module RBS
  class Parser
    class SyntaxError < ParsingError
      attr_reader token_str: String
      attr_reader error_value: untyped
      attr_reader value_stack: untyped?

      def initialize: (token_str: String, error_value: untyped, ?value_stack: untyped?) -> void
    end

    class LexerError < ParsingError
      attr_reader input: String
      attr_reader location: Location

      def initialize: (input: String, location: Location) -> void
    end

    class SemanticsError < ParsingError
      attr_reader subject: untyped
      attr_reader location: Location
      attr_reader original_message: String

      def initialize: (String message, subject: untyped, location: Location) -> void
    end

    def self.parse_method_type: (String | Buffer, ?variables: Array[Symbol], ?eof_re: Regexp?) -> MethodType

    def self.parse_type: (String | Buffer, ?variables: Array[Symbol], ?eof_re: Regexp?) -> Types::t

    def self.parse_signature: (String | Buffer, ?eof_re: Regexp?) -> Array[AST::Declarations::t]
  end
end
