exclude :test_dup, "needs investigation"
exclude :test_add_file, "needs investigation"
exclude :test_nosegv_on_cleanup, "needs investigation"
exclude :test_set_errors, "needs investigation"
exclude :test_verify, "needs investigation"
