AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'lib/bin/**/*'
    - 'lib/json/**/*'
    - 'lib/mri/**/*'
    - 'lib/patches/**/*'
    - 'lib/pr-zlib/**/*'
    - 'lib/ruby/**/*'
    - 'lib/rubysl/**/*'
    - 'lib/truffleruby-tool/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'tool/**/*'
    - 'truffleruby/target/classes/**/*'

Style/IndentationWidth:
  Enabled: true

Style/CaseIndentation:
  Enabled: true
  EnforcedStyle: 'end'

Style/IndentationConsistency:
  Enabled: true
