AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - '*.rb'
    - 'bin/**/*'
    - 'lib/bin/**/*'
    - 'lib/json/**/*'
    - 'lib/mri/**/*'
    - 'lib/patches/**/*'
    - 'lib/pr-zlib/**/*'
    - 'lib/ruby/**/*'
    - 'lib/rubysl/**/*'
    - 'mxbuild/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'tool/**/*'
    - 'truffleruby/target/classes/**/*'

# Department 'Lint' (58):
Lint/AmbiguousOperator:
  Description: Checks for ambiguous operators in the first argument of a method invocation
    without parentheses.
  StyleGuide: "#method-invocation-parens"
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Description: Checks for ambiguous regexp literals in the first argument of a method
    invocation without parentheses.
  Enabled: true

# Supports --auto-correct
Lint/BlockAlignment:
  Description: Align block ends correctly.
  Enabled: true
  EnforcedStyleAlignWith: either
  SupportedStylesAlignWith:
  - either
  - start_of_block
  - start_of_line

Lint/CircularArgumentReference:
  Description: Default values in optional keyword arguments and optional ordinal arguments
    should not refer back to the name of the argument.
  Enabled: true

Lint/ConditionPosition:
  Description: Checks for condition placed in a confusing position relative to the keyword.
  StyleGuide: "#same-line-condition"
  Enabled: true

# Supports --auto-correct
Lint/Debugger:
  Description: Check for debugger calls.
  Enabled: true

# Supports --auto-correct
Lint/DefEndAlignment:
  Description: Align ends corresponding to defs correctly.
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
  SupportedStylesAlignWith:
  - start_of_line
  - def
  AutoCorrect: false

# Supports --auto-correct
Lint/DeprecatedClassMethods:
  Description: Check for deprecated class method calls.
  Enabled: true

Lint/DuplicateCaseCondition:
  Description: Do not repeat values in case conditionals.
  Enabled: true

Lint/DuplicateMethods:
  Description: Check for duplicate method definitions.
  Enabled: true

Lint/DuplicatedKey:
  Description: Check for duplicate keys in hash literals.
  Enabled: true

Lint/EachWithObjectArgument:
  Description: Check for immutable argument given to each_with_object.
  Enabled: true

Lint/ElseLayout:
  Description: Check for odd code arrangement in an else block.
  Enabled: true

Lint/EmptyEnsure:
  Description: Checks for empty ensure block.
  Enabled: true

Lint/EmptyExpression:
  Description: Checks for empty expressions.
  Enabled: true

# Supports --auto-correct
Lint/EmptyInterpolation:
  Description: Checks for empty string interpolation.
  Enabled: true

Lint/EmptyWhen:
  Description: Checks for `when` branches with empty bodies.
  # disabled, used quite often
  Enabled: false

# Supports --auto-correct
Lint/EndAlignment:
  Description: Align ends correctly.
  Enabled: true
  EnforcedStyleAlignWith: keyword
  SupportedStylesAlignWith:
  - keyword
  - variable
  - start_of_line
  AutoCorrect: false

Lint/EndInMethod:
  Description: END blocks should not be placed inside method definitions.
  Enabled: true

Lint/EnsureReturn:
  Description: Do not use return in an ensure block.
  StyleGuide: "#no-return-ensure"
  Enabled: true

Lint/FloatOutOfRange:
  Description: Catches floating-point literals too large or small for Ruby to represent.
  Enabled: true

Lint/FormatParameterMismatch:
  Description: The number of parameters to format/sprint must match the fields.
  Enabled: true

Lint/HandleExceptions:
  Description: Don't suppress exception.
  StyleGuide: "#dont-hide-exceptions"
  Enabled: true

Lint/ImplicitStringConcatenation:
  Description: Checks for adjacent string literals on the same line, which could better
    be represented as a single string literal.
  Enabled: true

Lint/IneffectiveAccessModifier:
  Description: Checks for attempts to use `private` or `protected` to set the visibility
    of a class method, which does not work.
  Enabled: true

# Supports --auto-correct
Lint/InheritException:
  Description: Avoid inheriting from the `Exception` class.
  Enabled: true
  EnforcedStyle: runtime_error
  SupportedStyles:
  - runtime_error
  - standard_error
  Exclude:
  - truffleruby/src/main/ruby/core/exception.rb

Lint/InvalidCharacterLiteral:
  Description: Checks for invalid character literals with a non-escaped whitespace character.
  Enabled: true

Lint/LiteralInCondition:
  Description: Checks of literals used in conditions.
  Details: >-
      Pattern `while true` is allowed, disable the cop with
      `while true # rubocop:disable Lint/LiteralInCondition` in this case.
  Enabled: true
  Exclude:
  - lib/truffle/java/java_ext/*.rb

# Supports --auto-correct
Lint/LiteralInInterpolation:
  Description: Checks for literals used in interpolation.
  Enabled: true

Lint/Loop:
  Description: Use Kernel#loop with break rather than begin/end/until or begin/end/while
    for post-loop tests.
  StyleGuide: "#loop-with-break"
  # disabled, begin/end/until or begin/end/while seems better alternative to loop and a break
  Enabled: false

# Supports --auto-correct
Lint/MultipleCompare:
  Description: Use `&&` operator to compare multiple value.
  Enabled: true

Lint/NestedMethodDefinition:
  Description: Do not use nested method definitions.
  StyleGuide: "#no-nested-methods"
  Enabled: true

Lint/NextWithoutAccumulator:
  Description: Do not omit the accumulator when calling `next` in a `reduce`/`inject`
    block.
  Enabled: true

Lint/NonLocalExitFromIterator:
  Description: Do not use return in iterator to cause non-local exit.
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Description: Checks for method calls with a space before the opening parenthesis.
  StyleGuide: "#parens-no-spaces"
  Enabled: true

# Supports --auto-correct
Lint/PercentStringArray:
  Description: Checks for unwanted commas and quotes in %w/%W literals.
  Enabled: true

# Supports --auto-correct
Lint/PercentSymbolArray:
  Description: Checks for unwanted commas and colons in %i/%I literals.
  Enabled: true

Lint/RandOne:
  Description: Checks for `rand(1)` calls. Such calls always return `0` and most likely
    a mistake.
  Enabled: true

Lint/RequireParentheses:
  Description: Use parentheses in the method call to avoid confusion about precedence.
  Enabled: true

Lint/RescueException:
  Description: Avoid rescuing the Exception class.
  StyleGuide: "#no-blind-rescues"
  Enabled: true

# Supports --auto-correct
Lint/SafeNavigationChain:
  Description: Do not chain ordinary method call after safe navigation operator.
  Enabled: true

Lint/ShadowedException:
  Description: Avoid rescuing a higher level exception before a lower level exception.
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Description: Do not use the same name as outer local variable for block arguments
    or block local variables.
  Enabled: true

# Supports --auto-correct
Lint/StringConversionInInterpolation:
  Description: Checks for Object#to_s usage in string interpolation.
  StyleGuide: "#no-to-s"
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Description: Do not use prefix `_` for a variable that is used.
  Enabled: true

# Supports --auto-correct
Lint/UnifiedInteger:
  Description: Use Integer instead of Fixnum or Bignum
  # disabled, not a 2.4 yet
  Enabled: false

# Supports --auto-correct
Lint/UnneededDisable:
  Description: 'Checks for rubocop:disable comments that can be removed. Note: this
    cop is not disabled when disabling all cops. It must be explicitly disabled.'
  Enabled: true

# Supports --auto-correct
Lint/UnneededSplatExpansion:
  Description: Checks for splat unnecessarily being called on literals
  Enabled: true

Lint/UnreachableCode:
  Description: Unreachable code.
  Enabled: true

# Supports --auto-correct
Lint/UnusedBlockArgument:
  Description: Checks for unused block arguments.
  StyleGuide: "#underscore-unused-vars"
  Enabled: true
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: false

# Supports --auto-correct
Lint/UnusedMethodArgument:
  Description: Checks for unused method arguments.
  StyleGuide: "#underscore-unused-vars"
  # disabled, used often in primitives
  Enabled: false
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true

Lint/UselessAccessModifier:
  Description: Checks for useless access modifiers.
  Enabled: true
  ContextCreatingMethods: []
  MethodCreatingMethods: []

Lint/UselessAssignment:
  Description: Checks for useless assignment to a local variable.
  StyleGuide: "#underscore-unused-vars"
  Enabled: true

Lint/UselessComparison:
  Description: Checks for comparison of something with itself.
  Enabled: true

Lint/UselessElseWithoutRescue:
  Description: Checks for useless `else` in `begin..end` without `rescue`.
  Enabled: true

Lint/UselessSetterCall:
  Description: Checks for useless setter call to a local variable.
  Enabled: true

Lint/Void:
  Description: Possible use of operator/literal/variable in void context.
  Enabled: true



Style/IndentationWidth:
  Enabled: true

Style/CaseIndentation:
  Enabled: true
  EnforcedStyle: 'end'

Style/IndentationConsistency:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
