AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - '*.rb'
    - 'bin/**/*'
    - 'lib/bin/**/*'
    - 'lib/json/**/*'
    - 'lib/mri/**/*'
    - 'lib/patches/**/*'
    - 'lib/pr-zlib/**/*'
    - 'lib/ruby/**/*'
    - 'lib/rubysl/**/*'
    - 'lib/truffleruby-tool/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'tool/**/*'
    - 'truffleruby/target/classes/**/*'
    - 'mxbuild/**/*'

# Supports --auto-correct
Lint/DeprecatedClassMethods:
  Description: Check for deprecated class method calls.
  Enabled: true

# Supports --auto-correct
Lint/EndAlignment:
  Description: Align ends correctly.
  Enabled: true
  EnforcedStyleAlignWith: keyword
  SupportedStylesAlignWith:
  - keyword
  - variable
  - start_of_line
  AutoCorrect: false

Lint/LiteralInCondition:
  Description: Checks of literals used in conditions.
  Enabled: true
  Exclude:
  - lib/truffle/java/java_ext/*.rb

Style/IndentationWidth:
  Enabled: true

Style/CaseIndentation:
  Enabled: true
  EnforcedStyle: 'end'

Style/IndentationConsistency:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
