exclude :test_filter_column, "undefined symbol: rb_parser_st_locale_insensitive_strncasecmp"
exclude :test_filter_filename, "undefined symbol: rb_parser_st_locale_insensitive_strncasecmp"
exclude :test_filter_filename_unset, "undefined symbol: rb_parser_st_locale_insensitive_strncasecmp"
exclude :test_filter_lineno, "undefined symbol: rb_parser_st_locale_insensitive_strncasecmp"
exclude :test_filter_lineno_set, "undefined symbol: rb_parser_st_locale_insensitive_strncasecmp"
exclude :test_filter_state, "undefined symbol: rb_parser_st_locale_insensitive_strncasecmp"
