exclude :test_assign_error_const, "needs investigation"
exclude :test_call, "needs investigation"
exclude :test_local_variables, "needs investigation"
exclude :test_operator_ambiguous, "needs investigation"
exclude :test_rescue_class, "needs investigation"
exclude :test_var_ref, "needs investigation"
exclude :test_block_variables, "needs investigation"
exclude :test_event_coverage, "needs investigation"
