exclude :test_pattern_matching_415, "needs investigation"
exclude :test_pattern_matching_427, "needs investigation"
exclude :test_pattern_matching_439, "needs investigation"
exclude :test_params_mlhs, "transient"
exclude :test_pattern_matching_216, " case 0; in *a,b,c; end ."
exclude :test_pattern_matching_402, " case 0; in [a]; end ."
exclude :test_pattern_matching_234, " case 0; in *,a; end ."
exclude :test_pattern_matching_166, " case 0; in a; end ."
exclude :test_pattern_matching_171, " case 0; in a,; end ."
exclude :test_pattern_matching_371, " case 0; in A[a]; end ."
exclude :test_pattern_matching_321, " case 0; in 0 => a; end ."
exclude :test_pattern_matching_183, " case 0; in a,b; end ."
