/******************************************************************************/
/* This file is generated by the bin/template script and should not be        */
/* modified manually. See                                                     */
/* templates/java/org/yarp/ParseResult.java.erb                               */
/* if you are looking to modify the                                           */
/* template                                                                   */
/******************************************************************************/
package org.yarp;

// GENERATED BY ParseResult.java.erb
// @formatter:off

public final class ParseResult {

    public static final class Error {
        private final String message;
        private final Nodes.Location location;

        public Error(String message, Nodes.Location location) {
            this.message = message;
            this.location = location;
        }

        public String getMessage() {
            return message;
        }

        public Nodes.Location getLocation() {
            return location;
        }
    }

    public static final class Warning {
        private final String message;
        private final Nodes.Location location;

        public Warning(String message, Nodes.Location location) {
            this.message = message;
            this.location = location;
        }

        public String getMessage() {
            return message;
        }

        public Nodes.Location getLocation() {
            return location;
        }
    }

    private final Nodes.Node value;
    private final Error[] errors;
    private final Warning[] warnings;

    public ParseResult(Nodes.Node value, Error[] errors, Warning[] warnings) {
        this.value = value;
        this.errors = errors;
        this.warnings = warnings;
    }

    public Nodes.Node getValue() {
        return value;
    }

    public Error[] getErrors() {
        return errors;
    }

    public Warning[] getWarnings() {
        return warnings;
    }
}

