exclude :test_compsub, "needs investigation"
exclude :test_expt, "needs investigation"
exclude :test_fixed_bug, "needs investigation"
exclude :test_marshal_compatibility, "needs investigation"
exclude :test_mul, "needs investigation"
exclude :test_parse, "needs investigation"
exclude :test_ruby19, "needs investigation"
exclude :test_rationalize, "needs investigation"
