exclude :test_custom_formatter, "NameError: uninitialized constant ErrorHighlight::Ractor"
exclude :test_OP_ASGN1_op_4, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_ATTRASGN_2, "<\"undefined method `[]=' for nil:NilClass\\n\" +"
exclude :test_OPCALL_binary_2, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_ATTRASGN_4, "<\"undefined method `[]=' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN1_op_2, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_OPCALL_unary_2, "<\"undefined method `+@' for nil:NilClass\\n\" +"
exclude :test_CALL_arg_5, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN1_aref_1, "<\"undefined method `[]' for nil:NilClass\\n\" +"
exclude :test_CALL_arg_1, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_COLON2_2, "<\"uninitialized constant ErrorHighlightTest::NotDefined\\n\" +"
exclude :test_OP_ASGN2_op_2, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_CALL_arg_3, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_const_get, "<\"uninitialized constant ErrorHighlightTest::NotDefined\\n\" +"
exclude :test_OP_ASGN2_read_3, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN2_read_1, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_CALL_noarg_2, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_OP_CDECL_toplevel_2, "<\"undefined method `+' for ErrorHighlightTest:Class\\n\" +"
exclude :test_CALL_noarg_4, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_CALL_send, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_CALL_aref_1, "<\"undefined method `[]' for nil:NilClass\\n\" +"
exclude :test_CALL_aref_5, "<\"undefined method `[]' for nil:NilClass\\n\" +"
exclude :test_CALL_aset, "<\"undefined method `[]=' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN2_write_2, "<\"undefined method `foo=' for #<Object:0x1d6a1b8>\\n\" +"
exclude :test_OP_ASGN1_aset_1, "<\"undefined method `[]=' for #<Object:0x1d6a268>\\n\" +"
exclude :test_OP_ASGN1_aset_3, "<\"undefined method `[]=' for #<Object:0x1d6a318>\"> expected but was"
exclude :test_QCALL_2, "<\"undefined method `foo' for 1:Integer\\n\" +"
exclude :test_FCALL_2, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_COLON3, "<\"uninitialized constant NotDefined\\n\" +"
exclude :test_OP_CDECL_op_1, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_OP_CDECL_read_1, "<\"uninitialized constant ErrorHighlightTest::OP_CDECL_TEST::NotDefined\\n\" +"
exclude :test_OP_CDECL_op_3, "NoMethodError expected but nothing was raised."
exclude :test_local_variable_get, "<\"local variable `foo' is not defined for #<Binding:0x1d6a628>\\n\" +"
exclude :test_OP_ASGN1_aset_2, "<\"undefined method `[]=' for #<Object:0x1d6a6a8>\\n\" +"
exclude :test_QCALL_1, "<\"undefined method `foo' for 1:Integer\\n\" +"
exclude :test_OP_ASGN2_write_1, "<\"undefined method `foo=' for #<Object:0x1d6a7f8>\\n\" +"
exclude :test_OP_ASGN2_write_3, "<\"undefined method `foo=' for #<Object:0x1d6a8a8>\\n\" +"
exclude :test_OP_ASGN1_aset_4, "<\"undefined method `[]=' for #<Object:0x1d6a958>\\n\" +"
exclude :test_OP_CDECL_read_2, "<\"uninitialized constant ErrorHighlightTest::OP_CDECL_TEST::NotDefined\\n\" +"
exclude :test_OP_CDECL_op_2, "NoMethodError expected but nothing was raised."
exclude :test_VCALL_2, "<\"undefined local variable or method `foo' for nil:NilClass\\n\" +"
exclude :test_FCALL_1, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_CALL_op_asgn, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_OP_CDECL_toplevel_1, "<\"uninitialized constant NotDefined\\n\" +"
exclude :test_CALL_noarg_1, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_CALL_noarg_3, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_CALL_aref_4, "<\"undefined method `[]' for #<Object:0x1d6ad58>\\n\" +"
exclude :test_CALL_aref_2, "<\"undefined method `[]' for nil:NilClass\\n\" +"
exclude :test_explicit_raise_no_method_error, "<\"NoMethodError\\n\" + \"\\n\" + \"      raise NoMethodError\\n\" + \"      ^^^^^\"> expected but was"
exclude :test_explicit_raise_name_error, "<\"NameError\\n\" + \"\\n\" + \"      raise NameError\\n\" + \"      ^^^^^\"> expected but was"
exclude :test_OP_ASGN2_read_2, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN1_op_1, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_ATTRASGN_5, "<\"undefined method `foo=' for nil:NilClass\\n\" +"
exclude :test_OPCALL_binary_3, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_ATTRASGN_3, "<\"undefined method `foo=' for nil:NilClass\\n\" +"
exclude :test_OPCALL_binary_1, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_ATTRASGN_1, "<\"undefined method `[]=' for nil:NilClass\\n\" +"
exclude :test_CALL_arg_2, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN2_op_3, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_CONST, "<\"uninitialized constant ErrorHighlightTest::NotDefined\\n\" +"
exclude :test_OP_ASGN1_aref_4, "<\"undefined method `[]' for nil:NilClass\\n\" +"
exclude :test_OP_ASGN2_op_1, "<\"undefined method `+' for nil:NilClass\\n\" +"
exclude :test_COLON2_1, "[NameError] exception expected, not #<TypeError: 1:Integer is not a class/module>."
exclude :test_CALL_arg_6, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_OPCALL_unary_1, "<\"undefined method `+@' for nil:NilClass\\n\" + \"\\n\" + \"      + nil\\n\" + \"      ^\"> expected but was"
exclude :test_hard_tabs, "<\"undefined method `time' for 1:Integer\\n\" +"
exclude :test_CALL_arg_4, "<\"undefined method `foo' for nil:NilClass\\n\" +"
exclude :test_no_final_newline, "<\"undefined method `time' for 1:Integer\\n\" + \"\\n\" + \"1.time {}\\n\" + \" ^^^^^\"> expected but was"
exclude :test_OP_ASGN1_aref_2, "<\"undefined method `[]' for nil:NilClass\\n\" +"
exclude :test_OP_CDECL_read_3, "<\"uninitialized constant ErrorHighlightTest::OP_CDECL_TEST::NotDefined\"> expected but was"
