exclude :test_abort_tls, "needs investigation"
exclude :test_active_clear_data_connection, "needs investigation"
exclude :test_active_private_data_connection, "needs investigation"
exclude :test_passive_clear_data_connection, "needs investigation"
exclude :test_passive_private_data_connection, "needs investigation"
exclude :test_tls_post_connection_check, "needs investigation"
exclude :test_tls_unknown_ca, "needs investigation"
exclude :test_tls_verify_none, "needs investigation"
exclude :test_tls_with_ca_file, "needs investigation"
exclude :test_read_timeout_exceeded, "spurious failures on Darwin"
exclude :test_read_timeout_not_exceeded, "spurious failures on Darwin"
exclude :test_list_read_timeout_exceeded, "spurious failures on Darwin"
exclude :test_list_read_timeout_not_exceeded, "spurious failures on Darwin"
exclude :test_retrbinary_read_timeout_exceeded , "spurious failures on Darwin"
exclude :test_retrbinary_read_timeout_not_exceeded, "spurious failures on Darwin"
exclude :test_getbinaryfile_command_injection, "needs investigation"
exclude :test_getbinaryfile_command_injection, "needs investigation"
