exclude :test_Rational_with_invalid_exception, "[ArgumentError] exception expected, not #<TypeError: denominator is not an Integer>."
exclude :test_Rational_without_exception, "TypeError: denominator is not an Integer"
exclude :test_conv, "RangeError: can't' convert 1+2i into Rational"
exclude :test_marshal, "TypeError expected but nothing was raised."
exclude :test_marshal_compatibility, "TypeError expected but nothing was raised."
exclude :test_parse, "Rational(\"5__5/33\")."
exclude :test_power_of_0, "Expected 0.0 to be an instance of Rational, not Float."
exclude :test_power_overflow, "FloatDomainError: Infinity"
exclude :test_ratsub, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_supp, "<3.330669073875469e-16> expected but was <3.3306690738754696e-16>."
