exclude :test_assert_equal_different_hex_invisible, "needs investigation"
exclude :test_assert_equal_different_collection_array_hex_invisible, "needs investigation"
exclude :test_assert_equal_different_hex, "needs investigation"
exclude :test_assert_raises_triggered_different_msg, "needs investigation"
exclude :test_assert_raises_triggered_different, "needs investigation"
exclude :test_assert_in_epsilon_triggered_negative_case, "needs investigation"
exclude :test_assert_equal_different_collection_hash_hex_invisible, "needs investigation"
