exclude :test_width_underflow, "needs investigation"
exclude :test_binary, "needs investigation"
exclude :test_float_prec, "needs investigation"
exclude :test_integer, "needs investigation"
exclude :test_named_typed, "needs investigation"
exclude :test_named_typed_enc, "needs investigation"
exclude :test_named_untyped, "needs investigation"
exclude :test_named_untyped_enc, "needs investigation"
exclude :test_negative_width_overflow, "needs investigation"
exclude :test_percent_sign_at_end, "needs investigation"
exclude :test_rational, "needs investigation"
exclude :test_star, "needs investigation"
exclude :test_named_default, "needs investigation"
exclude :test_no_hidden_garbage, "skipped in CI due to thread count, depends on ObjectSpace.count_objects"
