exclude :test_argf_memsize, "NoMethodError: undefined method `inplace_mode=' for #<Truffle::ARGFClass:0x418>"
exclude :test_count_imemo_objects, "NoMethodError: undefined method `count_imemo_objects' for ObjectSpace:Module"
exclude :test_count_objects_size_with_wrong_type, "[TypeError] exception expected, not #<NoMethodError: undefined method `fetch' for 0:Integer>."
exclude :test_count_symbols, "NoMethodError: undefined method `count_symbols' for ObjectSpace:Module"
exclude :test_dump_addresses_match_dump_all_addresses, "<\"true\"> expected but was <\"{\\\"address\\\":\\\"0xb8\\\",\\\"class\\\":\\\"0xc8\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\">."
exclude :test_dump_all, "number of strings."
exclude :test_dump_all_full, "<\"nil\"> expected but was <\"{\\\"address\\\":\\\"0x5218\\\",\\\"class\\\":\\\"0x148\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}nil\">."
exclude :test_dump_all_single_generation, "<\"nil\"> expected but was <\"{\\\"address\\\":\\\"0x4d10\\\",\\\"class\\\":\\\"0xc8\\\",\\\"memsize\\\":0,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}nil\">."
exclude :test_dump_array, "Expected \"{\\\"address\\\":\\\"0x5f8\\\",\\\"class\\\":\\\"0x608\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"ARRAY\\\",\\\"length\\\":0}\" to include \"\\\"length\\\":0, \\\"embedded\\\":true\"."
exclude :test_dump_callinfo_includes_mid, "Expected \"\" to include \"\\\"mid\\\":\\\"baz\\\"\"."
exclude :test_dump_class_addresses_match_dump_all_addresses, "<\"true\"> expected but was <\"{\\\"address\\\":\\\"0xb8\\\",\\\"class\\\":\\\"0xc8\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\">."
exclude :test_dump_control_char, "Expected \"{\\\"address\\\":\\\"0x6c8\\\",\\\"class\\\":\\\"0x6b8\\\",\\\"memsize\\\":2,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":1,\\\"value\\\":\\\"\\u007F\\\",\\\"encoding\\\":\\\"UTF-8\\\"}\" to include \"\\\"value\\\":\\\"\\\\u007f\\\"\"."
exclude :test_dump_dynamic_symbol, "Expected /\"type\":\"SYMBOL\"/ to match \"{\\\"address\\\":\\\"0x60\\\",\\\"class\\\":\\\"0x708\\\",\\\"memsize\\\":0,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\"."
exclude :test_dump_escapes_method_name, "Expected \"{\\\"address\\\":\\\"0x748\\\",\\\"class\\\":\\\"0x6b8\\\",\\\"memsize\\\":12,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":11,\\\"value\\\":\\\"TEST STRING\\\",\\\"encoding\\\":\\\"UTF-8\\\"}\" to include \"\\\"method\\\":\\\"foo\\\\\\\"bar\\\"\"."
exclude :test_dump_flags, "Expected /\"wb_protected\":true, \"old\":true/ to match \"{\\\"address\\\":\\\"0x80\\\",\\\"class\\\":\\\"0x6b8\\\",\\\"memsize\\\":0,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":3,\\\"value\\\":\\\"foo\\\",\\\"encoding\\\":\\\"UTF-8\\\"}\"."
exclude :test_dump_includes_imemo_type, "<\"nil\"> expected but was <\"{\\\"address\\\":\\\"0x5218\\\",\\\"class\\\":\\\"0x128\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}nil\">."
exclude :test_dump_includes_slot_size, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_dump_object, "Expected \"{\\\"address\\\":\\\"0x828\\\",\\\"class\\\":\\\"0x818\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\" to include \"\\\"embedded\\\":true\"."
exclude :test_dump_objects_dumps_page_slot_sizes, "<\"true\"> expected but was <\"{\\\"address\\\":\\\"0x5218\\\",\\\"class\\\":\\\"0x148\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}true\">."
exclude :test_dump_reference_addresses_match_dump_all_addresses, "<\"true\"> expected but was <\"{\\\"address\\\":\\\"0xb8\\\",\\\"class\\\":\\\"0xc8\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\">."
exclude :test_dump_shapes, "NoMethodError: undefined method `dump_shapes' for ObjectSpace:Module"
exclude :test_dump_singleton_class, "Expected \"{\\\"address\\\":\\\"0x8d8\\\",\\\"class\\\":\\\"0x3c8\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\" to include \"\\\"name\\\":\\\"Object\\\"\"."
exclude :test_dump_special_consts, "<\"null\"> expected but was <\"{\\\"address\\\":\\\"0x2\\\",\\\"class\\\":\\\"0x918\\\",\\\"memsize\\\":0,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\">."
exclude :test_dump_special_floats, "Expected /\"value\":\"NaN\"/ to match \"{\\\"address\\\":\\\"0x27ff8000000000000\\\",\\\"class\\\":\\\"0x958\\\",\\\"memsize\\\":0,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\"."
exclude :test_dump_string_coderange, "Expected \"{\\\"address\\\":\\\"0x988\\\",\\\"class\\\":\\\"0x6b8\\\",\\\"memsize\\\":12,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":11,\\\"value\\\":\\\"TEST STRING\\\",\\\"encoding\\\":\\\"UTF-8\\\"}\" to include \"\\\"coderange\\\":\\\"7bit\\\"\"."
exclude :test_dump_to_default, "Expected /\"embedded\":true, \"bytesize\":7, \"value\":\"hello w\", \"encoding\":\"UTF-8\"/ to match \"{\\\"address\\\":\\\"0x9c8\\\",\\\"class\\\":\\\"0x6b8\\\",\\\"memsize\\\":8,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":7,\\\"value\\\":\\\"hello w\\\",\\\"encoding\\\":\\\"UTF-8\\\"}\"."
exclude :test_dump_to_io, "Expected /\"embedded\":true, \"bytesize\":7, \"value\":\"hello w\", \"encoding\":\"UTF-8\"/ to match \"{\\\"address\\\":\\\"0x9f8\\\",\\\"class\\\":\\\"0x6b8\\\",\\\"memsize\\\":8,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":7,\\\"value\\\":\\\"hello w\\\",\\\"encoding\\\":\\\"UTF-8\\\"}\"."
exclude :test_dump_uninitialized_file, "Expected /\"type\":\"FILE\"/ to match \"{\\\"address\\\":\\\"0xb8\\\",\\\"class\\\":\\\"0xc8\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\"."
exclude :test_internal_class_of, "NoMethodError: undefined method `internal_class_of' for ObjectSpace:Module"
exclude :test_internal_class_of_on_ast, "NameError: uninitialized constant TestObjSpace::RubyVM"
exclude :test_internal_super_of, "NoMethodError: undefined method `internal_super_of' for ObjectSpace:Module"
exclude :test_load_allocation_path_compile_file, "NameError: uninitialized constant TestObjSpace::Tempfile"
exclude :test_load_allocation_path_load, "NameError: uninitialized constant TestObjSpace::Tempfile"
exclude :test_memsize_of_iseq, "NameError: uninitialized constant TestObjSpace::RubyVM"
exclude :test_memsize_of_root_shared_string, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_name_error_message, "spurious; <NameError> expected but was <#<Class:0x2966028>>."
exclude :test_reachable_objects_from, "<[Array, \"a\", \"b\", \"c\"]> expected but was <[Array, \"b\", \"c\", \"a\"]>."
exclude :test_reachable_objects_size, "NoMethodError: undefined method `each' for nil:NilClass"
exclude :test_trace_object_allocations, "<\"/b/b/e/main/test/mri/tests/objspace/test_objspace.rb\"> expected but was <nil>."
exclude :test_utf8_method_names, "{\"address\":\"0xc68\",\"class\":\"0x6b8\",\"memsize\":3,\"flags\":{},\"type\":\"STRING\",\"bytesize\":2,\"value\":\"12\",\"encoding\":\"UTF-8\"}."
