exclude :test_caller_lev, "NoMethodError: undefined method `map' for nil:NilClass"
exclude :test_caller_lev_and_n, "NoMethodError: undefined method `map' for nil:NilClass"
exclude :test_caller_limit_cfunc_iseq_no_pc, "<{[\"each\", \"group_by\"]=>[1]}> expected but was <{[\"group_by\", \"each\"]=>[1]}>."
exclude :test_caller_location_inspect_cfunc_iseq_no_pc, "<\"[\\\"/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_backtrace.rb:218:in `times'\\\"]\"> expected but was <\"[\\\"<internal:core> core/enumerable.rb:107:in `block in map'\\\"]\">."
exclude :test_caller_location_path_cfunc_iseq_no_pc, "<\"/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_backtrace.rb\"> expected but was <\"<internal:core> core/enumerable.rb\">."
exclude :test_caller_locations_label, "<\"rescue in test_caller_locations_label\"> expected but was <\"test_caller_locations_label\">."
exclude :test_caller_to_enum, "| -:3:in `foo': unhandled exception"
exclude :test_each_backtrace_location, "<[\"/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/lib/test/unit/testcase.rb:200:in `run_test'\","
exclude :test_notty_backtrace, "| -:7:in `bar': bar! (RuntimeError)"
