exclude :test_Integer, "[Encoding::CompatibilityError] exception expected, not #<ArgumentError: invalid value for Integer(): 0>."
exclude :test_Integer_when_to_str, "TypeError: can't convert Object into Integer"
exclude :test_Integer_with_base, "TypeError expected but nothing was raised."
exclude :test_Integer_with_exception_keyword, "RuntimeError: "
exclude :test_Integer_with_invalid_exception, "ArgumentError expected but nothing was raised."
exclude :test_bitwise_and_with_integer_coercion, "TypeError: #<Class:0x4d8> can't be coerced into Integer"
exclude :test_bitwise_or_with_integer_coercion, "TypeError: #<Class:0x508> can't be coerced into Integer"
exclude :test_bitwise_xor_with_integer_coercion, "TypeError: #<Class:0x538> can't be coerced into Integer"
exclude :test_ceil, "<11110> expected but was <11120>."
exclude :test_ceildiv, "NoMethodError: undefined method `-@' for #<Object:0x578>"
exclude :test_floor, "<-100000000000000000000> expected but was <0>."
exclude :test_pow, "FloatDomainError: Infinity"
exclude :test_round, "<300> expected but was <200>."
exclude :test_square_root, "10**33."
