exclude :test_sprintf_s, "<#<Encoding:EUC-JP>> expected but was <#<Encoding:ASCII-8BIT>>."
exclude :test_str_aref_substr, "ArgumentError: regexp preprocess failed: invalid multibyte character"
exclude :test_str_assign, "[Encoding::CompatibilityError] exception expected, not #<IndexError: index -1 out of string>."
exclude :test_str_assign_len, "[Encoding::CompatibilityError] exception expected, not #<IndexError: index -1 out of string>."
exclude :test_str_chop, "\"\\xA1\".force_encoding(\"EUC-JP\").chop."
exclude :test_str_count, "\"\".force_encoding(\"ASCII-8BIT\").count(\"\\xA1\".force_encoding(\"EUC-JP\"))."
exclude :test_str_end_with?, "\"\\x80\".force_encoding(\"UTF-8\").end_with?(\"\\x80\".force_encoding(\"UTF-8\"))."
exclude :test_str_include?, "Encoding::CompatibilityError expected but nothing was raised."
exclude :test_str_index, "\"\\xA1\".force_encoding(\"EUC-JP\").index(\"\\x80\".force_encoding(\"EUC-JP\"), -1)."
exclude :test_str_partition, "transient: already checked in the caller, String#index (java.lang.AssertionError) from org.truffleruby.core.string.StringNodes$StringCharacterIndexNode.singleByteOptimizable(StringNodes.java:3859)"
exclude :test_str_rindex, "Encoding::CompatibilityError expected but nothing was raised."
exclude :test_str_rpartition, "\"\\x80\".force_encoding(\"ASCII-8BIT\").rpartition(\"\\xC2\\xA1\".force_encoding(\"Windows-31J\"))."
exclude :test_str_smart_chomp, "Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-16BE"
exclude :test_str_split, "[ArgumentError, RegexpError] expected but nothing was raised."
exclude :test_str_squeeze, "\"\".force_encoding(\"ASCII-8BIT\").squeeze(\"\\xA1\".force_encoding(\"EUC-JP\"))."
