exclude :test_DATA_binmode, "assert_separately failed with error message"
exclude :test_advise, "tmpfs on Linux 6.8.0-41-generic."
exclude :test_advise_pipe, "[Errno::ESPIPE, Errno::EINVAL] exception expected, not #<RuntimeError: IO#advise not implemented>."
exclude :test_autoclose_false_closed_by_finalizer, "too slow"
exclude :test_autoclose_true_closed_by_finalizer, "Errno::EBADF expected but nothing was raised."
exclude :test_binmode_pipe, "Expected #<IO:fd 46> to be binmode?."
exclude :test_cloexec, "Expected #<IO:fd 42> to be close_on_exec?."
exclude :test_close_on_exec, "TypeError: wrong argument type NilClass (expected Integer)"
exclude :test_close_read, "TypeError: wrong argument type NilClass (expected Integer)"
exclude :test_close_read_write_separately, "slow: 33.15s on truffleruby 24.2.0-dev-48f958a9*, like ruby 3.2.4, GraalVM CE JVM [arm64-darwin23] with Apple M1 Max: (10 vCPUs)"
exclude :test_close_uninitialized, "IOError expected but nothing was raised."
exclude :test_close_write, "TypeError: wrong argument type NilClass (expected Integer)"
exclude :test_copy_stream_dst_rbuf, "<\"abxyz\"> expected but was <\"abcxyz\">."
exclude :test_copy_stream_megacontent_nonblock, "transient, and very slow on aarch64-darwin"
exclude :test_copy_stream_pipe_nonblock, "retain-on-retag; very long string mismatch"
exclude :test_copy_stream_rbuf, "<3> expected but was <2>."
exclude :test_copy_stream_socket6, "retain-on-retag; very long string mismatch"
exclude :test_copy_stream_socket7, "NotImplementedError: fork is not available"
exclude :test_copy_stream_strio_off, "ArgumentError expected but nothing was raised."
exclude :test_copy_stream_to_duplex_io, "IOError: not opened for writing"
exclude :test_cross_thread_close_fd, "hangs"
exclude :test_cross_thread_close_stdio, "hangs"
exclude :test_dup, "TypeError: wrong argument type NilClass (expected Integer)"
exclude :test_dup_many, "ArgumentError: unknown exec option: :rlimit_nofile"
exclude :test_dup_timeout, "NoMethodError: undefined method `timeout=' for #<IO:(closed)>"
exclude :test_each_line, "<[\"foo\\n\"]> expected but was <[\"foo\"]>."
exclude :test_exclusive_mode, "[Errno::EEXIST] exception expected, not #<ArgumentError: invalid mode -- wx>."
exclude :test_explicit_path, "Expected /Fake Path/ to match \"#<IO:fd 0>\"."
exclude :test_fcntl_lock_linux, "NotImplementedError: fork is not available" if RUBY_PLATFORM.include?('linux')
exclude :test_flag, "ArgumentError expected but nothing was raised."
exclude :test_gets_chomp_rs_nil, "<\"a\\n\" + \"\\n\" + \"b\\n\" + \"\\n\"> expected but was <\"a\\n\" + \"\\n\" + \"b\\n\">."
exclude :test_gets_limit_extra_arg, "TypeError expected but nothing was raised."
exclude :test_invalid_advise, "Expected Exception(NotImplementedError) was raised, but the message doesn't match. Expected /:Normal/ to match \"Unsupported advice: Normal\"."
exclude :test_new_with_block, "expected: /IO入出力/"
exclude :test_pid_after_close_read, "IOError: closed stream"
exclude :test_print_separators, "<\"a:b:c\\n\"> expected but was <\"abc\\n\">."
exclude :test_puts_old_write, "expected: /[.#]write is outdated/"
exclude :test_race_closed_stream, "transient"
exclude :test_race_gets_and_close, "transient"
exclude :test_read_command, "[Errno::ENOENT, Errno::EINVAL] expected but nothing was raised."
exclude :test_read_lock, "RuntimeError expected but nothing was raised."
exclude :test_read_nonblock_invalid_exception, "[ArgumentError] exception expected, not #<IO::EAGAINWaitReadable: Resource temporarily unavailable>."
exclude :test_read_nonblock_zero_size, "Expected \"01234567\" to be empty."
exclude :test_readpartial_lock, "RuntimeError expected but nothing was raised."
exclude :test_readpartial_locktmp, "<100> expected but was <0>."
exclude :test_recycled_fd_close, "\"bad\" reader timeout."
exclude :test_reinitialize, "[RuntimeError] exception expected, not #<ArgumentError: wrong number of arguments (given 0, expected 1..3)>."
exclude :test_reopen, "<\"baz\\n\"> expected but was <nil>."
exclude :test_reopen_encoding, "<#<Encoding:EUC-JP>> expected but was <#<Encoding:UTF-8>>."
exclude :"test_reopen_nonascii(EUC-JP)", "Errno::EILSEQ: Invalid or incomplete multibyte or wide character - ��ӡ�" if RUBY_PLATFORM.include?('darwin')
exclude :"test_reopen_nonascii(Shift_JIS)", "Errno::EILSEQ: Invalid or incomplete multibyte or wide character - ���r�[" if RUBY_PLATFORM.include?('darwin')
exclude :test_reopen_opt, "Exception raised: <#<ArgumentError: wrong number of arguments (given 3, expected 1..2)>>"
exclude :test_reopen_opt_encoding, "Exception raised: <#<TypeError: no implicit conversion of Hash into String>>"
exclude :test_seek, "NameError: uninitialized constant TestIO::Bug" if RUBY_PLATFORM.include?('linux')
exclude :test_seek_symwhence, "TypeError: unsupported type [:SET]"
exclude :test_select_exceptfds, "Truffle::IOOperations.poll(acc, Truffle::IOOperations::POLLIN_SET | Truffle::IOOperations::POLLEX_SET, nil) returns POLLRDNORM|POLLPRI|POLLIN on Linux (correct) but POLLRDNORM|POLLIN on macOS (bug). With events=POLLPRI it hangs on macOS. It seems a bug of macOS poll() not handling TCP MSG_OOB. MSG_OOB is poorly supported across platforms anyway." if RUBY_PLATFORM.include?('darwin')
exclude :test_set_stdout, "Expected Exception(TypeError) was raised, but the message doesn't match. Expected /\\$標準出力 must.*, Xほげ given/ to match \"$stdout must have a write method, Xほげ given\"."
exclude :test_sysread_locktmp, "Exception(RuntimeError) with message matches to /can't modify string; temporarily locked/."
exclude :test_sysread_with_negative_length, "[ArgumentError] exception expected, not #<Errno::EFAULT: Bad address>."
exclude :test_threaded_flush, "slow: 32.30s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_ungetbyte, "Errno::EINVAL: Invalid argument"
exclude :test_ungetc, "IOError expected but nothing was raised."
exclude :test_uninitialized, "IOError expected but nothing was raised."
exclude :test_write_nonblock_invalid_exception, "ArgumentError expected but nothing was raised."
