exclude :test_errinfo_after_autoload, "Expected Exception(SyntaxError) was raised, but the message doesn't match. Expected /unknown regexp option - Q/ to match \"(eval):1: unknown regexp option: Q\"."
exclude :test_extra_encoding, "ArgumentError expected but nothing was raised."
exclude :test_nonascii_library_path, "assert_separately failed with error message"
exclude :test_replicate, "ArgumentError expected but nothing was raised."
exclude :test_singleton, "TypeError expected but nothing was raised."
