exclude :test_birthtime, "NoMethodError: undefined method `birthtime' for #<Pathname:a>"
exclude :test_each_entry_enumerator, "LocalJumpError: no block given (yield)"
exclude :test_find, "LocalJumpError: no block given (yield)"
exclude :test_mkpath, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_relative_path_from_mock, "TypeError: no implicit conversion of Object into String"
exclude :test_s_glob_3args, "<[#<Pathname:.>, #<Pathname:f>]> expected but was <[#<Pathname:.>, #<Pathname:..>, #<Pathname:f>]>."
exclude :test_split, "[TypeError] exception expected, not #<NoMethodError: undefined method `map' for nil:NilClass>."
exclude :test_world_readable?, "NoMethodError: undefined method `world_readable?' for FileTest:Module"
exclude :test_world_writable?, "NoMethodError: undefined method `world_writable?' for FileTest:Module"
