exclude :test_alias, "pid 57958 exit 0."
exclude :test_ancestors, "The JSON pure implementation is used so String class includes a JSON::Pure-specific module when JSON library is required"
exclude :test_ancestry_of_duped_classes, "Expected #<#<Class:0x578>:0x588> to not be a kind of #<Class:0x568>."
exclude :test_attr, "NameError expected but nothing was raised."
exclude :test_bad_constants_get, "[Bug #7573]: wrong constant name \"String::\" to get."
exclude :test_class_variable_in_dup_class, "[ruby-core:17019]."
exclude :test_const_defined?, "[EncodingError] exception expected, not #<NameError: wrong constant name �>."
exclude :test_const_set_invalid_name, "NameError expected but nothing was raised."
exclude :test_define_module_under_private_constant, "NameError expected but nothing was raised."
exclude :test_deprecate_constant, "expected: /#<Class:0xbd8>::FOO is deprecated/"
exclude :test_frozen_visibility, "[ruby-core:70828] [Bug #11532]."
exclude :test_include_into_module_already_included, "<[:sc, :m1, :m2, :c]> expected but was"
exclude :test_included_modules, "The JSON pure implementation is used so String class includes a JSON::Pure-specific module when JSON library is required"
exclude :test_initialize_copy, "TypeError expected but nothing was raised."
exclude :test_initialize_copy_empty, "TypeError expected but nothing was raised."
exclude :test_inspect_segfault, "[ruby-core:65214] [Bug #10282]."
exclude :test_invalid_attr, "NameError expected but nothing was raised."
exclude :test_method_redefinition, "Expected /:1876: warning: method redefined; discarding old foo/ to match \"\"."
exclude :test_module_function_inside_method, "[ruby-core:79751]."
exclude :test_module_name_in_singleton_method, "[Bug #14895]."
exclude :test_nested_defined, "Expected Object.const_defined?(\"TestModule::String\") to return false."
exclude :test_nested_defined_symbol, "NameError expected but nothing was raised."
exclude :test_nested_get, "NameError expected but nothing was raised."
exclude :test_prepend_after_include, "<[:m, :sc, :m, :c]> expected but was"
exclude :test_prepend_each_classes, "should be able to prepend each classes."
exclude :test_prepend_module_ancestors, "<[m0, m1, m3, m0, m1]> expected but was"
exclude :test_private_constant_in_class, "Exception(NameError) with message matches to /#<Class:0x2028>::FOO/."
exclude :test_private_constant_in_module, "<#<Module:0x2058>> expected but was"
exclude :test_private_constant_with_no_args, "pid 57996 exit 0."
exclude :test_private_top_methods, ":include should be private."
exclude :test_protected_singleton_method, "NoMethodError expected but nothing was raised."
exclude :test_redefinition_mismatch, "Expected \"A is not a module\" to include \"/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_module.rb:3185: previous definition\"."
exclude :test_undef, "pid 58017 exit 0."
exclude :test_classpath, "NameError: constant TestModule::M not defined"
exclude :test_constant_access_from_method_in_cloned_module, "NameError: uninitialized constant TestModule::CloneTestM0::TEST"
exclude :test_prepend_private_super, "SystemStackError: stack level too deep"
exclude :test_private_constant_const_missing, "NameError: private constant #<Class:0x2008>::FOO referenced"
exclude :test_protected_include_into_included_module, "NoMethodError: undefined method `other_foo' for #<#<Class:0x2238>:0x2268>"
