exclude :test_file_open_newline_option, "<\"a\\r\\n\" + \"b\\r\\n\"> expected but was <\"a\\n\" + \"b\\n\">."
exclude :test_file_share_delete, "NameError: uninitialized constant IO::SHARE_DELETE"
exclude :test_gets_para_extended_file, "mode = <{}>."
exclude :test_open_tempfile_path, "Expected \"/b/b/e/.tmp/test_open_tempfile_path20241021-21320-c87h2k\" to be nil."
exclude :test_realpath_encoding, "<\"/b/b/e/.tmp/rubytest-realpath20241021-21320-7sqyld/AΑАԱႠאⰀあ\"> expected but was <\"/b/b/e/.tmp/rubytest-realpath20241021-21320-7sqyld/A\\xCE\\x91\\xD0\\x90\\xD4\\xB1\\xE1\\x82\\xA0\\xD7\\x90\\xE2\\xB0\\x80\\xE3\\x81\\x82\">."
exclude :test_realpath_special_symlink, "Errno::ENOENT: No such file or directory - /dev/fd/7"
exclude :test_stat, "NoMethodError: undefined method `birthtime' for #<File::Stat:0x918>"
exclude :test_uninitialized, "[TypeError] exception expected, not #<NoMethodError: undefined method `[]' for nil:NilClass>."
