exclude :test_timeout, "flaky: timeout can be missed and test then spins in a loop"
exclude :test_queue, "test hangs"
exclude :test_enumerator_next, "test hangs"
exclude :test_cannot_convert_into_time_interval, "needs investigation"
exclude :test_custom_exception, "needs investigation"
exclude :test_handle_interrupt, "needs investigation"
exclude :test_rescue_exit, "needs investigation"
exclude :test_skip_rescue, "needs investigation"
