exclude :test_hash_redefinition, "needs investigation"
exclude :test_match_method, "needs investigation"
exclude :test_symbol_encoding, "needs investigation"
exclude :test_to_proc_binding, "needs investigation"
exclude :test_to_proc_iseq, "needs investigation"
exclude :test_ascii_incomat_inspect, "needs investigation"
exclude :test_symbol_gc_1, "needs investigation"
exclude :test_to_proc_for_hash_each, "needs investigation"
