exclude :test_casecmp2, "needs investigation"
exclude :test_hex, "needs investigation"
exclude :test_oct, "needs investigation"
exclude :test_split_awk, "needs investigation"
exclude :test_is_mbc_newline, "needs investigation"
exclude :test_succ, "needs investigation"
