exclude :test_array_subclass, "needs investigation"
exclude :test_delete_if, "needs investigation"
exclude :test_drop, "needs investigation"
exclude :test_flatten, "needs investigation"
exclude :test_join, "needs investigation"
exclude :test_join_recheck_array_length, "needs investigation"
exclude :test_join_recheck_elements_type, "needs investigation"
exclude :test_keep_if, "needs investigation"
exclude :test_max_uncomparable, "needs investigation"
exclude :test_min_uncomparable, "needs investigation"
exclude :test_misc_0, "needs investigation"
exclude :test_reject!, "needs investigation"
exclude :test_slice, "needs investigation"
exclude :test_slice!, "needs investigation"
exclude :test_slice_out_of_range, "needs investigation"
exclude :test_sort_uncomparable, "needs investigation"
exclude :test_uniq, "needs investigation"
exclude :test_freeze_inside_sort!, "needs investigation"
exclude :test_intersect_big_array, "needs investigation"
exclude :test_intersect?, "needs investigation"
exclude :test_combination_clear, "hangs"
exclude :test_product2, "Exception raised:"
exclude :test_shuffle_random, "[RuntimeError] exception expected, not #<RangeError: random number too big 0>."
exclude :test_sample_random, "<[]> expected but was"
exclude :test_select!, "[ruby-dev:48805] [Bug #10722]."
exclude :test_repeated_combination_stack_error, "Exception raised:"
exclude :test_ary_new, "ArgumentError expected but nothing was raised."
exclude :test_zip, "[TypeError] exception expected, not #<NoMethodError: undefined method `each' for #<Object:0x1112028>>."
exclude :test_sort_bang_with_freeze, "frozen during comparison."
exclude :test_times, "[ArgumentError] exception expected, not #<RangeError: new array size too large>."
exclude :test_aset_error, "IndexError expected but nothing was raised."
exclude :test_repeated_combination_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_combination_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_reject_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_repeated_permutation_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_permutation_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_flatten_recursive, "ArgumentError: tried to flatten recursive array"
exclude :test_product_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_sort_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_flatten_with_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_flatten_respond_to_missing, "ArgumentError: unknown event: raise"
exclude :test_insert, "TypeError expected but nothing was raised."
exclude :test_count, "expected: /given block not used/"
exclude :test_bsearch_typechecks_return_values, "Expected Exception(TypeError) was raised, but the message doesn't match."
exclude :test_reverse_each2, "<[5, 3, 1]> expected but was"
exclude :test_repeated_permutation_stack_error, "Exception raised:"
exclude :test_big_array_literal_with_kwsplat, "<10000> expected but was"
exclude :test_permutation_stack_error, "[ruby-core:63103] [Bug #9932]."
exclude :test_join2, "[ruby-core:24150]."
exclude :test_uniq_bang_with_freeze, "frozen during comparison."
exclude :test_union, "Failed assertion, no message given."
exclude :test_shuffle, "Exception(ArgumentError) with message matches to /unknown keyword/."
exclude :test_sort_with_replace, "[ruby-core:34732]."
exclude :test_OR, "Failed assertion, no message given."
exclude :test_initialize, "expected: /given block not used/"
exclude :test_to_ary, "Exception(NoMethodError) with message matches to /foo_bar/."
