exclude :test_count, "GR-15504: Expected 0 to be < 0."
exclude :test_exception_in_finalizer_method, "needs investigation"
exclude :test_exception_in_finalizer_procs, "transient"
exclude :test_finalizer_passed_object_id, "needs investigation"
exclude :test_finalizing_main_thread, "| -:1:in `define_finalizer': wrong number of arguments (given 1, expected 2) (ArgumentError)"
exclude :test_gc_disabled_start, "GR-15504: <1> expected but was <0>."
exclude :test_gc_internals, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_gc_parameter, "slow: 32.16s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_gc_parameter_init_slots, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_interrupt_in_finalizer, "spurious; TypeError: no implicit conversion of nil into Integer"
exclude :test_latest_gc_info, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_latest_gc_info_argument, "NoMethodError: undefined method `latest_gc_info' for GC:Module"
exclude :test_latest_gc_info_need_major_by, "NameError: uninitialized constant GC::OPTS"
exclude :test_latest_gc_info_weak_references_count, "NoMethodError: undefined method `latest_gc_info' for GC:Module"
exclude :test_measure_total_time, "<65> expected but was <154>."
exclude :test_old_to_young_reference, "Expected \"{\\\"address\\\":\\\"0x8538\\\",\\\"class\\\":\\\"0x8548\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\" to include \"\\\"old\\\":true\"."
exclude :test_profiler_raw_data, "NoMethodError: undefined method `raw_data' for GC::Profiler:Module"
exclude :test_start_full_mark, "NameError: uninitialized constant GC::OPTS"
exclude :test_start_immediate_sweep, "NoMethodError: undefined method `latest_gc_info' for GC:Module"
exclude :test_stat, "NoMethodError: undefined method `count_objects' for ObjectSpace:Module"
exclude :test_stat_argument, "Exception(ArgumentError) with message matches to /\\u{30eb 30d3 30fc}/."
exclude :test_stat_constraints, "Expected |1546 - 0| (1546) to be <= 1."
exclude :test_stat_heap, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_stat_heap_all, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_stat_heap_constraints, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_stat_single, "ArgumentError expected but nothing was raised."
exclude :test_thrashing_for_young_objects, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_verify_internal_consistency, "NoMethodError: undefined method `verify_internal_consistency' for GC:Module"
