exclude :test_bind, "Expected /bind\\(2\\)\\ for\\ 127\\.0\\.0\\.1:56331/ to match \"Address already in use - bind(2)\"."
exclude :test_closed_read, "retain-on-retag; test timed out"
exclude :test_getaddrinfo, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_getaddrinfo_raises_no_errors_on_port_argument_of_0, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_getnameinfo, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_resolurion_error_error_code, "NoMethodError: undefined method `error_code' for #<SocketError: ai_family not supported>"
exclude :test_socket_new_cloexec, "Failed assertion, no message given."
exclude :test_tcp_cloexec, "Failed assertion, no message given."
exclude :test_timestamp, "NoMethodError: undefined method `cmsg_is?' for nil:NilClass"
exclude :test_timestampns, "NoMethodError: undefined method `cmsg_is?' for nil:NilClass"
exclude :test_udp_server, "RuntimeError: thread killed"
exclude :test_unix, "Failed assertion, no message given."
