exclude :test_Integer, "[Encoding::CompatibilityError] exception expected, not #<ArgumentError: invalid value for Integer(): 0>."
exclude :test_Integer_when_to_str, "TypeError: can't convert Object into Integer"
exclude :test_Integer_with_exception_keyword, "RuntimeError: "
exclude :test_Integer_with_invalid_exception, "ArgumentError expected but nothing was raised."
exclude :test_bitwise_and_with_integer_coercion, "TypeError: #<Class:0x498> can't be coerced into Integer"
exclude :test_bitwise_or_with_integer_coercion, "TypeError: #<Class:0x4c8> can't be coerced into Integer"
exclude :test_bitwise_xor_with_integer_coercion, "TypeError: #<Class:0x4f8> can't be coerced into Integer"
exclude :test_ceil, "<11110> expected but was <11120>."
exclude :test_pow, "FloatDomainError: Infinity"
exclude :test_round, "<300> expected but was <200>."
exclude :test_square_root, "10**33."
exclude :test_times_bignum_redefine_plus_lt, "<false> expected but was <true>."
