exclude :test_branch_coverage_for_case_statement, "needs investigation"
exclude :test_branch_coverage_for_if_statement, "needs investigation"
exclude :test_branch_coverage_for_pattern_matching, "needs investigation"
exclude :test_branch_coverage_for_safe_method_invocation, "needs investigation"
exclude :test_branch_coverage_for_while_statement, "needs investigation"
exclude :test_branch_coverage_in_ensure_clause, "needs investigation"
exclude :test_clear_with_branches, "needs investigation"
exclude :test_clear_with_lines, "needs investigation"
exclude :test_clear_with_methods, "needs investigation"
exclude :test_clear_with_oneshot_lines, "needs investigation"
exclude :test_coverage_ensure_if_return, "needs investigation"
exclude :test_coverage_in_main_script, "| /b/b/e/main/test/mri/tests/coverage/main.rb:1:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)"
exclude :test_coverage_optimized_branch, "needs investigation"
exclude :test_coverage_state, "| -:1:in `<main>': undefined method `state' for Coverage:Module (NoMethodError)"
exclude :test_coverage_supported, "Failed assertion, no message given."
exclude :test_coverage_suspendable, "NoMethodError: undefined method `setup' for Coverage:Module"
exclude :test_double_resume, "| -:2:in `<main>': undefined method `resume' for Coverage:Module (NoMethodError)"
exclude :test_double_suspend, "| -:1:in `<main>': undefined method `setup' for Coverage:Module (NoMethodError)"
exclude :test_eval, "needs investigation"
exclude :test_eval_coverage, "| -:12:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)"
exclude :test_line_coverage_for_multiple_lines, "needs investigation"
exclude :test_line_stub, "NoMethodError: undefined method `line_stub' for Coverage:Module"
exclude :test_method_coverage, "needs investigation"
exclude :test_method_coverage_for_alias, "needs investigation"
exclude :test_method_coverage_for_define_method, "needs investigation"
exclude :test_method_coverage_for_singleton_class, "needs investigation"
exclude :test_oneshot_line_coverage, "needs investigation"
exclude :test_restarting_coverage, "needs investigation"
exclude :test_result_after_suspend, "| -:2:in `<main>': undefined method `suspend' for Coverage:Module (NoMethodError)"
exclude :test_result_without_resume, "| -:1:in `<main>': undefined method `setup' for Coverage:Module (NoMethodError)"
exclude :test_resume_without_setup, "| -:1:in `<main>': undefined method `resume' for Coverage:Module (NoMethodError)"
exclude :test_suspend_without_setup, "| -:1:in `<main>': undefined method `suspend' for Coverage:Module (NoMethodError)"
exclude :test_tag_break_with_branch_coverage, "needs investigation"
