exclude :test_encoding, "needs investigation"
exclude :"test_format_integer(% #+-00.d)", "needs investigation"
exclude :"test_format_integer(% #+-020d)", "needs investigation"
exclude :"test_format_integer(% #-00.d)", "needs investigation"
exclude :"test_format_integer(% #-020.d)", "needs investigation"
exclude :"test_format_integer(% #-020d)", "needs investigation"
exclude :"test_format_integer(% #0.d)", "needs investigation"
exclude :"test_format_integer(% +-0.0d)", "needs investigation"
exclude :"test_format_integer(% +-20.0d)", "needs investigation"
exclude :"test_format_integer(%#+0.d)", "needs investigation"
exclude :"test_format_integer(%#+05.d)", "needs investigation"
exclude :"test_format_integer(%+-05.0d)", "needs investigation"
exclude :"test_format_integer(%.0d)", "needs investigation"
exclude :"test_format_integer(%5.0d)", "needs investigation"
exclude :test_quote, "needs investigation"
exclude :test_snprintf_count, "needs investigation"
