exclude :test_pow, "needs investigation"
exclude :test_divmod, "needs investigation"
exclude :test_pack_utf8, "needs investigation"
exclude :test_printf_b, "needs investigation"
exclude :test_printf_o, "needs investigation"
exclude :test_remainder, "needs investigation"
exclude :test_rshift, "needs investigation"
exclude :test_lshift, "needs investigation"
