exclude :test_to_s, "needs investigation"
exclude :test_equals2, "needs investigation"
exclude :test_output_name, "needs investigation"
exclude :test_find_method_or_attribute_recursive, "needs investigation"
exclude :test_is_alias_for, "needs investigation"
exclude :test_search_record, "needs investigation"
exclude :test_full_name, "needs investigation"
exclude :test_initialize_copy, "needs investigation"
