exclude :test_eq_can_be_redefined, "needs investigation"
exclude :test_hash_redefinition, "needs investigation"
exclude :test_match_method, "needs investigation"
exclude :test_symbol_encoding, "needs investigation"
exclude :test_to_proc_binding, "needs investigation"
exclude :test_to_proc_iseq, "needs investigation"
exclude :test_ascii_incomat_inspect, "needs investigation"
exclude :test_to_proc_arg, "flaky: sometimes times out in CI"
exclude :test_to_proc_no_method, "flaky: sometimes times out in CI"