exclude :test_coerce, "needs investigation"
exclude :test_coerced_remainder, "needs investigation"
exclude :test_dummynumeric, "needs investigation"
exclude :test_dup, "needs investigation"
exclude :test_step, "needs investigation"
