exclude :test_all_modules, "needs investigation"
exclude :test_classes, "needs investigation"
exclude :test_all_classes_and_modules, "needs investigation"
exclude :test_complete, "needs investigation"
exclude :test_load_single_class, "needs investigation"
