exclude :test_eval_ascii_incompatible, "needs investigation"
exclude :test_eval_location_binding, "needs investigation"
exclude :test_eval_location_fstring, "needs investigation"
exclude :test_file_encoding, "needs investigation"
exclude :test_instance_eval_const, "needs investigation"
exclude :test_gced_eval_location, "needs investigation"
exclude :test_return_in_eval_lambda, "needs investigation"
