exclude :test_hup_me, "needs investigation"
exclude :test_invalid_signal_name, "needs investigation"
exclude :test_kill_immediately_before_termination, "needs investigation"
exclude :test_reserved_signal, "needs investigation"
exclude :test_sigexit, "needs investigation"
exclude :test_signal_exception, "needs investigation"
exclude :test_trap, "needs investigation"
exclude :test_trap_uncatchable_KILL, "needs investigation"
exclude :test_trap_uncatchable_STOP, "needs investigation"
exclude :test_exit_action, "needs investigation"
exclude :test_ignored_interrupt, "needs investigation"
exclude :test_sigchld_ignore, "needs investigation"
exclude :test_signal2, "needs investigation"
exclude :test_signame_delivered, "needs investigation"
exclude :test_sigwait_fd_unused, "needs investigation"
exclude :test_trap_system_default, "needs investigation"
exclude :test_trap_puts, "flaky: IllegalStateException: The context is currently executing on another thread. Set cancelIfExecuting to true to stop the execution on this thread."
