exclude :test_bind, "[IOError] exception expected, not #<NoMethodError: undefined method `empty?' for #<Object:0x728>>."
exclude :test_bind_addrinuse, "Expected /bind\\(2\\)\\ for\\ \"127\\.0\\.0\\.1\"\\ port\\ 47181/ to match \"Address already in use - bind(2)\"."
exclude :test_connect, "[IOError] exception expected, not #<NoMethodError: undefined method `empty?' for #<Object:0x798>>."
exclude :test_inspect, "Expected /AF_INET\\b/ to match \"#<UDPSocket:fd 42>\"."
exclude :test_send_too_long, "Expected /for\\ \"127\\.0\\.0\\.1\"\\ port\\ 7/ to match \"Message too long - send(2)\"."
