exclude :test_bound_parameters, "needs investigation"
exclude :test_compose_with_callable, "needs investigation"
exclude :test_compose_with_lambda, "needs investigation"
exclude :test_compose_with_method, "needs investigation"
exclude :test_curry_given_blocks, "needs investigation"
exclude :test_curry_passed_block, "needs investigation"
exclude :test_curry_proc, "needs investigation"
exclude :test_curry_proc_splat, "needs investigation"
exclude :test_curry_with_trace, "needs investigation"
exclude :test_orphan_return, "needs investigation"
exclude :test_parameters, "needs investigation"
exclude :test_proc_args_opt_post, "needs investigation"
exclude :test_proc_args_opt_post_block, "needs investigation"
exclude :test_proc_args_opt_rest, "needs investigation"
exclude :test_proc_args_opt_rest_post_block, "needs investigation"
exclude :test_proc_args_opt_single, "needs investigation"
exclude :test_proc_args_pos_opt_post, "needs investigation"
exclude :test_proc_args_pos_opt_post_block, "needs investigation"
exclude :test_proc_args_pos_opt_rest_post_block, "needs investigation"
exclude :test_proc_args_pos_rest_post, "needs investigation"
exclude :test_proc_args_pos_rest_post_block, "needs investigation"
exclude :test_proc_args_rest_kwsplat, "needs investigation"
exclude :test_proc_args_rest_post, "needs investigation"
exclude :test_proc_args_rest_post_block, "needs investigation"
exclude :test_proc_autosplat, "needs investigation"
exclude :test_to_s, "needs investigation"
exclude :test_binding, "needs investigation"
exclude :test_curry_lambda_splat, "needs investigation"
exclude :test_dup_clone, "needs investigation"
exclude :test_localjump_error, "needs investigation"
exclude :test_proc_args_single_kwsplat_no_autosplat, "<[[1], {}]> expected but was"
exclude :test_binding_error_unless_ruby_frame, "[RuntimeError] exception expected, not #<NoMethodError: undefined method `call' for #<TestProc:0x1a6158>>."
exclude :test_parameters_lambda, "ArgumentError: wrong number of arguments (given 1, expected 0)"
