exclude :test_load, "needs investigation"
exclude :test_race_exception, "needs investigation"
exclude :test_require_changed_home, "needs investigation"
exclude :test_require_invalid_shared_object, "needs investigation"
exclude :test_require_path_home_1, "needs investigation"
exclude :test_require_path_home_2, "needs investigation"
exclude :test_require_path_home_3, "needs investigation"
exclude :test_require_to_path_redefined_in_load_path, "needs investigation"
exclude :test_require_to_str_redefined_in_load_path, "needs investigation"
exclude :test_require_too_long_filename, "needs investigation"
exclude :test_throw_while_loading, "needs investigation"
exclude :test_load_ospath, "needs investigation"
exclude :test_loading_fifo_fd_leak, "needs investigation"
exclude :test_loading_fifo_threading_raise, "needs investigation"
exclude :test_loading_fifo_threading_success, "needs investigation"
exclude :test_require_nonascii_path, "needs investigation"
exclude :test_require_nonascii_path_shift_jis, "needs investigation"
exclude :test_relative_symlink_realpath, "bug17885 [ruby-core:104010]."
exclude :test_load_into_module, "<[:b]> expected but was"
exclude :test_resolve_feature_path_with_missing_feature, "LoadError: cannot load such file -- superkalifragilisticoespialidoso"
