exclude :test_ancestors, "<[#<refinement:Array@#<Module:0x7e8>>]> expected but was <[#<refinement:Array@#<Module:0x7e8>>,"
exclude :test_eval_with_binding_scoping, "needs investigation"
exclude :test_import_methods, "ArgumentError expected but nothing was raised."
exclude :test_inlinecache, "<:R> expected but was <\"\">."
exclude :test_prepend_after_refine, "<\"refined\"> expected but was <\"mixin\">."
exclude :test_refine_in_using, "NoMethodError: undefined method `foo' for #<TestRefinement::RefineInUsing:0xe88>"
exclude :test_refine_prepended_class, "<[:c, :m1, :m2]> expected but was <[:c, :m1]>."
exclude :test_refine_with_proc, "ArgumentError expected but nothing was raised."
exclude :test_refined_protected_methods, "NoMethodError: protected method `foo' called for #<C:0x2d8>"
exclude :test_refinements, "spurious; <[#<refinement:Integer@#<Module:0x297a668>>, #<refinement:String@#<Module:0x297a668>>]> expected but was <[#<refinement:String@#<Module:0x297a668>>, #<refinement:Integer@#<Module:0x297a668>>]>."
exclude :test_target, "NoMethodError: undefined method `target' for #<refinement:Integer@#<Module:0x1178>>"
exclude :test_unbound_refine_method, "TypeError expected but nothing was raised."
exclude :test_used_modules, "spurious; <[TestRefinement::VisibleRefinements::RefB, TestRefinement::VisibleRefinements::RefA]> expected but was <[TestRefinement::VisibleRefinements::RefA, TestRefinement::VisibleRefinements::RefB]>."
exclude :test_warn_setconst_in_refinmenet, "needs investigation"
