exclude :test_bind, "Expected /bind\\(2\\)\\ for\\ 127\\.0\\.0\\.1:58855/ to match \"Address already in use - bind(2)\"."
exclude :test_closed_read, "retain-on-retag; test timed out"
exclude :test_getnameinfo, "SocketError expected but nothing was raised."
exclude :test_socket_new_cloexec, "Failed assertion, no message given."
exclude :test_tcp_cloexec, "Failed assertion, no message given."
exclude :test_timestamp, "NoMethodError: undefined method `cmsg_is?' for nil:NilClass"
exclude :test_timestampns, "NoMethodError: undefined method `cmsg_is?' for nil:NilClass"
exclude :test_udp_server, "RuntimeError: thread killed"
exclude :test_unix, "Failed assertion, no message given."
