exclude :test_not_method_defined, "needs investigation"
exclude :test_respond_to, "needs investigation"
exclude :test_not_private_method_defined, "needs investigation"
exclude :test_not_protected_method_defined, "needs investigation"
exclude :test_method_inspect_notimplement, "needs investigation"
