exclude :test_argument_error_location, "<\"(eval):1:in `block in <main>'\"> expected but was <\"(eval):1:in `block (2 levels) in <unused>'\">."
exclude :test_arity_special, "<-1> expected but was <-2>."
exclude :test_body, "<#<NameError: uninitialized constant TestMethod::RubyVM>>"
exclude :test_callee, "Expected :\"<class:TestCallee>\" to be nil."
exclude :test_callee_top_level, "needs investigation"
exclude :test_caller_negative_level, "ArgumentError expected but nothing was raised."
exclude :test_clone, "TypeError: allocator undefined for Method"
exclude :test_curry_from_proc, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /wrong number/ to match \"Wrong number of arguments (2 for 3)\"."
exclude :test_curry_from_proc_var_args, "NoMethodError: undefined method `call' for [1]:Array"
exclude :test_curry_method, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /wrong number/ to match \"Wrong number of arguments (2 for 3)\"."
exclude :test_curry_var_args, "NoMethodError: undefined method `call' for [1]:Array"
exclude :test_define_method, "Expected Exception(TypeError) was raised, but the message doesn't match. Expected /X\\u{1F431}/ to match \"#<Class:0x2478> is not a symbol nor a string\"."
exclude :test_eq, "<#<Method: #<Object:0x25a8>.foo() /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:191>> expected to be != to"
exclude :test_inspect, "<\"#<Method: #<Class:0x2648>(#<Class:0x2638>)#foo() /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:462>\"> expected but was <\"#<Method: #<Class:0x2648>#foo() /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:462>\">."
exclude :test_instance_method, "Expected Exception(TypeError) was raised, but the message doesn't match. Expected /X\\u{1F431}/ to match \"no implicit conversion of Class into String\"."
exclude :test_method_list, "spurious; TypeError: no implicit conversion of Array into Integer"
exclude :test_method_parameters_inspect, "Expected \"#<Method: TestMethod#mo8(a, b=..., **, d, &e) /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:24>\" to include \"(a, b=..., *, d, &e)\"."
exclude :test_override_optimized_method_on_class_using_prepend, "NoMethodError: undefined method `unpack1' for nil:NilClass"
exclude :test_public_methods_with_extended, "spurious; <[:m1, :a]> expected but was <[:a, :m1]>."
exclude :test_receiver_name_owner, "NoMethodError: undefined method `original_name' for #<Method:0xc8b8>"
exclude :test_super_method_bind_unbind_clone, "TypeError: allocator undefined for Method"
exclude :test_super_method_module, "NoMethodError: undefined method `owner' for nil:NilClass"
exclude :test_super_method_removed_public, "Expected #<UnboundMethod: #<Class:0xcb88>#foo() /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:1060> to be nil."
exclude :test_unbound_method_parameters_inspect, "Expected \"#<UnboundMethod: TestMethod#mo8(a, b=..., **, d, &e) /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:24>\" to include \"(a, b=..., *, d, &e)\"."
exclude :test_visibility, "<nil> expected but was <\"method\">."
exclude :test_zsuper_method_redefined_bind_call, "<[:bar2]> expected but was <[:foo, :bar]>."
exclude :test_zsuper_method_removed, "<\"#<UnboundMethod: A#foo(arg=...) /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:1226>\"> expected but was <\"#<UnboundMethod: B#foo(arg=...) /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:1226>\">."
exclude :test_zsuper_method_removed_higher_method, "<\"#<UnboundMethod: A#foo(arg=...) /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:1268>\"> expected but was <\"#<UnboundMethod: B#foo(arg=...) /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_method.rb:1268>\">."
