exclude :test_ascii_incompatible, "Encoding::CompatibilityError expected but nothing was raised."
exclude :test_format_string_modified, "RuntimeError expected but nothing was raised."
exclude :test_invalid_warning, "expected: /unknown pack directive ',' in ','/"
exclude :test_length_too_big, "[RangeError] exception expected, not #<ArgumentError: too few arguments>."
exclude :test_pack_P, "<\"a\"> expected but was <\"abc\">."
exclude :test_pack_garbage, "expected: /unknown pack directive '\\*' in '\\*U'$/"
exclude :test_pack_p, "hangs; high CPU"
exclude :test_pack_resize, "Exception(ArgumentError) with message matches to /too few/."
exclude :test_pack_unpack_P2, "ArgumentError expected but nothing was raised."
exclude :test_pack_unpack_U, "ArgumentError expected but nothing was raised."
exclude :test_pack_unpack_u, "<no message> (java.lang.UnsupportedOperationException) from org.truffleruby.core.format.write.bytes.EncodeUM.encodes(EncodeUM.java:107)"
exclude :test_pack_with_buffer, "<\"@\\xEB\\xA9\\xB2\\\\V\\x00\\x00\"> expected but was <\"\\xB0LN\\xB3\\\\V\\x00\\x00\">."
exclude :test_short_with_block, "Expected [nil] to be nil."
exclude :test_unpack_garbage, "<no message> (com.oracle.truffle.api.CompilerDirectives.ShouldNotReachHere) from com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:603)"
exclude :test_unpack_with_block, "<[65, 66, 67, 68]> expected but was <[]>."
