exclude :test_coerce, "Expected Exception(TypeError) was raised, but the message doesn't match. Expected /:\\u{3042}/ to match \"Symbol can't be coerced into Integer\"."
exclude :test_coerced_remainder, "[ArgumentError] exception expected, not #<NoMethodError: undefined method `<' for #<#<Class:0x2b8>:0x2f8>>."
exclude :test_dummynumeric, "[ArgumentError] exception expected, not #<TypeError: coerce must return [x, y]>."
exclude :test_dup, "Expected #<Numeric:0x648> (oid=1608) to be the same as #<Numeric:0x658> (oid=1624)."
exclude :test_float_round_ndigits, "<0.5> expected but was <0.49999999999999994>."
exclude :test_floor_ceil_ndigits, "<291.4> expected but was <291.39>."
exclude :test_remainder_infinity, "<4> expected but was <NaN>."
exclude :test_step, "ArgumentError expected but nothing was raised."
