exclude :test_AREF_fstring_key, "NoMethodError: undefined method `count_objects' for ObjectSpace:Module"
exclude :test_ASET_fstring_key, "Expected \"abc\" (oid=51000) to be the same as \"abc\" (oid=51016)."
exclude :test_ASET_fstring_non_literal_key, "Expected \"abc_def\" (oid=51048) to be the same as \"abc_def\" (oid=51064)."
exclude :test_NEWHASH_fstring_key, "Expected \"ABC\" (oid=51096) to be the same as \"ABC\" (oid=80)."
exclude :test_any_hash_fixable, "very slow: 85.93s on truffleruby 24.2.0-dev-910e8f06, like ruby 3.3.5, Interpreted JVM [x86_64-darwin23] with Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz: ( 16 vCPUs)"
exclude :test_ar2st_delete, "<no message> (java.lang.AssertionError) from org.truffleruby.core.hash.library.BucketsHashStore.verify(BucketsHashStore.java:518)"
exclude :test_ar2st_insert, "<no message> (java.lang.AssertionError) from org.truffleruby.core.hash.library.PackedHashStoreLibrary.verify(PackedHashStoreLibrary.java:396)"
exclude :test_ar2st_lookup, "class org.truffleruby.core.hash.library.BucketsHashStore cannot be cast to class [Ljava.lang.Object; (org.truffleruby.core.hash.library.BucketsHashStore is in module org.graalvm.ruby of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap') (java.lang.ClassCastException) from org.truffleruby.core.hash.library.PackedHashStoreLibrary$LookupPackedEntryNode.getPackedArray(PackedHashStoreLibrary.java:481)"
exclude :test_compare_by_identity_during_iteration, "compare_by_identity during iteration."
exclude :test_float_hash_random, "slow: 37.42s on truffleruby 24.2.0-dev-910e8f06, like ruby 3.3.5, Interpreted JVM [x86_64-darwin23] with Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz: ( 16 vCPUs)"
exclude :test_integer_hash_random, "slow: 37.20s on truffleruby 24.2.0-dev-910e8f06, like ruby 3.3.5, Interpreted JVM [x86_64-darwin23] with Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz: ( 16 vCPUs)"
exclude :test_select_reject_will_not_rehash, "<1> expected but was <2>."
