exclude :test_info_const_name, "Expected Exception(NameError) was raised, but the message doesn't match. Expected /ModuleName/ to match \"uninitialized constant #<Module:0x3d8>::DOES_NOT_EXIST\"."
exclude :test_info_local_variables, "NoMethodError: private method `local_variables' called for #<NameError:0x438>"
exclude :test_info_method, "NoMethodError: undefined method `private_call?' for #<NoMethodError:0x458>"
exclude :test_info_method_missing, "NoMethodError: undefined method `private_call?' for #<NoMethodError:0x488>"
exclude :test_info_parent_iseq_mark, "NoMethodError: private method `local_variables' called for #<NameError:0x2c8>"
exclude :test_large_receiver_inspect, "Expected /\\Auninitialized constant AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA::FOO$/ to match \"uninitialized constant #<Class:0x548>::FOO\"."
