exclude :test_binding, "NoMethodError: undefined method `foo=' for #<Binding:0x408>"
exclude :test_binding_error_unless_ruby_frame, "[RuntimeError] exception expected, not #<NoMethodError: undefined method `call' for #<TestProc:0x418>>."
exclude :test_bound_parameters, "<[[:rest]]> expected but was <[[:req, :pattern], [:opt, :replacement], [:block, :block]]>."
exclude :test_compose_with_callable, "Expected #<Proc:0xd48 <internal:core> core/proc.rb:126> to be lambda?."
exclude :test_compose_with_lambda, "Expected #<Proc:0xd68 <internal:core> core/proc.rb:126> to be lambda?."
exclude :test_compose_with_method, "Expected #<Proc:0xd98 <internal:core> core/proc.rb:126> to be lambda?."
exclude :test_curry_given_blocks, "expected: /given block not used/"
exclude :test_curry_lambda_splat, "ArgumentError: wrong number of arguments (given 1, expected 3+)"
exclude :test_curry_passed_block, "<nil> expected to not be nil."
exclude :test_curry_proc, "<6> expected but was <0>."
exclude :test_curry_proc_splat, "<6> expected but was <0>."
exclude :test_curry_with_trace, "<nil> expected to not be nil."
exclude :test_dup_clone, "NoMethodError: undefined method `foo=' for #<Proc:0xfb8>"
exclude :test_localjump_error, "NoMethodError: undefined method `exit_value' for #<LocalJumpError: no block given (yield)>"
exclude :test_orphan_return, "LocalJumpError expected but nothing was raised."
exclude :test_parameters, "<[[:opt, nil], [:block, :b]]> expected but was <[[:req], [:block, :b]]>."
exclude :test_proc_args_opt_rest, "<[:a, :b, :c, []]> expected but was <[[], :b, :c, []]>."
exclude :test_proc_autosplat, "<[[1, 2], [[1, 2, 3], 0], [[1, 2, 3], {}]]> expected but was <[[1, 2], [1, 2], [[1, 2, 3], {}]]>."
exclude :test_proc_autosplat_with_multiple_args_with_ruby2_keywords_splat_bug_19759, "<[[:a, :b], nil]> expected but was <[:a, :b]>."
exclude :test_to_s, "Expected /^#<Proc:0x\\h+ \\(lambda\\)>$/ to match \"#<Proc:0x5bd8 <internal:core> core/post.rb:78 (lambda)>\"."
