exclude :test_Float_to_d_with_precision, "needs investigation"
exclude :test_Float_to_d_without_precision, "needs investigation"
exclude :test_Integer_to_d, "needs investigation"
exclude :test_Rational_to_d, "needs investigation"
exclude :test_String_to_d, "needs investigation"
