exclude :test_callcc, "Expected Exception(RuntimeError) was raised, but the message doesn't match. Expected /reentered/ to match \"Continuations are unsupported on TruffleRuby\"."
exclude :test_cycle, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_detect, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_drop_while, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_each_entry, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_find, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_find_all, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_first, "| "
exclude :test_grep, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_grep_optimization, "TypeError: can't define singleton"
exclude :test_grep_v, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_group_by, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_inject_op_private, "needs investigation"
exclude :test_max_by, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_min_by, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_minmax_by, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_partition, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_reject, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_select, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_sort_by, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_take_while, "ArgumentError: wrong number of arguments (given 1, expected 2)"
exclude :test_zip, "ArgumentError: wrong number of arguments (given 1, expected 2)"
