exclude :test_close_read, "Exception raised: <#<IOError: not opened for reading>>"
exclude :test_close_write, "Exception raised: <#<IOError: not opened for writing>>"
exclude :test_each, "<[\"foo\\n\" + \"bar\\n\" + \"\\n\" + \"\\n\", \"baz\\n\"]> expected but was <[\"foo\\n\" + \"bar\\n\" + \"\\n\", \"baz\\n\"]>."
exclude :test_encoding_read, "Encoding::CompatibilityError: incompatible character encodings: UTF-32BE and UTF-8"
exclude :test_encoding_write, "Encoding::CompatibilityError: incompatible character encodings: UTF-32BE and UTF-8"
exclude :test_frozen, "FrozenError expected but nothing was raised."
exclude :test_frozen_string, "IOError expected but nothing was raised."
exclude :test_gets2, "Encoding::CompatibilityError: incompatible character encodings: UTF-16BE and UTF-8"
exclude :test_gets_chomp, "<\"abc\\n\" + \"\\n\" + \"def\\n\"> expected but was <\"abc\\n\" + \"\\n\" + \"def\">."
exclude :test_gets_chomp_eol, "<\"abc\\r\\n\" + \"\\r\\n\" + \"def\\r\\n\"> expected but was <\"abc\\r\\n\" + \"\\r\\n\" + \"def\">."
exclude :test_gets_utf_16, "Encoding::CompatibilityError: incompatible character encodings: UTF-16LE and UTF-8"
exclude :test_initialize, "ArgumentError expected but nothing was raised."
exclude :test_overflow, "it hangs up on darwin"
exclude :test_pread, "NoMethodError: undefined method `pread' for #<StringIO:0x948>"
exclude :test_read, "Expected \"あい\" (oid=2392) to be the same as \"あい\" (oid=2408)."
exclude :test_set_encoding, "<\"foo\\x83\"> (ASCII-8BIT) expected but was <\"foo\\x83\"> (UTF-8)."
exclude :"test_strip_bom:UTF-16BE", "UTF-16BE."
exclude :"test_strip_bom:UTF-16LE", "UTF-16LE."
exclude :"test_strip_bom:UTF-32BE", "UTF-32BE."
exclude :"test_strip_bom:UTF-32LE", "UTF-32LE."
exclude :"test_strip_bom:UTF-8", "UTF-8."
exclude :test_truncate, "<0> expected but was <10>."
exclude :test_ungetbyte, "<\"q紅玉bar\\n\"> expected but was <\"foo\\n\" + \"bar\\n\">."
exclude :test_ungetbyte_padding, "<\"\\u0000a\"> expected but was <\"a\">."
exclude :test_ungetc, "<\"x\"> expected but was <\"1\">."
exclude :test_ungetc_fill, "<500> expected but was <599>."
exclude :test_ungetc_padding, "<\"b\\u0000a\"> expected but was <\"\\u0000a\">."
exclude :test_write_encoding_conversion, "ArgumentError: wrong number of arguments (given 2, expected 1)"
exclude :test_write_with_multiple_arguments, "ArgumentError: wrong number of arguments (given 2, expected 1)"
