exclude :test_abort, "needs investigation"
exclude :test_argv0, "slow: 30.26s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_argv0_frozen, "Expected \"test/mri/tests/runner.rb: TestProcess#test_argv0_frozen\" to be frozen?."
exclude :test_argv0_noarg, "slow: 49.46s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_aspawn_too_long_path, "[Errno::ENOENT, Errno::E2BIG] exception expected, not #<ArgumentError: unknown exec option: :rlimit_nproc>."
exclude :test_clock_getres, "Expected Exception(Errno::EINVAL) was raised, but the message doesn't match. Expected /:foo/ to match \"Invalid argument\"."
exclude :test_clock_gettime, "Expected Exception(Errno::EINVAL) was raised, but the message doesn't match. Expected /:foo/ to match \"Invalid argument\"."
exclude :test_deadlock_by_signal_at_forking, "NotImplementedError: fork is not available"
exclude :test_exec_fd_3_redirect, "NotImplementedError: fork is not available"
exclude :test_execopts_chdir, "Exception(Errno::ENOENT) with message matches to /d\\/notexist/."
exclude :test_execopts_close_others, "slow: 39.27s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_execopts_duplex_io, "ArgumentError expected but nothing was raised."
exclude :test_execopts_env_popen_string, "slow: 51.42s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_execopts_env_popen_vector, "slow: 50.25s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_execopts_gid, "Exception raised: <#<ArgumentError: unknown exec option: :gid>>"
exclude :test_execopts_pgroup, "Errno::EPERM expected but nothing was raised."
exclude :test_execopts_popen, "Errno::ENOENT expected but nothing was raised."
exclude :test_execopts_popen_stdio, "ArgumentError expected but nothing was raised."
exclude :test_execopts_redirect_dup2_child, "<\"errout\"> expected but was <\"\">."
exclude :test_execopts_redirect_fd, "ArgumentError expected but nothing was raised."
exclude :test_execopts_redirect_open_fifo, "hangs"
exclude :test_execopts_redirect_open_fifo_interrupt_print, "hangs"
exclude :test_execopts_redirect_open_fifo_interrupt_raise, "hangs"
exclude :test_execopts_redirect_open_order_reverse, "<\"7\"> expected but was <\"\">."
exclude :test_execopts_redirect_pipe, "hangs"
exclude :test_execopts_redirect_self, "hangs"
exclude :test_execopts_rlimit, "ArgumentError: unknown exec option: :rlimit_core"
exclude :test_execopts_uid, "Exception raised: <#<ArgumentError: unknown exec option: :uid>>"
exclude :test_execopts_umask, "RuntimeError: Unknown spawn option: umask"
exclude :test_fallback_to_sh, "<[16323, true]> expected but was <[16323, false]>."
exclude :test_fd_inheritance, "slow: 31.22s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_initgroups, "[ArgumentError] exception expected, not #<NoMethodError: undefined method `initgroups' for Truffle::POSIX:Module>."
exclude :test_maxgroups, "[ArgumentError] exception expected, not #<Errno::EPERM: Operation not permitted>."
exclude :test_no_curdir, "needs investigation"
exclude :test_overwrite_ENV, "assert_separately failed with error message"
exclude :test_process_detach, "NotImplementedError: fork is not available"
exclude :test_rlimit_value, "[ArgumentError] exception expected, not #<TypeError: wrong argument type Symbol (expected Integer)>."
exclude :test_sh_exec, "Errno::ENOENT: No such file or directory - No such file or directory - exec"
exclude :test_signals_work_after_exec_fail, "NotImplementedError: fork is not available"
exclude :test_sleep, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /not.*negative/ to match \"time interval must be positive\"."
exclude :test_spawn_too_long_path, "[Errno::ENOENT, Errno::E2BIG] exception expected, not #<ArgumentError: unknown exec option: :rlimit_nproc>."
exclude :test_status, "expected: /\\buse .*Process::Status/"
exclude :test_status_quit, "ArgumentError: unknown exec option: :rlimit_core"
exclude :test_threading_works_after_exec_fail, "NotImplementedError: fork is not available"
exclude :test_to_hash_on_arguments, "needs investigation"
exclude :test_warmup_frees_pages, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_warmup_precompute_string_coderange, "Expected \"{\\\"address\\\":\\\"0x2b8\\\",\\\"class\\\":\\\"0x2c8\\\",\\\"memsize\\\":13,\\\"flags\\\":{},\\\"type\\\":\\\"STRING\\\",\\\"bytesize\\\":12,\\\"value\\\":\\\"aaaaaaaaaaaa\\\",\\\"encoding\\\":\\\"ASCII-8BIT\\\"}\" to include \"\\\"coderange\\\":\\\"unknown\\\"\"."
exclude :test_warmup_promote_all_objects_to_oldgen, "Expected \"{\\\"address\\\":\\\"0x2b8\\\",\\\"class\\\":\\\"0x2c8\\\",\\\"memsize\\\":1,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":0}\" to include \"\\\"old\\\":true\"."
exclude :test_warmup_run_major_gc_and_compact, "<3> expected but was <2>."
