exclude :test_capacity_embedded, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_capacity_frozen, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_capacity_fstring, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_capacity_normal, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_capacity_shared, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_io_read, "<1048576> expected but was <2058>."
exclude :test_literal_capacity, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_s_new_capacity, "<10000> expected but was <0>."
