exclude :test_each_slice_size, "needs investigation"
exclude :test_chain_each_lambda, "needs investigation"
exclude :test_each_arg, "needs investigation"
exclude :test_generator, "needs investigation"
exclude :test_initialize_copy, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_peek_modify, "needs investigation"
exclude :test_peek_values_modify, "needs investigation"
exclude :test_size, "needs investigation"
exclude :test_size_for_cycle, "needs investigation"
exclude :test_size_for_downup_to, "needs investigation"
exclude :test_uniq, "needs investigation"
exclude :test_initialize, "needs investigation"
exclude :test_lazy_chain, "hangs"
