exclude :test_abstract_namespace, "needs investigation"
exclude :test_abstract_unix_server_socket, "needs investigation"
exclude :test_abstract_unix_socket_econnrefused, "needs investigation"
exclude :test_accept_nonblock, "needs investigation"
exclude :test_autobind, "needs investigation"
exclude :test_cloexec, "needs investigation"
exclude :test_getcred_ucred, "needs investigation"
exclude :test_getcred_xucred, "fails on Darwin in CI"
exclude :test_socket_pair_with_block, "needs investigation"
exclude :test_abstract_unix_server, "needs investigation"
exclude :test_dgram_pair, "needs investigation"
exclude :test_fd_passing, "needs investigation"
exclude :test_fd_passing_race_condition, "needs investigation"
exclude :test_sendcred_ucred, "needs investigation"
exclude :test_unix_server_socket, "needs investigation"
exclude :test_unix_socket_pair_with_block, "needs investigation"
