exclude :test_pause, "Failed to run script with JIT:"
exclude :test_pause_wait_false, "Failed to run script with JIT:"
exclude :test_pause_does_not_hang_on_full_units, "Failed to run script with JIT:"
exclude :test_pause_waits_until_compaction, "Failed to run script with JIT:"
exclude :test_resume, "Failed to run script with JIT:"
