exclude :test_deconstruct_cache, "TypeError: deconstruct must return Array"
exclude :test_invalid_syntax, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_pattern_matching.rb:1269:in `test_invalid_syntax'."
exclude :test_single_pattern_error_alternative_pattern, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"0: 2 === 0 does not return true\"> expected but was <\"0\">."
exclude :test_single_pattern_error_array_pattern, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"[]: Hash === [] does not return true\"> expected but was <\"[]\">."
exclude :test_single_pattern_error_as_pattern, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"[0]: 1 === 0 does not return true\"> expected but was <\"[0]\">."
exclude :test_single_pattern_error_find_pattern, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"[]: Hash === [] does not return true\"> expected but was <\"[]\">."
exclude :test_single_pattern_error_guard_clause, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"0: guard clause does not return true\"> expected but was <\"0\">."
exclude :test_single_pattern_error_hash_pattern, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"{}: Array === {} does not return true\"> expected but was <\"{}\">."
exclude :test_single_pattern_error_value_pattern, "Expected Exception(NoMatchingPatternError) was raised, but the message doesn't match. <\"0: 1 === 0 does not return true\"> expected but was <\"0\">."
