exclude :test_beg_len, "TypeError: no implicit conversion of Object into Integer"
exclude :test_comparison_when_recursive, "<no message> (java.lang.IndexOutOfBoundsException) from com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java:-1)"
exclude :test_count, "<6> expected but was <5>."
exclude :test_cover, "Expected 1..5 to not be cover? 3..2."
exclude :test_cyclic_range_inspect, "<no message> (java.lang.IndexOutOfBoundsException) from com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java:-1)"
exclude :test_duckrange, "TypeError: no implicit conversion of TestRange::DuckRange into Integer"
exclude :test_each, "NoMethodError: undefined method `<' for nil:NilClass"
exclude :test_each_with_succ, "NoMethodError: undefined method `i' for nil:NilClass"
exclude :test_eqq, "Expected 0..10 to not be === 0..10."
exclude :test_frozen_initialize, "FrozenError expected but nothing was raised."
exclude :test_include, "hangs"
exclude :test_initialize_twice, "[FrozenError] exception expected, not #<NameError: `initialize' called twice>."
exclude :test_last_with_redefine_each, "needs investigation"
exclude :test_max, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_min, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_overlap?, "NoMethodError: undefined method `overlap?' for 0..2:Range"
exclude :test_range_bsearch_for_floats, "needs investigation"
exclude :test_range_numeric_string, "<[\"9\", \"10\"]> expected but was <[]>."
exclude :test_reverse_each_for_beginless_range, "TypeError: can't iterate from NilClass"
exclude :test_reverse_each_for_empty_range, "RangeError: long too big to convert into `int'"
exclude :test_reverse_each_for_endless_range, "[TypeError] exception expected, not #<RangeError: cannot convert endless range to an array>."
exclude :test_size, "<3> expected but was <(31/10)>."
exclude :test_step, "ArgumentError expected but nothing was raised."
exclude :test_step_with_succ, "NoMethodError: undefined method `i' for nil:NilClass"
