exclude :test_gets, "needs investigation"
exclude :test_gets2, "needs investigation"
exclude :test_open, "needs investigation"
exclude :test_readline, "needs investigation"
exclude :test_ungetc_paragraph, "needs investigation"
