exclude :test_ast_compacts, "needs investigation"
exclude :test_compact_count, "needs investigation"
exclude :test_complex_hash_keys, "needs investigation"
exclude :test_gc_compact_stats, "needs investigation"
exclude :test_moving_strings_up_size_pools, "NameError: uninitialized constant GC::OPTS"
exclude :test_updating_references_for_heap_allocated_frozen_shared_arrays, "NameError: uninitialized constant GC::OPTS"
exclude :test_updating_references_for_embed_frozen_shared_arrays, "NameError: uninitialized constant GC::OPTS"
exclude :test_moving_arrays_down_size_pools, "NameError: uninitialized constant GC::OPTS"
exclude :test_compacting_from_trace_point, "NameError: uninitialized constant GC::OPTS"
exclude :test_updating_references_for_embed_shared_arrays, "NameError: uninitialized constant GC::OPTS"
exclude :test_moving_arrays_up_size_pools, "NameError: uninitialized constant GC::OPTS"
exclude :test_moving_objects_between_size_pools_keeps_shape_frozen_status, "NameError: uninitialized constant GC::OPTS"
exclude :test_moving_strings_down_size_pools, "NameError: uninitialized constant GC::OPTS"
exclude :test_updating_references_for_heap_allocated_shared_arrays, "NameError: uninitialized constant GC::OPTS"
exclude :test_moving_objects_between_size_pools, "NameError: uninitialized constant GC::OPTS"
