exclude :test_encoding, "<\"<あいうえお>\"> expected but was <\"<\\xE3\\x81\\x82\\xE3\\x81\\x84\\xE3\\x81\\x86\\xE3\\x81\\x88\\xE3\\x81\\x8A>\">."
exclude :"test_format_integer(% #-020.d)", "transient(depends on libc and fails on CI): rb_sprintf(\"% #-020.d\", 2147483647)."
exclude :"test_format_integer(%#+05.d)", "transient(depends on libc and fails on CI): rb_sprintf(\"%#+05.d\", 3)."
exclude :test_quote, "<\"[\\\\n]\"> expected but was <\"[\\n\" + \"]\">."
exclude :test_snprintf_count, "undefined symbol: ruby_snprintf"
