exclude :test_capacity_embedded, "needs investigation"
exclude :test_capacity_frozen, "needs investigation"
exclude :test_capacity_fstring, "needs investigation"
exclude :test_capacity_normal, "needs investigation"
exclude :test_capacity_shared, "needs investigation"
exclude :test_io_read, "needs investigation"
exclude :test_literal_capacity, "needs investigation"
exclude :test_s_new_capacity, "needs investigation"
