exclude :test_any_hash_fixable, "very slow: 178.88s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_callcc_escape, "Exception raised: <#<RuntimeError: Continuations are unsupported on TruffleRuby>>"
exclude :test_callcc_iter_level, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_callcc_reenter, "Exception raised: <#<RuntimeError: Continuations are unsupported on TruffleRuby>>"
exclude :test_create, "ArgumentError expected but nothing was raised."
exclude :test_fetch_error, "Expected /\\.\\.\\.\\z/ to match \"key not found: \\\"gumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumby\\\"\"."
exclude :test_float_hash_random, "very slow: 70.52s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_huge_iter_level, "spurious; RuntimeError expected but nothing was raised."
exclude :test_integer_hash_random, "very slow: 69.57s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_inverse_hash, "<3973466990156122966> expected to be != to"
exclude :test_merge!, "FrozenError expected but nothing was raised."
exclude :test_recursive_hash_value_struct, "<no message> (java.lang.IndexOutOfBoundsException) from com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java:-1)"
exclude :test_rehash2, "RuntimeError expected but nothing was raised."
exclude :test_reject, "Expected 42 to be nil."
exclude :test_reject_on_identhash, "<{}> expected but was <{\"str\"=>1, \"str\"=>2}>."
exclude :test_s_AREF_from_pairs, "ArgumentError expected but nothing was raised."
exclude :test_select_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was <{\"str\"=>2}>."
exclude :test_slice_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was <{\"str\"=>2}>."
exclude :test_symbol_hash_random, "slow: 43.82s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_to_proc, "Expected #<Proc:0x1ec8 <internal:core> core/hash.rb:522> to be lambda?."
exclude :test_transform_keys_bang, "<{false=>1, :b=>2, :c=>3}> expected but was <{false=>1}>."
exclude :test_transform_values_on_identhash, "<{1=>2, 3=>4, 5=>6, \"str\"=>1, \"str\"=>2}> expected but was <{1=>2, 3=>4, 5=>6, \"str\"=>2}>."
exclude :test_update5, "FrozenError expected but nothing was raised."
