exclude :test_tracer_by_add_filter_with_block, "needs investigation"
exclude :test_tracer_by_add_filter_with_proc, "needs investigation"
exclude :test_tracer_by_set_get_line_procs_with_block, "needs investigation"
exclude :test_tracer_by_set_get_line_procs_with_proc, "needs investigation"
exclude :test_tracer_with_option_r, "needs investigation"
exclude :test_tracer_with_option_r_without_gems, "needs investigation"
