exclude :test_anonymous_message, "needs investigation"
exclude :test_cause_at_end, "needs investigation"
exclude :test_cause_raised_in_rescue, "needs investigation"
exclude :test_circular_cause, "needs investigation"
exclude :test_circular_cause_handle, "needs investigation"
exclude :test_control_in_message, "needs investigation"
exclude :test_errat, "needs investigation"
exclude :test_errinfo_encoding_in_debug, "needs investigation"
exclude :test_errinfo_in_debug, "needs investigation"
exclude :test_frozen_error_message, "needs investigation"
exclude :test_frozen_error_receiver, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_kernel_warn_uplevel, "needs investigation"
exclude :test_machine_stackoverflow, "needs investigation"
exclude :test_machine_stackoverflow_by_define_method, "needs investigation"
exclude :test_name_error_info_const, "needs investigation"
exclude :test_name_error_info_parent_iseq_mark, "needs investigation"
exclude :test_non_exception_cause, "needs investigation"
exclude :test_output_string_encoding, "needs investigation"
exclude :test_too_many_args_in_eval, "needs investigation"
exclude :test_undefined_backtrace, "needs investigation"
exclude :test_warning_category, "needs investigation"
exclude :test_warning_warn_circular_require_backtrace, "needs investigation"
exclude :test_wrong_backtrace, "needs investigation"
exclude :test_cause_thread_with_cause, "needs investigation"
exclude :test_name_error_info_local_variables, "needs investigation"
exclude :test_name_error_info_method, "needs investigation"
exclude :test_name_error_info_method_missing, "needs investigation"
exclude :test_nomethod_error_new_name_args_priv, "needs investigation"
exclude :test_nomethod_error_new_receiver, "needs investigation"
exclude :test_blocking_backtrace, "needs investigation"
exclude :test_exception_in_message, "needs investigation"
exclude :test_full_message, "needs investigation"
exclude :test_warn_deprecated_backwards_compatibility_category, "needs investigation"
exclude :test_warn_deprecated_to_remove_category, "needs investigation"
exclude :test_warning_warn, "needs investigation"
exclude :test_warning_warn_super, "needs investigation"
exclude :test_warn_deprecated_category, "needs investigation"
exclude :test_warning_category_deprecated, "needs investigation"
exclude :test_warning_category_experimental, "needs investigation"
exclude :test_undef_Warning_warn, "[NoMethodError] exception expected, not #<NameError: undefined method `warn' for class `Module'>."
exclude :test_exception_in_ensure_with_next, "NameError: uninitialized constant TestException::RubyVM"
exclude :test_stackoverflow, "[ruby-core:43794] [Feature #6216]."
exclude :test_marshal_circular_cause, "\"\\x04\\bo:\\x11RuntimeError\\b:\\tmesgI\\\"\\berr\\x06:\\x06ET:\\abt[\\x00:\\ncauseo:\\x0EException\\a;\\x060;\\b0\"."
exclude :test_raise_with_cause, "[TypeError] exception expected, not #<RuntimeError: [Feature #8257]>."
exclude :test_full_message_with_custom_detailed_message, "Expected /BOO!/ to match \"/home/eregon/code/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_exception.rb:1469:in `test_full_message_with_custom_detailed_message': \\e[1mmessage (\\e[1;4mRuntimeError\\e[m\\e[1m)\\e[m\\n\"."
exclude :test_syntax_error_path, "NoMethodError: undefined method `path' for #<SyntaxError:0x6282d8>"
exclude :test_detailed_message, "NoMethodError: undefined method `detailed_message' for #<RuntimeError: message>"
