exclude :test_encoding_is_upgraded_during_writing_as_needed, "needs investigation"
exclude :test_encoding_is_upgraded_for_ascii_content_during_writing_as_needed, "needs investigation"
exclude :test_explicit_encoding, "needs investigation"
exclude :test_row_separator_detection_with_invalid_encoding, "needs investigation"
exclude :test_foreach_allows_you_to_set_encodings, "needs investigation"
exclude :test_open_allows_you_to_set_encodings, "needs investigation"
exclude :test_read_allows_you_to_set_encodings, "needs investigation"
exclude :test_read_with_default_encoding, "needs investigation"
