exclude :test_funcall_extra_args, "needs investigation"
exclude :test_with_funcall_passing_block, "needs investigation"
exclude :test_with_funcall_passing_block_kw, "needs investigation"
exclude :test_with_funcallv_public_kw, "needs investigation"
exclude :test_with_yield_splat_kw, "needs investigation"
