exclude :test_strftime_too_wide, "needs investigation"
exclude :test_asctime, "needs investigation"
exclude :test_at, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_marshal_nsec_191, "needs investigation"
exclude :test_marshal_timezone, "needs investigation"
exclude :test_marshal_to_s, "needs investigation"
exclude :test_plus_type, "needs investigation"
exclude :test_reinitialize, "needs investigation"
exclude :test_strftime_flags, "needs investigation"
exclude :test_strftime_rational, "needs investigation"
exclude :test_strftime_wide_precision, "needs investigation"
exclude :test_2038, "needs investigation"
exclude :test_future, "needs investigation"
exclude :test_getlocal_utc, "ArgumentError: \"+HH:MM\" or \"-HH:MM\" expected for utc_offset"
exclude :test_marshal_distant_future, "needs investigation"
exclude :test_marshal_distant_past, "needs investigation"
exclude :test_past, "needs investigation"
exclude :test_strftime_seconds_from_epoch, "needs investigation"
exclude :test_strftime_year, "needs investigation"
exclude :test_utc_or_local, "needs investigation"
exclude :test_memsize, "needs investigation"
exclude :test_strftime, "needs investigation"
exclude :test_getlocal_utc, "needs investigation"
exclude :test_marshal_broken_month, "ArgumentError: argument out of range"
exclude :test_strfimte_zoneoffset, "<\"-0000\"> expected but was"
exclude :test_new, "Exception(ArgumentError) with message matches to /invalid value for Integer/."
exclude :test_getlocal_utc_offset, "ArgumentError: \"+HH:MM\" or \"-HH:MM\" expected for utc_offset"
