exclude :test_errinfo_after_autoload, "needs investigation"
exclude :test_nonascii_library_path, "needs investigation"
exclude :test_replicate, "needs investigation"
exclude :test_singleton, "needs investigation"
exclude :test_extra_encoding, "needs investigation"
exclude :test_exceed_encoding_table_size, "Failed assertion, no message given."
