exclude :test___dir__, "needs investigation"
exclude :test_alias_owner, "needs investigation"
exclude :test_arity_special, "needs investigation"
exclude :test_bmethod_bound_parameters, "needs investigation"
exclude :test_bmethod_unbound_parameters, "needs investigation"
exclude :test_body, "needs investigation"
exclude :test_bound_parameters, "needs investigation"
exclude :test_callee, "needs investigation"
exclude :test_callee_top_level, "needs investigation"
exclude :test_caller_negative_level, "needs investigation"
exclude :test_curry_from_proc, "needs investigation"
exclude :test_curry_method, "needs investigation"
exclude :test_define_method, "needs investigation"
exclude :test_eq, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_instance_method, "needs investigation"
exclude :test_method_parameters_inspect, "needs investigation"
exclude :test_super_method_removed, "needs investigation"
exclude :test_unbound_method_parameters_inspect, "needs investigation"
exclude :test_unbound_parameters, "needs investigation"
exclude :test_visibility, "needs investigation"
exclude :test_argument_error_location, "needs investigation"
exclude :test_clone, "needs investigation"
exclude :test_curry_from_proc_var_args, "needs investigation"
exclude :test_curry_var_args, "needs investigation"
exclude :test_receiver_name_owner, "needs investigation"
exclude :test_super_method_bind_unbind_clone, "needs investigation"
exclude :test_super_method_module, "needs investigation"
exclude :test_public_methods_with_extended, "needs investigation"
exclude :test_method_list, "needs investigation"
exclude :test_override_optimized_method_on_class_using_prepend, "NoMethodError: undefined method `unpack1' for nil:NilClass"
exclude :test_method_visibility_predicates, "NoMethodError: undefined method `public?' for #<Method:0xc8e248>"
exclude :test_unbound_method_visibility_predicates, "NoMethodError: undefined method `public?' for #<UnboundMethod:0xc8e298>"
