exclude :test_begininclass, "needs investigation"
exclude :test_begininmethod, "needs investigation"
exclude :test_callcc_at_exit, "needs investigation"
exclude :test_errinfo_at_exit, "needs investigation"
exclude :test_propagate_signaled, "needs investigation"
exclude :test_rescue_at_exit, "needs investigation"
exclude :test_internal_errinfo_at_exit, "needs investigation"
