exclude :test_cannot_convert_into_time_interval, "TypeError expected but nothing was raised."
exclude :test_custom_exception, "Exception(#<Class:0x448>) with message matches to \"execution expired\"."
exclude :test_enumerator_next, "test hangs"
exclude :test_handle_interrupt, "[Timeout::Error] exception expected, not #<NameError: uninitialized constant Timeout::ExitException>."
exclude :test_nested_timeout, "test hangs, flaky"
exclude :test_nested_timeout_error_identity, "test hangs, flaky"
exclude :test_nested_timeout_which_error_bubbles_up, "retain-on-retag: <\"inner message\"> expected but was <\"uninitialized constant Timeout::ExitException\">."
exclude :test_queue, "test hangs"
exclude :test_raises_exception_internally, "retain-on-retag: Exception(Timeout::Error) with message matches to /execution expired/."
exclude :test_rescue_exit, "Exception(#<Class:0x528>) with message matches to \"execution expired\"."
exclude :test_skip_rescue_standarderror, "retain-on-retag: Exception(Timeout::Error) with message matches to /execution expired/."
exclude :test_threadgroup, "<\"[]\"> expected but was <\"[#<Thread:0x2d8 /Users/andrykonchin/projects/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/lib/truffle/timeout.rb:129 sleep>]\">."
exclude :test_timeout, "flaky: timeout can be missed and test then spins in a loop"
