exclude :test_hup_me, "SignalException expected but nothing was raised."
exclude :test_invalid_signal_name, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /\\u{30eb 30d3 30fc}/ to match \"ArgumentError\"."
exclude :test_kill_immediately_before_termination, "| Exception in thread \"SIGUSR1 handler\" java.lang.IllegalStateException: Language environment is already disposed."
exclude :test_sigexit, "needs investigation"
exclude :test_signal, "transient: RuntimeError: Interrupt"
exclude :test_signal2, "ArgumentError: ArgumentError"
exclude :test_signal_exception, "Expected /SIG-SIG/ to not match \"invalid signal name SIG-SIGEXIT\"."
exclude :test_signame_delivered, "slow: 48.91s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: (16 vCPUs)"
exclude :test_trap, "ArgumentError: Unsupported command ''"
exclude :test_trap_uncatchable_KILL, "SIGKILL is not allowed to be caught."
exclude :test_trap_uncatchable_STOP, "SIGSTOP is not allowed to be caught."
