exclude :test_casecmp2, "<0> expected but was <-1>."
exclude :test_hex, "Encoding::CompatibilityError expected but nothing was raised."
exclude :test_is_mbc_newline, "Encoding::CompatibilityError: incompatible character encodings: UTF-16LE and UTF-8"
exclude :test_oct, "Encoding::CompatibilityError expected but nothing was raised."
exclude :test_split_awk, "<2> expected but was <3>."
exclude :test_succ, "Encoding::CompatibilityError: incompatible character encodings: UTF-16BE and UTF-8"
