exclude :test_cherokee, "<\"ᎠᎡᎢᎣᎤᎥᎦᎧᎨᎩ\"> expected but was <\"ꭰꭱꭲꭳꭴꭵꭶꭷꭸꭹ\">."
exclude :test_fold_option, "<nil> expected but was <\"ss\">."
exclude :test_georgian_capitalize, "<\"აბგ\"> expected but was <\"Აბგ\">."
exclude :test_swapcase, "<\"dZ\"> expected but was <\"ǲ\">."
exclude :test_titlecase, "<\"ǳ ǆ ǉ ǌ\"> expected but was <\"ǲ ǅ ǈ ǋ\">."
