exclude :test_AREF_fstring_key, "NoMethodError: undefined method `count_objects' for ObjectSpace:Module"
exclude :test_ASET_fstring_key, "Expected \"abc\" (oid=1032) to be the same as \"abc\" (oid=1048)."
exclude :test_ASET_fstring_non_literal_key, "Expected \"abc_def\" (oid=1080) to be the same as \"abc_def\" (oid=1096)."
exclude :test_NEWHASH_fstring_key, "Expected \"ABC\" (oid=1160) to be the same as \"ABC\" (oid=32)."
exclude :test_any_hash_fixable, "very slow: 178.88s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_ar2st, "<no message> (java.lang.AssertionError) from org.truffleruby.core.hash.library.PackedHashStoreLibrary.verify(PackedHashStoreLibrary.java:396)"
exclude :test_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_callcc_escape, "Exception raised: <#<RuntimeError: Continuations are unsupported on TruffleRuby>>"
exclude :test_callcc_iter_level, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_callcc_reenter, "Exception raised: <#<RuntimeError: Continuations are unsupported on TruffleRuby>>"
exclude :test_create, "ArgumentError expected but nothing was raised."
exclude :test_fetch_error, "Expected /\\.\\.\\.\\z/ to match \"key not found: \\\"gumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumby\\\"\"."
exclude :test_float_hash_random, "very slow: 70.52s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_huge_iter_level, "spurious; RuntimeError expected but nothing was raised."
exclude :test_integer_hash_random, "very slow: 69.57s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_inverse_hash, "<3732844395273875856> expected to be != to"
exclude :test_iterlevel_in_ivar_bug19589, "SystemStackError: stack level too deep"
exclude :test_merge!, "FrozenError expected but nothing was raised."
exclude :test_recursive_hash_value_struct, "Exception raised: <#<SystemStackError: stack level too deep from java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:85)>>"
exclude :test_rehash2, "RuntimeError expected but nothing was raised."
exclude :test_reject, "Expected 42 to be nil."
exclude :test_reject_on_identhash, "<{}> expected but was <{\"str\"=>1, \"str\"=>2}>."
exclude :test_s_AREF_from_pairs, "ArgumentError expected but nothing was raised."
exclude :test_select_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was <{\"str\"=>2}>."
exclude :test_select_reject_will_not_rehash, "<1> expected but was <2>."
exclude :test_slice_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was <{\"str\"=>2}>."
exclude :test_symbol_hash_random, "slow: 43.82s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_to_proc, "<true> expected but was <false>."
exclude :test_transform_keys_bang, "<{false=>1, :b=>2, :c=>3}> expected but was <{false=>1}>."
exclude :test_transform_values_on_identhash, "<{1=>2, 3=>4, 5=>6, \"str\"=>1, \"str\"=>2}> expected but was <{1=>2, 3=>4, 5=>6, \"str\"=>2}>."
exclude :test_update5, "FrozenError expected but nothing was raised."
