exclude :test_many_fibers, "OOM"
exclude :test_fatal_in_fiber, "inter-test dependency"
exclude :test_stack_size, "RubyVM-specific"
exclude :test_no_valid_cfp, "needs investigation"
exclude :test_fiber_transfer_segv, "RubyVM-specific"
exclude :test_gc_root_fiber, "RubyVM-specific"
exclude :test_many_fibers_with_threads, "needs investigation"
exclude :test_to_s, "needs investigation"
exclude :test_machine_stack_gc, "spurious"
exclude :test_error, "needs investigation"
exclude :test_raise, "needs investigation"
