exclude :test_argument_forwarding, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1872:in `test_argument_forwarding'."
exclude :test_array_kwsplat_hash, "<[]> expected but was <[{}]>."
exclude :test_class_module_Object_ancestors, "TypeError: 1:Integer is not a class"
exclude :test_constant_reassignment_nested, "very slow: 85.74s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_constant_reassignment_toplevel, "very slow: 84.30s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_dedented_heredoc_concatenation, "<\"\\n\" + \"0\\n\" + \"1\"> expected but was <\" \\n\" + \"0\\n\" + \"1\">."
exclude :test_duplicated_when, "expected: /3: warning: duplicated `when' clause with line 3 is ignored.+4: warning: duplicated `when' clause with line 3 is ignored.+4: warning: duplicated `when' clause with line 3 is ignored.+5: warning: duplicated `when' clause with line 3 is ignored.+5: warning: duplicated `when' clause with line 3 is ignored/m"
exclude :test_duplicated_when_check_option, "| -:4: warning: 'when' clause on line 4 duplicates 'when' clause on line 3 and is ignored"
exclude :test_error_message_encoding, "```# -*- coding: utf-8 -*-\ndef n \"∈\"; end\n```"
exclude :test_eval_return_toplevel, "NameError: uninitialized constant TestSyntax::Tempfile"
exclude :test_hash_kwsplat_hash, "<false> expected but was <true>."
exclude :test_heredoc_no_terminator, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1110:in `test_heredoc_no_terminator'."
exclude :test_invalid_jump, "| truffleruby: -e:1: Invalid redo (SyntaxError)"
exclude :test_it, "expected: /`it`/"
exclude :test_keyword_self_reference, "SyntaxError: (eval):1: circular argument reference - var"
exclude :test_method_call_location, "<1668> expected but was <1665>."
exclude :test_methoddef_endless_command, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1726:in `test_methoddef_endless_command'."
exclude :test_no_label_with_percent, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:559:in `test_no_label_with_percent'."
exclude :test_numbered_parameter, "<[:a]> expected but was <[0]>."
exclude :test_optional_self_reference, "SyntaxError: (eval):1: circular argument reference - var"
exclude :test_parenthesised_statement_argument, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1322:in `test_parenthesised_statement_argument'."
exclude :test_return_in_BEGIN_in_eval, "Exception raised: <#<LocalJumpError: unexpected return>>"
exclude :test_return_toplevel, "very slow: 295.12s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_return_toplevel_with_argument, "LocalJumpError: unexpected return"
exclude :test_script_lines, "<[\"/b/b/e/.tmp/bug4361_20241021-46113-p8ox4l\"]> expected but was <[]>."
exclude :test_script_lines_encoding, "needs investigation"
exclude :test_syntax_error_at_newline, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1547:in `test_syntax_error_at_newline'."
exclude :test_warn_balanced, "needs investigation"
