exclude :test_file_mapped, "NameError: uninitialized constant IO::Buffer"
exclude :test_endian, "NameError: uninitialized constant IO::Buffer"
exclude :test_new_readonly, "NameError: uninitialized constant IO::Buffer"
exclude :test_new_mapped, "NameError: uninitialized constant IO::Buffer"
exclude :test_flags, "NameError: uninitialized constant IO::Buffer"
exclude :test_default_size, "NameError: uninitialized constant IO::Buffer"
exclude :test_compare_same_size, "NameError: uninitialized constant IO::Buffer"
exclude :test_slice, "NameError: uninitialized constant IO::Buffer"
exclude :test_write, "NameError: uninitialized constant IO::Buffer"
exclude :test_pwrite, "NameError: uninitialized constant IO::Buffer"
exclude :test_read, "NameError: uninitialized constant IO::Buffer"
exclude :test_slice_bounds, "NameError: uninitialized constant IO::Buffer"
exclude :test_clear, "NameError: uninitialized constant IO::Buffer"
exclude :test_string_mapped, "NameError: uninitialized constant IO::Buffer"
exclude :test_invalidation, "NameError: uninitialized constant IO::Buffer"
exclude :test_pread, "NameError: uninitialized constant IO::Buffer"
exclude :test_locked, "NameError: uninitialized constant IO::Buffer"
exclude :test_get_string, "NameError: uninitialized constant IO::Buffer"
exclude :test_resize_preserve, "NameError: uninitialized constant IO::Buffer"
exclude :test_compare_different_size, "NameError: uninitialized constant IO::Buffer"
exclude :test_string_mapped_frozen, "NameError: uninitialized constant IO::Buffer"
exclude :test_resize_mapped, "NameError: uninitialized constant IO::Buffer"
exclude :test_get_set_primitives, "NameError: uninitialized constant IO::Buffer"
exclude :test_new_internal, "NameError: uninitialized constant IO::Buffer"
exclude :test_file_mapped_invalid, "[NoMethodError] exception expected, not #<NameError: uninitialized constant IO::Buffer>."
exclude :test_non_string, "[TypeError] exception expected, not #<NameError: uninitialized constant IO::Buffer>."
