exclude :test_realworld_default_gem, "needs investigation"
exclude :test_no_kernel_require_in_Kernel_warn_with_uplevel, "needs investigation"
exclude :test_no_other_behavioral_changes_with_Kernel_warn, "needs investigation"
exclude :test_no_other_behavioral_changes_with_warn, "needs investigation"
exclude :test_no_kernel_require_in_warn_with_uplevel, "needs investigation"
exclude :test_normal_gems_with_overridden_load_error_message, "needs investigation"
exclude :test_realworld_upgraded_default_gem, "needs investigation"
