exclude :test_def_method_with_fname, "needs investigation"
exclude :test_def_method_without_filename, "needs investigation"
exclude :test_keep_lineno, "needs investigation"
exclude :test_core, "needs investigation"
exclude :test_token_extension, "needs investigation"
