exclude :test_cause_at_end, "| "
exclude :test_cause_raised_in_rescue, "cause should not be overwritten by reraise."
exclude :test_cause_thread_with_cause, "NoMethodError: undefined method `message' for nil:NilClass"
exclude :test_circular_cause, "Expected #<RuntimeError: error 2> to be nil."
exclude :test_circular_cause_handle, "Exception(ArgumentError) with message matches to /circular cause/."
exclude :test_errinfo_encoding_in_debug, "Expected \"\" to include \"#<Module:0x5b8>::Cエラー\"."
exclude :test_errinfo_in_debug, "needs investigation"
exclude :test_exception_in_ensure_with_next, "NameError: uninitialized constant TestException::RubyVM"
exclude :test_inspect, "<\"#<Class:0x718>\"> expected but was <nil>."
exclude :test_machine_stackoverflow, "assert_separately failed with error message"
exclude :test_machine_stackoverflow_by_define_method, "assert_separately failed with error message"
exclude :test_marshal_circular_cause, "\"\\x04\\bo:\\x11RuntimeError\\b:\\tmesgI\\\"\\berr\\x06:\\x06ET:\\abt[\\x00:\\ncauseo:\\x0EException\\a;\\x060;\\b0\"."
exclude :test_non_exception_cause, "Exception(TypeError) with message matches to /exception/."
exclude :test_output_string_encoding, "<1> expected but was <0>."
exclude :test_raise_with_cause, "[TypeError] exception expected, not #<RuntimeError: [Feature #8257]>."
exclude :test_stackoverflow, "<no message> (java.lang.IndexOutOfBoundsException) from com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java:-1)"
exclude :test_too_many_args_in_eval, "[SystemStackError] exception expected, not #<ArgumentError: wrong number of arguments (given 140000, expected 0..3)>."
exclude :test_undef_Warning_warn, "[NoMethodError] exception expected, not #<NameError: undefined method `warn' for class `Module'>."
exclude :test_undefined_backtrace, "assert_separately failed with error message"
exclude :test_warning_warn_circular_require_backtrace, "Expected /^\\tfrom \\/tmp\\/circular20240905\\-98331\\-tcktqz\\.rb:1:/ to match \"/tmp/circular20240905-98331-tcktqz.rb:1: warning: loading in progress, circular require considered harmful - /tmp/circular20240905-98331-tcktqz.rb\\n\"."
exclude :test_wrong_backtrace, "assert_separately failed with error message"
