exclude :test_threaded_accessing_constant, "needs investigation"
exclude :test_threaded_accessing_inner_constant, "needs investigation"
exclude :test_bug_13526, "spurious and buggy test"
exclude :test_autoload_same_file, "hangs"
exclude :test_autoload_p, "needs investigation"
exclude :test_source_location, "needs investigation"
