exclude :test_europe_berlin, "[ruby-core:67345] [Bug #10698]"
exclude :test_localtime_zone, "<\"GMT+08:00\"> expected but was"
exclude :test_america_los_angeles, "RangeError: bignum too big to convert into `long'"
exclude :test_europe_lisbon, "RangeError: bignum too big to convert into `long'"
exclude :test_utc_names, "ArgumentError: \"+HH:MM\", \"-HH:MM\", \"UTC\" or \"A\"..\"I\",\"K\"..\"Z\" expected for utc_offset: utc"
