exclude :test_aset, "needs investigation"
exclude :test_assoc, "needs investigation"
exclude :test_delete, "needs investigation"
exclude :test_fetch, "needs investigation"
exclude :test_frozen_env, "needs investigation"
exclude :test_getenv, "needs investigation"
exclude :test_has_key, "needs investigation"
exclude :test_except, "needs investigation"
exclude :test_clone, "expected: /ENV\\.clone is deprecated; use ENV\\.to_h instead/"
exclude :test_dup, "TypeError expected but nothing was raised."
