exclude :test_beg_len, "TypeError: no implicit conversion of Object into Integer"
exclude :test_comparison_when_recursive, "SystemStackError: stack level too deep"
exclude :test_cover, "Expected 1..5 to not be cover? 3..2."
exclude :test_cyclic_range_inspect, "SystemStackError: stack level too deep"
exclude :test_duckrange, "TypeError: no implicit conversion of TestRange::DuckRange into Integer"
exclude :test_each, "NoMethodError: undefined method `<' for nil:NilClass"
exclude :test_eqq_string, "TypeError expected but nothing was raised."
exclude :test_frozen_initialize, "FrozenError expected but nothing was raised."
exclude :test_include, "hangs"
exclude :test_initialize_twice, "[FrozenError] exception expected, not #<NameError: `initialize' called twice>."
exclude :test_last_with_redefine_each, "needs investigation"
exclude :test_max, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_min, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_range_bsearch_for_floats, "needs investigation"
exclude :test_range_numeric_string, "<[\"9\", \"10\"]> expected but was <[]>."
exclude :test_step, "ArgumentError expected but nothing was raised."
