exclude :test_capacity_equals_to_new_size, "RangeError: cannot convert endless range to an array"
exclude :test_coderange_after_append, "RangeError: cannot convert endless range to an array"
exclude :test_coderange_after_trunc, "RangeError: cannot convert endless range to an array"
exclude :test_non_shared, "RangeError: cannot convert endless range to an array"
exclude :test_shared, "RangeError: cannot convert endless range to an array"
