exclude :"test_existence_of_mathn/complex", "needs investigation"
exclude :"test_existence_of_mathn/rational", "needs investigation"
exclude :test_existence_of_nkf, "needs investigation"
exclude :test_existence_of_openssl, "needs investigation"
exclude :test_existence_of_pty, "needs investigation"
exclude :"test_existence_of_racc/cparse", "needs investigation"
exclude :test_existence_of_ripper, "needs investigation"
exclude :test_existence_of_sdbm, "needs investigation"
