exclude :test_accessing_fastly, "accesses a public web site at runtime"
exclude :test_accessing_new_index, "accesses a public web site at runtime"
exclude :test_accessing_rubygems, "accesses a public web site at runtime"
exclude :test_accessing_staging, "needs investigation"
exclude :test_accessing_www_rubygems, "needs investigation"
