exclude :test_close_at_exit, "needs investigation"
exclude :test_fiber_without_scheduler, "needs investigation"
exclude :test_closed_at_thread_exit, "needs investigation"
exclude :test_closed_when_set_to_nil, "needs investigation"
exclude :test_fiber_new, "needs investigation"
exclude :test_fiber_new_with_options, "needs investigation"
exclude :test_optional_close, "needs investigation"
