exclude :test_enumerator_count, "NoMethodError: undefined method `[]=' for Fiber:Class"
exclude :test_enumerator_inherited_storage, "NoMethodError: undefined method `[]=' for Fiber:Class"
exclude :test_inherited_storage, "ArgumentError: unknown keyword: :storage"
exclude :test_storage, "NoMethodError: undefined method `[]=' for Fiber:Class"
exclude :test_storage_assignment, "NoMethodError: undefined method `storage=' for #<Fiber:0x408>"
exclude :test_storage_assignment_type_error, "[TypeError] exception expected, not #<ArgumentError: unknown keyword: :storage>."
exclude :test_storage_inherited, "NoMethodError: undefined method `[]=' for Fiber:Class"
exclude :test_storage_only_allow_access_from_same_fiber, "[ArgumentError] exception expected, not #<NoMethodError: undefined method `storage' for #<Fiber:0x498>>."
exclude :test_thread_inherited_storage, "NoMethodError: undefined method `[]=' for Fiber:Class"
exclude :test_variable_assignment, "NoMethodError: undefined method `[]=' for Fiber:Class"
