exclude :test_bom_8, "needs investigation"
exclude :test_eof_0, "needs investigation"
exclude :test_eof_0_seek, "needs investigation"
exclude :test_eof_1, "needs investigation"
exclude :test_gets_para_extended_file, "needs investigation"
exclude :test_realpath_encoding, "needs investigation"
exclude :test_uninitialized, "needs investigation"
exclude :test_file_share_delete, "needs investigation"
exclude :test_stat, "needs investigation"
exclude :test_realpath_special_symlink, "needs investigation"
exclude :test_open_tempfile_path, "fails on aarch64-linux" if RUBY_PLATFORM == 'aarch64-linux'
