exclude :test_each_object_singleton_class, "needs investigation"
exclude :test_finalizer, "needs investigation"
exclude :test_id2ref_invalid_argument, "needs investigation"
exclude :test_count_objects, "needs investigation"
exclude :test_id2ref_liveness, "needs investigation"
exclude :test_exception_in_finalizer, "pid 283258 exit 1"
