exclude :test_finalizer_passed_object_id, "needs investigation"
exclude :test_finalizing_main_thread, "needs investigation"
exclude :test_gc_parameter, "needs investigation"
exclude :test_stat, "needs investigation"
exclude :test_stat_argument, "needs investigation"
exclude :test_stat_constraints, "needs investigation"
exclude :test_stat_single, "needs investigation"
exclude :test_gc_internals, "needs investigation"
exclude :test_interrupt_in_finalizer, "needs investigation"
exclude :test_latest_gc_info, "needs investigation"
exclude :test_latest_gc_info_argument, "needs investigation"
exclude :test_start_full_mark, "needs investigation"
exclude :test_start_immediate_sweep, "needs investigation"
exclude :test_verify_internal_consistency, "needs investigation"
exclude :test_gc_disabled_start, "fails on native: GR-38054"
exclude :test_exception_in_finalizer_procs, "transient"
exclude :test_exception_in_finalizer_method, "pid 277840 exit 0."
exclude :test_stat_heap, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_stat_heap_constraints, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_stat_heap_all, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_latest_gc_info_need_major_by, "NameError: uninitialized constant GC::OPTS"
exclude :test_thrashing_for_young_objects, "NoMethodError: undefined method `stat_heap' for GC:Module"
exclude :test_ast_node_buffer, "SyntaxError: (eval):2: YARPTranslator does not know how to translate ShareableConstantNode at (eval):2"
