exclude :test_america_los_angeles, "RangeError: bignum too big to convert into `long'"
exclude :test_europe_berlin, "TZ=Europe/Berlin Time.local(2011, 10, 30, 2, 0, 0)."
exclude :test_europe_lisbon, "RangeError: bignum too big to convert into `long'"
exclude :test_localtime_zone, "<\"GMT+08:00\"> expected but was <\"PST\">."
exclude :test_utc_names, "ArgumentError: \"+HH:MM\", \"-HH:MM\", \"UTC\" or \"A\"..\"I\",\"K\"..\"Z\" expected for utc_offset: utc"
