exclude :test_branch_coverage_for_case_statement, "needs investigation"
exclude :test_branch_coverage_for_if_statement, "needs investigation"
exclude :test_branch_coverage_for_pattern_matching, "needs investigation"
exclude :test_branch_coverage_for_safe_method_invocation, "needs investigation"
exclude :test_branch_coverage_for_while_statement, "needs investigation"
exclude :test_clear_with_branches, "needs investigation"
exclude :test_clear_with_lines, "needs investigation"
exclude :test_clear_with_methods, "needs investigation"
exclude :test_clear_with_oneshot_lines, "needs investigation"
exclude :test_coverage_optimized_branch, "needs investigation"
exclude :test_eval, "needs investigation"
exclude :test_line_coverage_for_multiple_lines, "needs investigation"
exclude :test_method_coverage, "needs investigation"
exclude :test_method_coverage_for_alias, "needs investigation"
exclude :test_method_coverage_for_define_method, "needs investigation"
exclude :test_method_coverage_for_singleton_class, "needs investigation"
exclude :test_oneshot_line_coverage, "needs investigation"
exclude :test_restarting_coverage, "needs investigation"
exclude :test_stop_wrong_peephole_optimization, "needs investigation"
exclude :test_line_stub, "needs investigation"
exclude :test_branch_coverage_in_ensure_clause, "needs investigation"
exclude :test_double_resume, "pid 271370 exit 1"
exclude :test_coverage_with_asan, "pid 271410 exit 1"
exclude :test_coverage_state, "pid 271430 exit 1"
exclude :test_result_after_suspend, "pid 271450 exit 1"
exclude :test_result_without_resume, "pid 271490 exit 1"
exclude :test_resume_without_setup, "pid 271530 exit 1"
exclude :test_suspend_without_setup, "pid 271550 exit 1"
exclude :test_coverage_suspendable, "pid 271590 exit 1"
exclude :test_double_suspend, "pid 271610 exit 1"
