exclude :test_call_ifunc_iseq_large_array_splat_fail, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_ifunc_iseq_large_array_splat_pass, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_op_asgn_keywords, "<[[], {}, nil, [4], {}, nil]> expected but was <[[{}], {}, nil, [{}, 4], {}, nil]>."
exclude :test_call_op_asgn_keywords_mutable, "<[[2], {:b=>5}, [2, 4], {:b=>5}]> expected but was <[[2, {:b=>5}], {}, [2, {:b=>5}, 4], {}]>."
exclude :test_call_rb_call_bmethod_large_array_splat_fail, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_rb_call_bmethod_large_array_splat_pass, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_rb_call_iseq_large_array_splat_fail, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_rb_call_iseq_large_array_splat_pass, "NameError: uninitialized constant TestCall::Bug"
exclude :test_kwsplat_block_order_op_asgn, "<[:to_hash, :to_proc, :to_proc]> expected but was <[:to_hash, :to_proc]>."
