exclude :test_k_lead_opt_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_opt_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_opt_trail_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_opt_var_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_opt_var_trail_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_var_hash, "ArgumentError expected but nothing was raised."
exclude :test_lead_var_trail_hash, "ArgumentError expected but nothing was raised."
exclude :test_n_lead_opt_hash, "ArgumentError expected but nothing was raised."
exclude :test_opt_hash, "<[0, nil, {\"a\"=>0, :b=>1}]> expected but was <[1, {\"a\"=>0, :b=>1}, nil]>."
exclude :test_opt_trail_hash, "ArgumentError expected but nothing was raised."
exclude :test_opt_var_hash, "<[1, \"a\", [], {\"b\"=>0, :c=>1}]> expected but was <[2, \"a\", [{\"b\"=>0, :c=>1}], nil]>."
exclude :test_opt_var_trail_hash, "ArgumentError expected but nothing was raised."
exclude :test_var_hash, "<[0, [], {\"a\"=>0, :b=>1}]> expected but was <[1, [{\"a\"=>0, :b=>1}], nil]>."
exclude :test_var_trail_hash, "ArgumentError expected but nothing was raised."
