exclude :test_abort_on_exception, "| Exception: `RuntimeError' at -:3:in `block in <main>' - "
exclude :test_handle_interrupt, "transient: <[:on_blocking, :c1]> expected but was <[:on_blocking, :c2]>."
exclude :test_handle_interrupt_and_io, "needs investigation"
exclude :test_handle_interrupt_and_p, "transient"
exclude :test_handle_interrupt_blocking, "<:ok> expected but was <nil>."
exclude :test_handle_interrupt_invalid_argument, "[ArgumentError] exception expected, not #<TypeError: TruffleRuby doesn't have a case for the org.truffleruby.core.thread.ThreadNodesFactory$HandleInterruptNodeFactory$HandleInterruptNodeGen node with values of type Thread(org.truffleruby.core.thread.RubyThread) org.truffleruby.core.symbol.RubySymbol org.truffleruby.language.Nil"
exclude :test_handle_interrupted?, "<:ok> expected but was <:ng1>."
exclude :test_ignore_deadlock, "very slow: 60.41s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_join_argument_conversion, "TypeError: TruffleRuby doesn't have a case for the org.truffleruby.core.thread.ThreadNodesFactory$JoinNodeFactory$JoinNodeGen node with values of type TestThread::Thread(org.truffleruby.core.thread.RubyThread) #<Class:0x648>(org.truffleruby.core.basicobject.RubyBasicObject)"
exclude :test_kill_wrong_argument, "[TypeError] exception expected, not #<NoMethodError: undefined method `kill' for nil:NilClass>."
exclude :test_machine_stack_size, "transient; Expected 46 to be >= 47"
exclude :test_main_thread_status_at_exit, "needs investigation"
exclude :test_no_valid_cfp, "transient; java.lang.AssertionError: null element in Object[] at index 0: [null] at org.graalvm.ruby/org.truffleruby.language.RubyBaseNode.createArray(RubyBaseNode.java:220)"
exclude :test_pending_interrupt?, "ArgumentError: Thread#pending_interrupt? does not support being called for another Thread than the current Thread"
exclude :test_priority, "spurious; Expected 3481319 to be > 3618431."
exclude :test_stack_size, "NoMethodError: undefined method `[]' for nil:NilClass"
exclude :test_stop, "transient; hangs"
exclude :test_switch_while_busy_loop, "transient"
exclude :test_thread_interrupt_for_killed_thread, "transient; hangs or very slow -- high CPU"
exclude :test_thread_invalid_name, "[ArgumentError] exception expected, not #<Encoding::CompatibilityError: incompatible character encodings: UTF-32BE and UTF-8>."
exclude :test_thread_join_current, "test hangs"
exclude :test_thread_join_main_thread, "test hangs"
exclude :test_thread_native_thread_id_across_fork_on_linux, "NoMethodError: undefined method `sym_defined?' for #<Fiddle::Handle:0x8a8>"
exclude :test_thread_value_in_trap, "transient"
exclude :test_uninitialized, "ArgumentError: Thread#pending_interrupt? does not support being called for another Thread than the current Thread"
exclude :test_vm_machine_stack_size, "transient; 0 size. Expected 38046 to be > 40594"
exclude :test_wakeup, "flaky; ThreadError expected but nothing was raised."
exclude :test_yield_across_thread_through_enum, "LocalJumpError: unexpected return"
