exclude :test_argf, "<\"[\\\"1\\\", 1, \\\"1\\\", 1]\"> expected but was <\"[\\\"1\\\", 1, \\\"3\\\", 1]\">."
exclude :test_close_replace, "hangs"
exclude :test_each_line_chomp, "| <internal:core> core/type.rb:280:in `convert_type': no implicit conversion of Hash into Integer (TypeError)"
exclude :test_each_line_limit_0, "ArgumentError expected but nothing was raised."
exclude :test_encoding, "<\"true\\n\" + \"true\\n\" + \"true\\n\" + \"nil\\n\"> expected but was <\"true\\n\" + \"false\\n\" + \"true\\n\" + \"nil\\n\">."
exclude :test_eof, "<\"false\"> expected but was <\"nil\">."
exclude :test_inplace, "| -:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)"
exclude :test_inplace2, "| -:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)"
exclude :test_inplace3, "| truffleruby: the -i option is not implemented"
exclude :test_inplace_bug_17117, "needs investigation"
exclude :test_inplace_dup, "| -:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)"
exclude :test_inplace_invalid_backup, "[ArgumentError] exception expected, not #<NoMethodError: undefined method `inplace_mode=' for #<Truffle::ARGFClass:0x988>>."
exclude :test_inplace_no_backup, "<[]> expected but was <[\"-:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)\"]>."
exclude :test_inplace_nonascii, "| truffleruby: the -i option is not implemented"
exclude :test_inplace_rename_impossible, "Expected /Can't rename .* to .*: .*. skipping file/ to match \"-:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)\"."
exclude :test_inplace_stdin, "| -:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)"
exclude :test_inplace_stdin2, "| -:2:in `<main>': undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xc8> (NoMethodError)"
exclude :test_inplace_suffix_encoding, "NoMethodError: undefined method `inplace_mode=' for #<Truffle::ARGFClass:0xb08>"
exclude :test_lineno, "<\"2001\"> expected but was <\"1003\">."
exclude :test_read3, "<\"nil\\n\" + \"\\\"\\\"\\n\"> expected but was <\"\\\"\\\"\\n\" + \"\\\"\\\"\\n\">."
exclude :test_read_nonblock, "<\"done with eof\\n\"> expected but was <nil>."
exclude :test_readbyte, "<\"[49, 10, 50, 10, 51, 10, 52, 10, 53, 10, 54, 10]\\n\"> expected but was <\"[\\\"1\\\", \\\"\\\\n\\\", \\\"2\\\", \\\"\\\\n\\\", \\\"3\\\", \\\"\\\\n\\\", \\\"4\\\", \\\"\\\\n\\\", \\\"5\\\", \\\"\\\\n\\\", \\\"6\\\", \\\"\\\\n\\\"]\\n\">."
exclude :test_readline_chomp, "TypeError: no implicit conversion of Hash into Integer"
exclude :test_readlines_chomp, "TypeError: no implicit conversion of Hash into Integer"
exclude :test_readlines_limit_0, "very slow: 3090.95s on truffleruby 24.2.0-dev-76574fc8*, like ruby 3.3.5, Interpreted JVM [x86_64-darwin23] with Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz: ( 16 vCPUs)"
exclude :test_textmode, "<\"1\\n\" + \"2\\n\" + \"3\\n\" + \"4\\n\" + \"5\\n\" + \"6\\n\"> expected but was <\"1\\n\" + \"2\\n\" + \"3\\n\" + \"4\\n\" + \"5\\r\\n\" + \"6\\r\\n\">."
exclude :test_unreadable, "Exception(Errno::ENOENT) with message matches to /- \\/tmp\\/bug4274\\-20240907\\-971677\\-f4faiq\\z/."
