exclude :test_kill_immediately_before_termination, "pid 43233 exit 0."
exclude :test_trap_uncatchable_STOP, "SIGSTOP is not allowed to be caught."
exclude :test_hup_me, "assert_separately failed"
exclude :test_sigexit, "pid 43488 exit 0."
exclude :test_trap_uncatchable_KILL, "SIGKILL is not allowed to be caught."
exclude :test_sigchld_ignore, "Errno::ECHILD expected but nothing was raised."
exclude :test_invalid_signal_name, "Expected Exception(ArgumentError) was raised, but the message doesn't match."
exclude :test_signal_exception, "Expected /SIG-SIG/ to not match \"invalid signal name SIG-SIGEXIT\"."
exclude :test_trap, "ArgumentError: Unsupported command ''"
exclude :test_signal2, "ArgumentError: ArgumentError"
exclude :test_trap_system_default, "ArgumentError: Signal already used by VM or OS: SIGQUIT"
