exclude :test_else_without_rescue, "[\"/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb\", 21]."
exclude :test_error_def_in_argument, "-:7:in `<main>'."
exclude :test_error_line, "Message to pipe should end with a newline."
exclude :test_float, "/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:763:in `test_float'."
exclude :test_global_variable, "/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:774:in `test_global_variable'."
exclude :test_invalid_char, "[ruby-core:64243] [Bug #10117]"
exclude :test_location_of_invalid_token, "/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1192:in `test_location_of_invalid_token'."
exclude :test_magic_comment, "[ArgumentError] exception expected, not #<SyntaxError: /Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:708: unknown or invalid encoding in the magic comment>."
exclude :test_method_block_location, "[ruby-core:40936]."
exclude :test_method_location_in_rescue, "[ruby-core:79388] [Bug #13181]."
exclude :test_string, "from the backslash through the invalid char."
exclude :test_unclosed_unicode_escape_at_eol_bug_19750, "-:7:in `<main>'."
exclude :test_unexpected_eof, "/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1188:in `test_unexpected_eof'."
exclude :test_unexpected_token_after_numeric, "/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1136:in `test_unexpected_token_after_numeric'."
exclude :test_unused_variable, "expected: /あ/"
exclude :test_utf8_bom, "Exception raised:"
exclude :test_void_expr_stmts_value, "expected: /unused/"
exclude :test_yyerror_at_eol, "/Users/andrykonchin/projects/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1042:in `test_yyerror_at_eol'."
exclude :test_question, "SyntaxError: (eval):1: cannot eval() a String with binary encoding, with no magic encoding comment and containing a non-US-ASCII character: \\xFF"
exclude :test_shareable_constant_value_nested, "SyntaxError: (eval):6: YARPTranslator does not know how to translate ShareableConstantNode at (eval):6"
exclude :test_shareable_constant_value_nonliteral, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_simple, "SyntaxError: (eval):3: YARPTranslator does not know how to translate ShareableConstantNode at (eval):3"
exclude :test_shareable_constant_value_unfrozen, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_unshareable_literal, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_truncated_source_line, "NoMethodError: undefined method `start_with?' for nil:NilClass"
