exclude :test_coerce, "needs investigation"
exclude :test_coerced_remainder, "needs investigation"
exclude :test_dummynumeric, "needs investigation"
exclude :test_dup, "needs investigation"
exclude :test_step, "needs investigation"
exclude :test_floor_ceil_ndigits, "[ruby-core:100090]."
exclude :test_float_round_ndigits, "[ruby-core:86323] (argument: 16)."
exclude :test_remainder_infinity, "<4> expected but was"
