exclude :test_KCODE_warning, "needs investigation"
exclude :test_assign_named_capture_to_const, "needs investigation"
exclude :test_assign_named_capture_to_reserved_word, "needs investigation"
exclude :test_dup_warn, "needs investigation"
exclude :test_equal, "needs investigation"
exclude :test_ignorecase_warning, "needs investigation"
exclude :test_initialize, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_invalid_escape_error, "needs investigation"
exclude :test_invalid_fragment, "needs investigation"
exclude :test_match_offset_begin_end, "needs investigation"
exclude :test_match_values_at, "needs investigation"
exclude :test_matchdata, "needs investigation"
exclude :test_named_capture, "needs investigation"
exclude :test_named_capture_nonascii, "needs investigation"
exclude :test_parse, "needs investigation"
exclude :test_parse_kg, "needs investigation"
exclude :test_regsub, "needs investigation"
exclude :test_source_unescaped, "needs investigation"
exclude :test_unescape, "needs investigation"
exclude :test_uninitialized, "needs investigation"
exclude :test_absent, "needs investigation"
exclude :test_match_aref, "needs investigation"
exclude :test_match_init_copy, "needs investigation"
exclude :test_match_without_regexp, "needs investigation"
exclude :test_once_multithread, "needs investigation"
exclude :test_quote, "needs investigation"
exclude :test_to_s, "needs investigation"
exclude :test_to_s_extended_subexp, "needs investigation"
exclude :test_union, "needs investigation"
exclude :test_invalid_free_at_parse_depth_limit_over, "needs investigation"
exclude :test_dup, "initialize_copy not implemented in TruffleRuby"
exclude :test_backref_overrun, "needs investigation"
exclude :test_ignorecase, "needs investigation"
exclude :test_match, "needs investigation"
exclude :test_posix_bracket, "needs investigation"
exclude :test_rindex_regexp, "needs investigation"
exclude :test_yoshidam_net_20041111_1, "needs investigation"
exclude :test_match_control_meta_escape, "<0> expected but was"
exclude :test_initialize_option, "<//m> expected but was"
exclude :test_initialize_bool_warning, "expected: /expected true or false as ignorecase/"
exclude :test_linear_time_p, "NoMethodError: undefined method `linear_time?' for Regexp:Class"
exclude :test_match_data_deconstruct_keys, "NoMethodError: undefined method `deconstruct_keys' for #<MatchData \"foobarbaz\">"
exclude :test_extended_comment_invalid_escape_bug_18294, "assert_separately failed with error message"
exclude :test_timeout_nil, "NoMethodError: undefined method `timeout=' for Regexp:Class"
exclude :test_timeout_shorter_than_global, "NoMethodError: undefined method `timeout=' for Regexp:Class"
exclude :test_cache_optimization_square, "NoMethodError: undefined method `timeout=' for Regexp:Class"
exclude :test_timeout_corner_cases, "NoMethodError: private method `timeout' called for //:Regexp"
exclude :test_timeout_longer_than_global, "NoMethodError: undefined method `timeout=' for Regexp:Class"
exclude :test_cache_optimization_exponential, "NoMethodError: undefined method `timeout=' for Regexp:Class"
exclude :test_s_timeout_corner_cases, "NoMethodError: private method `timeout' called for Regexp:Class"
exclude :test_bug_19467, "NoMethodError: undefined method `timeout=' for Regexp:Class"
exclude :test_s_timeout, "NoMethodError: undefined method `timeout=' for Regexp:Class"
