exclude :test_argument_forwarding, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:1717:in `test_argument_forwarding'."
exclude :test_array_kwsplat_hash, "<[]> expected but was <[{}]>."
exclude :test_class_module_Object_ancestors, "TypeError: 1:Integer is not a class"
exclude :test_constant_reassignment_nested, "very slow: 85.74s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_constant_reassignment_toplevel, "very slow: 84.30s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_dedented_heredoc_concatenation, "<\"\\n\" + \"0\\n\" + \"1\"> expected but was <\" \\n\" + \"0\\n\" + \"1\">."
exclude :test_duplicated_when, "expected: /3: warning: duplicated `when' clause with line 3 is ignored.+4: warning: duplicated `when' clause with line 3 is ignored.+4: warning: duplicated `when' clause with line 3 is ignored.+5: warning: duplicated `when' clause with line 3 is ignored.+5: warning: duplicated `when' clause with line 3 is ignored/m"
exclude :test_duplicated_when_check_option, "| -:4: warning: 'when' clause on line 4 duplicates 'when' clause on line 3 and is ignored"
exclude :test_error_message_encoding, "```# -*- coding: utf-8 -*-\ndef n \"∈\"; end\n```"
exclude :test_hash_kwsplat_hash, "<false> expected but was <true>."
exclude :test_heredoc_no_terminator, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:1074:in `test_heredoc_no_terminator'."
exclude :test_invalid_break, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:715:in `test_invalid_break'."
exclude :test_invalid_jump, "| truffleruby: -e:1: Invalid redo (SyntaxError)"
exclude :test_invalid_next, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:721:in `test_invalid_next'."
exclude :test_keyword_self_reference, "SyntaxError: (eval):1: circular argument reference - var"
exclude :test_method_call_location, "<1556> expected but was <1553>."
exclude :test_methoddef_endless_command, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:1614:in `test_methoddef_endless_command'."
exclude :test_no_label_with_percent, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:525:in `test_no_label_with_percent'."
exclude :test_numbered_parameter, "<[:a]> expected but was <[0]>."
exclude :test_optional_self_reference, "SyntaxError: (eval):1: circular argument reference - var"
exclude :test_parenthesised_statement_argument, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:1272:in `test_parenthesised_statement_argument'."
exclude :test_return_toplevel, "very slow: 295.12s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_return_toplevel_with_argument, "LocalJumpError: unexpected return"
exclude :test_script_lines, "<[\"/tmp/bug4361_20240905-563476-g59fvx\"]> expected but was <[]>."
exclude :test_script_lines_encoding, "needs investigation"
exclude :test_syntax_error_at_newline, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_syntax.rb:1435:in `test_syntax_error_at_newline'."
exclude :test_warn_balanced, "needs investigation"
