exclude :test_alias, "needs investigation"
exclude :test_ancestors, "spurious; <[String, Comparable, Object, Kernel, BasicObject]> expected but was <[String, JSON::Pure::Generator::GeneratorMethods::String, Comparable, Object, Kernel, BasicObject]>."
exclude :test_ancestry_of_duped_classes, "Expected #<#<Class:0x508>:0x518> to not be a kind of #<Class:0x4f8>."
exclude :test_attr, "NameError expected but nothing was raised."
exclude :test_bad_constants_get, "NameError expected but nothing was raised."
exclude :test_class_variable_in_dup_class, "<\"A\"> expected but was <\"B\">."
exclude :test_classpath, "NameError: constant TestModule::M not defined"
exclude :test_const_defined?, "[EncodingError] exception expected, not #<NameError: wrong constant name �>."
exclude :test_const_set_invalid_name, "NameError expected but nothing was raised."
exclude :test_constant_access_from_method_in_cloned_module, "NameError: uninitialized constant TestModule::CloneTestM0::TEST"
exclude :test_define_module_under_private_constant, "NameError expected but nothing was raised."
exclude :test_deprecate_constant, "expected: /#<Class:0xb68>::FOO is deprecated/"
exclude :test_frozen_visibility, "FrozenError expected but nothing was raised."
exclude :test_include_into_module_already_included, "<[:sc, :m1, :m2, :c]> expected but was <[:sc, :m1, :c]>."
exclude :test_included_modules, "spurious; <[Comparable, Kernel]> expected but was [JSON::Pure::Generator::GeneratorMethods::String, Comparable, Kernel]>."
exclude :test_initialize_copy, "TypeError expected but nothing was raised."
exclude :test_initialize_copy_empty, "TypeError expected but nothing was raised."
exclude :test_inspect_segfault, "<\"#<Method: A(ShallowInspect)#inspect(shallow_inspect)() -:10>\"> expected but was <\"#<Method: A(InspectIsShallow)#inspect() -:10>\">."
exclude :test_invalid_attr, "NameError expected but nothing was raised."
exclude :test_method_redefinition, "Expected /:1878: warning: method redefined; discarding old foo/ to match \"\"."
exclude :test_module_function_inside_method, "expected: /calling module_function without arguments inside a method may not have the intended effect/"
exclude :test_module_name_in_singleton_method, "Expected /::Foo$/ to match nil."
exclude :test_nested_defined, "Expected Object.const_defined?(\"TestModule::String\") to return false."
exclude :test_nested_defined_symbol, "NameError expected but nothing was raised."
exclude :test_nested_get, "NameError expected but nothing was raised."
exclude :test_prepend_after_include, "<[:m, :sc, :m, :c]> expected but was <[:sc, :m, :c]>."
exclude :test_prepend_each_classes, "should be able to prepend each classes."
exclude :test_prepend_module_ancestors, "<[m0, m1, m3, m0, m1]> expected but was <[m3, m0, m1]>."
exclude :test_prepend_private_super, "<no message> (java.lang.IndexOutOfBoundsException) from com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java:-1)"
exclude :test_private_constant_const_missing, "NameError: private constant #<Class:0x1f08>::FOO referenced"
exclude :test_private_constant_in_class, "Exception(NameError) with message matches to /#<Class:0x1f28>::FOO/."
exclude :test_private_constant_in_module, "<#<Module:0x1f58>> expected but was <#<Module:0x1f68>>."
exclude :test_private_constant_with_no_args, "needs investigation"
exclude :test_private_top_methods, ":include should be private."
exclude :test_protected_singleton_method, "NoMethodError expected but nothing was raised."
exclude :test_redefinition_mismatch, "Expected \"A is not a module\" to include \"/b/b/e/main/test/mri/tests/ruby/test_module.rb:3188: previous definition\"."
exclude :test_undef, "needs investigation"
