exclude :test_require_path_home_2, "pid 90932 exit 1"
exclude :test_race_exception, "Expected /circular require/ to match \"\"."
exclude :test_require_invalid_shared_object, "[LoadError] exception expected, not #<NameError: undefined local variable or method `dummy' for main:Object>."
exclude :test_require_to_path_redefined_in_load_path, "[ruby-core:47970]"
exclude :test_require_changed_home, "[ruby-core:47970]"
exclude :test_require_path_home_1, "pid 90994 exit 1"
exclude :test_relative_symlink_realpath, "bug17885 [ruby-core:104010]."
exclude :test_require_path_home_3, "pid 90997 exit 1"
exclude :test_require_too_long_filename, "Expected 2 to be <= 1."
exclude :test_require_to_str_redefined_in_load_path, "[ruby-core:47970]"
exclude :test_require_nonascii_path_shift_jis, "LoadError: cannot load such file -- enc/trans/single_byte"
exclude :test_load_ospath, "Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)"
exclude :test_loading_fifo_threading_raise, "Timeout::Error: execution of assert_separately expired (took longer than 9 seconds)"
exclude :test_loading_fifo_threading_success, "Timeout::Error: execution of assert_separately expired (took longer than 9 seconds)"
exclude :test_loading_fifo_fd_leak, "Timeout::Error: execution of assert_separately expired (took longer than 9 seconds)"
exclude :test_require_nonascii_path, "LoadError: cannot load such file -- enc/trans/single_byte"
