exclude :test_global_variables, "needs investigation"
exclude :test_special_constant_ivars, "needs investigation"
exclude :test_variable, "needs investigation"
exclude :test_setting_class_variable_on_module_through_inheritance, "needs investigation"
exclude :test_cvar_overtaken_by_module, "RuntimeError expected but nothing was raised."
exclude :test_cvar_overtaken_by_parent_class, "RuntimeError expected but nothing was raised."
