exclude :test_glob, "needs investigation"
exclude :test_chdir, "needs investigation"
exclude :test_glob_base, "needs investigation"
exclude :test_glob_base_dir, "needs investigation"
exclude :test_glob_cases, "fails on macOS in CI"
exclude :test_glob_gc_for_fd, "needs investigation"
exclude :test_glob_too_may_open_files, "needs investigation"
exclude :test_seek, "fails on macOS in CI"
exclude :test_unknown_keywords, "needs investigation"
exclude :test_chdir_conflict, "needs investigation"
exclude :test_foreach, "needs investigation"
exclude :test_glob_ignore_casefold_invalid_encoding, "Errno::EILSEQ: Invalid or incomplete multibyte or wide character - /Users/graal/slave/e/.tmp/__test_dir__20221104-21437-2t3gb2/�a123"
