exclude :test_else_without_rescue, "[\"/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb\", 21]."
exclude :test_error_def_in_argument, "-:7:in `<main>'."
exclude :test_error_line, "Message to pipe should end with a newline."
exclude :test_float, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:763:in `test_float'."
exclude :test_global_variable, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:774:in `test_global_variable'."
exclude :test_invalid_char, "| truffleruby: -e:1: Invalid char '\\x01' in expression (SyntaxError)"
exclude :test_location_of_invalid_token, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1192:in `test_location_of_invalid_token'."
exclude :test_magic_comment, "[ArgumentError] exception expected, not #<SyntaxError: /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:708: unknown or invalid encoding in the magic comment>."
exclude :test_method_block_location, "<923> expected but was <921>."
exclude :test_method_location_in_rescue, "<1075> expected but was <1082>."
exclude :test_question, "SyntaxError: (eval):1: cannot eval() a String with binary encoding, with no magic encoding comment and containing a non-US-ASCII character: \\xFF"
exclude :test_shareable_constant_value_nested, "SyntaxError: (eval):6: YARPTranslator does not know how to translate ShareableConstantNode at (eval):6"
exclude :test_shareable_constant_value_nonliteral, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_simple, "SyntaxError: (eval):3: YARPTranslator does not know how to translate ShareableConstantNode at (eval):3"
exclude :test_shareable_constant_value_unfrozen, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_unshareable_literal, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_string, "from the backslash through the invalid char."
exclude :test_truncated_source_line, "NoMethodError: undefined method `start_with?' for nil:NilClass"
exclude :test_unclosed_unicode_escape_at_eol_bug_19750, "-:7:in `<main>'."
exclude :test_unexpected_eof, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1188:in `test_unexpected_eof'."
exclude :test_unexpected_token_after_numeric, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1136:in `test_unexpected_token_after_numeric'."
exclude :test_unused_variable, "expected: /あ/"
exclude :test_utf8_bom, "Exception raised: <#<SyntaxError: (eval):1: cannot eval() a String with binary encoding, with no magic encoding comment and containing a non-US-ASCII character: \\xEF>>"
exclude :test_void_expr_stmts_value, "expected: /unused/"
exclude :test_yyerror_at_eol, "/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/test/mri/tests/ruby/test_parse.rb:1042:in `test_yyerror_at_eol'."
