exclude :"test_format_float(% #+-00.200e)", "needs investigation"
exclude :"test_format_float(% #+-00.e)", "needs investigation"
exclude :"test_format_float(% #+.9999f)", "needs investigation"
exclude :"test_format_float(% #.200e)", "needs investigation"
exclude :"test_format_float(% #0.20G)", "needs investigation"
exclude :"test_format_float(% #05.0g)", "needs investigation"
exclude :"test_format_float(% #5.f)", "needs investigation"
exclude :"test_format_float(% +0.20E)", "needs investigation"
exclude :"test_format_float(% +0.9999E)", "needs investigation"
exclude :"test_format_float(% -05.9999G)", "needs investigation"
exclude :"test_format_float(% -20.0E)", "needs investigation"
exclude :"test_format_float(% -20.20E)", "needs investigation"
exclude :"test_format_float(% -5.200g)", "needs investigation"
exclude :"test_format_float(% 0.8f)", "needs investigation"
exclude :"test_format_float(%#+-5.20f)", "needs investigation"
exclude :"test_format_float(%#+20.9999g)", "needs investigation"
exclude :"test_format_float(%#+20G)", "needs investigation"
exclude :"test_format_float(%#-.E)", "needs investigation"
exclude :"test_format_float(%#-0.9999E)", "needs investigation"
exclude :"test_format_float(%#-5.200E)", "needs investigation"
exclude :"test_format_float(%#00.0G)", "needs investigation"
exclude :"test_format_float(%#00.20g)", "needs investigation"
exclude :"test_format_float(%+-.8g)", "needs investigation"
exclude :"test_format_float(%+-0.0f)", "needs investigation"
exclude :"test_format_float(%+-05.20e)", "needs investigation"
exclude :"test_format_float(%+-5.8G)", "needs investigation"
exclude :"test_format_float(%+0.200E)", "needs investigation"
exclude :"test_format_float(%+0.200G)", "needs investigation"
exclude :"test_format_float(%+0.g)", "needs investigation"
exclude :"test_format_float(%+05.E)", "needs investigation"
exclude :"test_format_float(%-00.9999e)", "needs investigation"
exclude :"test_format_float(%-00f)", "needs investigation"
exclude :"test_format_float(%.20e)", "needs investigation"
exclude :"test_format_float(%020.200f)", "needs investigation"
exclude :"test_format_float(%020.e)", "needs investigation"
exclude :"test_format_float(%5.9999e)", "needs investigation"
exclude :"test_format_integer(% #+-0.8d)", "needs investigation"
exclude :"test_format_integer(% #+-0.B)", "needs investigation"
exclude :"test_format_integer(% #+-0.b)", "needs investigation"
exclude :"test_format_integer(% #+-0.d)", "needs investigation"
exclude :"test_format_integer(% #+-00.b)", "needs investigation"
exclude :"test_format_integer(% #+-020.8o)", "needs investigation"
exclude :"test_format_integer(% #+-0B)", "needs investigation"
exclude :"test_format_integer(% #+-20.8B)", "needs investigation"
exclude :"test_format_integer(% #+-20.8o)", "needs investigation"
exclude :"test_format_integer(% #+-20.X)", "needs investigation"
exclude :"test_format_integer(% +00.0b)", "needs investigation"
exclude :"test_format_integer(% +00.0o)", "needs investigation"
exclude :"test_format_integer(% +020.0x)", "needs investigation"
exclude :"test_format_integer(%#-0.8o)", "needs investigation"
exclude :"test_format_integer(%#-0.b)", "needs investigation"
exclude :"test_format_integer(%#-0.o)", "needs investigation"
exclude :"test_format_integer(%#-05.8b)", "needs investigation"
exclude :"test_format_integer(%#-05.x)", "needs investigation"
exclude :"test_format_integer(%#-05o)", "needs investigation"
exclude :"test_format_integer(%#-0b)", "needs investigation"
exclude :"test_format_integer(%.0X)", "needs investigation"
exclude :"test_format_integer(%.0d)", "needs investigation"
exclude :"test_format_integer(%.20B)", "needs investigation"
exclude :"test_format_integer(%05.0d)", "needs investigation"
exclude :"test_format_integer(%0B)", "needs investigation"
exclude :"test_format_integer(%5.0B)", "needs investigation"
exclude :"test_format_integer(%5.0d)", "needs investigation"
exclude :"test_format_integer(%B)", "needs investigation"
