exclude :test_continue, "undefined symbol: rb_hash_tbl"
exclude :test_delete, "undefined symbol: rb_hash_tbl"
exclude :test_notfound, "undefined symbol: rb_hash_tbl"
exclude :test_pass_objects_in_st_table, "undefined symbol: rb_hash_tbl"
exclude :test_update, "undefined symbol: rb_hash_tbl"
