exclude :test_gc_auto_compact_get_not_implemented, "NameError: uninitialized constant GC::OPTS"
exclude :test_gc_auto_compact_set_not_implemented, "NameError: uninitialized constant GC::OPTS"
exclude :test_gc_compact_not_implemented, "NameError: uninitialized constant GC::OPTS"
exclude :test_gc_latest_compact_info_not_implemented, "NameError: uninitialized constant GC::OPTS"
exclude :test_gc_verify_compaction_references_not_implemented, "NameError: uninitialized constant GC::OPTS"
