# <!-- rdoc-file=lib/rubygems.rb -->
# TruffleRuby >= 24 defines REUSE_AS_BINARY_ON_TRUFFLERUBY in
# defaults/truffleruby. However, TruffleRuby < 24 defines
# REUSE_AS_BINARY_ON_TRUFFLERUBY directly in its copy of
# lib/rubygems/platform.rb, so it is not defined if RubyGems is updated (gem
# update --system). Instead, we define it here in that case, similar to
# bundler/lib/bundler/rubygems_ext.rb. We must define it here and not in
# platform.rb because platform.rb is loaded before defaults/truffleruby.
#
# <!-- rdoc-file=lib/rubygems/platform.rb -->
# Available list of platforms for targeting Gem installations.
#
# See `gem help platform` for information on platform matching.
#
class Gem::Platform
end
