Q$(MX_VERBOSE) = @
MKMF_MAKEFILE_SUBPROCESS_FLAGS = $(MX_VERBOSE:y=V=1)

OS := $(shell uname)
ifeq ($(OS),Darwin)
SOEXT := dylib
DLEXT := bundle
else
SOEXT := so
DLEXT := so
endif

ifndef MX_HOME
$(error This Makefile should be called from mx)
endif

ROOT := $(realpath ../../..)
RUBY := $(TRUFFLERUBY_BOOTSTRAP_LAUNCHER)

TRUFFLE_POSIX := truffleposix/libtruffleposix.$(SOEXT)
SPAWN_HELPER := spawn-helper/spawn-helper

RUBY_HEADERS := $(shell find $(ROOT)/lib/cext/include -name '*.h')
ABI_VERSION := $(ROOT)/lib/cext/ABI_version.txt
RBCONFIG := $(ROOT)/lib/truffle/rbconfig.rb
MKMF := $(ROOT)/lib/mri/mkmf.rb
LIBTRUFFLERUBY = cext/libtruffleruby.$(SOEXT)
BASIC_EXTCONF_DEPS := Makefile $(SPAWN_HELPER) $(TRUFFLE_POSIX) $(RUBY_HEADERS) $(ABI_VERSION) $(RBCONFIG) $(MKMF)
# C extensions link against libtruffleruby (and might do have_func() checks against it), so it needs to be there before.
# However, if libtruffleruby is recompiled, there is no need to rebuild C extensions, so it's a order-only-prerequisite.
EXTCONF_DEPS := $(BASIC_EXTCONF_DEPS) | $(LIBTRUFFLERUBY)

DEBUG_GEM := $(ROOT)/lib/gems/gems/debug-1.6.3
DEBUG_GEM_EXT := $(DEBUG_GEM)/ext/debug
DEBUG_GEM_EXT_SO := $(DEBUG_GEM_EXT)/debug.$(DLEXT)
DEBUG_GEM_LIB_SO := $(DEBUG_GEM)/lib/debug/debug.$(DLEXT)

RBS_GEM := $(ROOT)/lib/gems/gems/rbs-2.7.0
RBS_GEM_EXT := $(RBS_GEM)/ext/rbs_extension
RBS_GEM_EXT_SO := $(RBS_GEM_EXT)/rbs_extension.$(DLEXT)
RBS_GEM_LIB_SO := $(RBS_GEM)/lib/rbs_extension.$(DLEXT)

IF_EXTCONF_FAIL := ( echo "`pwd`/extconf.rb failed:" 1>&2 && cat mkmf.log && false )

all: $(LIBTRUFFLERUBY) openssl/openssl.$(DLEXT) zlib/zlib.$(DLEXT) \
			psych/psych.$(DLEXT) ripper/ripper.$(DLEXT) syslog/syslog.$(DLEXT) nkf/nkf.$(DLEXT) \
			bigdecimal/bigdecimal.$(DLEXT) date/date_core.$(DLEXT) io-console/console.$(DLEXT) etc/etc.$(DLEXT) \
			rbconfig-sizeof/sizeof.$(DLEXT) $(DEBUG_GEM_LIB_SO) $(RBS_GEM_LIB_SO)

clean: clean_cexts clean_truffleposix

clean_truffleposix:
	$(Q) rm -f $(TRUFFLE_POSIX) truffleposix/*.o

clean_cexts:
	$(Q) rm -f cext/Makefile cext/*.o $(LIBTRUFFLERUBY)
	$(Q) rm -f openssl/Makefile openssl/*.o openssl/openssl.$(DLEXT) openssl/extconf.h
	$(Q) rm -f zlib/Makefile zlib/*.o zlib/zlib.$(DLEXT)
	$(Q) rm -f psych/Makefile psych/*.o psych/yaml/*.o psych/psych.$(DLEXT)
	$(Q) rm -f ripper/Makefile ripper/*.o ripper/ripper.$(DLEXT)
	$(Q) rm -f syslog/Makefile syslog/*.o syslog/syslog.$(DLEXT)
	$(Q) rm -f nkf/Makefile nkf/*.o nkf/nkf.$(DLEXT)
	$(Q) rm -f bigdecimal/Makefile bigdecimal/*.o bigdecimal/bigdecimal.$(DLEXT)
	$(Q) rm -f date/Makefile date/*.o date/date_core.$(DLEXT)
	$(Q) rm -f io-console/Makefile io-console/*.o io-console/console.$(DLEXT)
	$(Q) rm -f etc/Makefile etc/*.o etc/etc.$(DLEXT) etc/constdefs.h
	$(Q) rm -f rbconfig-sizeof/Makefile rbconfig-sizeof/*.o rbconfig-sizeof/sizeof.$(DLEXT)
	$(Q) rm -f $(DEBUG_GEM_EXT)/Makefile $(DEBUG_GEM_EXT)/*.o $(DEBUG_GEM_EXT_SO) $(DEBUG_GEM_LIB_SO)
	$(Q) rm -f $(RBS_GEM_EXT)/Makefile $(RBS_GEM_EXT)/*.o $(RBS_GEM_EXT_SO) $(RBS_GEM_LIB_SO)

# spawn-helper
$(SPAWN_HELPER): spawn-helper/Makefile spawn-helper/spawn-helper.c
	$(Q) cd spawn-helper && $(MAKE)

# truffleposix
$(TRUFFLE_POSIX): truffleposix/Makefile truffleposix/truffleposix.c
	$(Q) cd truffleposix && $(MAKE)

# libtruffleruby
cext/Makefile: cext/extconf.rb $(BASIC_EXTCONF_DEPS)
	$(Q) cd cext && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

$(LIBTRUFFLERUBY): cext/Makefile cext/*.c cext/*.h
	$(Q) cd cext && $(MAKE)

# openssl
openssl/Makefile: openssl/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd openssl && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

openssl/openssl.$(DLEXT): openssl/Makefile openssl/*.c openssl/*.h
	$(Q) cd openssl && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# zlib
zlib/Makefile: zlib/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd zlib && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

zlib/zlib.$(DLEXT): zlib/Makefile zlib/zlib.c
	$(Q) cd zlib && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# ripper
ripper/Makefile: ripper/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd ripper && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

ripper/ripper.$(DLEXT): ripper/Makefile ripper/*.c ripper/*.h
	$(Q) cd ripper && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# syslog
syslog/Makefile: syslog/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd syslog && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

syslog/syslog.$(DLEXT): syslog/Makefile syslog/syslog.c
	$(Q) cd syslog && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# nkf
nkf/Makefile: nkf/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd nkf && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

nkf/nkf.$(DLEXT): nkf/Makefile nkf/nkf.c nkf/nkf-utf8/*.c nkf/nkf-utf8/*.h
	$(Q) cd nkf && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# bigdecimal
bigdecimal/Makefile: bigdecimal/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd bigdecimal && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

bigdecimal/bigdecimal.$(DLEXT): bigdecimal/Makefile bigdecimal/bigdecimal.c
	$(Q) cd bigdecimal && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# date
date/Makefile: date/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd date && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

date/date_core.$(DLEXT): date/Makefile date/*.c date/*.h
	$(Q) cd date && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# io-console
io-console/Makefile: io-console/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd io-console && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

io-console/console.$(DLEXT): io-console/Makefile io-console/*.c
	$(Q) cd io-console && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# etc
etc/Makefile: etc/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd etc && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

etc/constdefs.h: etc/mkconstants.rb $(EXTCONF_DEPS)
	$(Q) $(RUBY) $< -o $@

etc/etc.c: etc/constdefs.h

etc/etc.$(DLEXT): etc/Makefile etc/etc.c
	$(Q) cd etc && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# rbconfig/sizeof
rbconfig-sizeof/Makefile: rbconfig-sizeof/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd rbconfig-sizeof && $(RUBY) -rmkmf extconf.rb || $(IF_EXTCONF_FAIL)

rbconfig-sizeof/sizeof.$(DLEXT): rbconfig-sizeof/Makefile rbconfig-sizeof/sizes.c
	$(Q) cd rbconfig-sizeof && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# psych
# Always use the bundled libyaml, as we want it as bitcode and avoid extra handles
psych/Makefile: psych/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd psych && $(RUBY) extconf.rb --enable-bundled-libyaml || $(IF_EXTCONF_FAIL)

psych/psych.$(DLEXT): psych/Makefile psych/*.c psych/*.h psych/yaml/*.c psych/yaml/*.h
	$(Q) cd psych && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

# debug bundled gem
$(DEBUG_GEM_EXT)/Makefile: $(DEBUG_GEM_EXT)/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd $(DEBUG_GEM_EXT) && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

$(DEBUG_GEM_EXT_SO): $(DEBUG_GEM_EXT)/Makefile $(DEBUG_GEM_EXT)/*.c $(DEBUG_GEM_EXT)/*.h
	$(Q) cd $(DEBUG_GEM_EXT) && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

$(DEBUG_GEM_LIB_SO): $(DEBUG_GEM_EXT_SO)
	$(Q) cp $< $@
	$(Q) $(RUBY) $(ROOT)/tool/mark-gem-extension-as-built.rb debug

# rbs bundled gem
$(RBS_GEM_EXT)/Makefile: $(RBS_GEM_EXT)/extconf.rb $(EXTCONF_DEPS)
	$(Q) cd $(RBS_GEM_EXT) && $(RUBY) extconf.rb || $(IF_EXTCONF_FAIL)

$(RBS_GEM_EXT_SO): $(RBS_GEM_EXT)/Makefile $(RBS_GEM_EXT)/*.c $(RBS_GEM_EXT)/*.h
	$(Q) cd $(RBS_GEM_EXT) && $(MAKE) $(MKMF_MAKEFILE_SUBPROCESS_FLAGS)

$(RBS_GEM_LIB_SO): $(RBS_GEM_EXT_SO)
	$(Q) cp $< $@
	$(Q) $(RUBY) $(ROOT)/tool/mark-gem-extension-as-built.rb rbs
