name: 'Extract TruffleRuby, add bin/ to PATH and set RUBY_BIN'
inputs:
  archive:
    description: 'basename of the archive'
    required: true
    default: 'truffleruby-jvm'
runs:
  using: "composite"
  steps:
    - name: Extract the archive to truffleruby-build
      run: tar xf ${{ inputs.archive }}.tar.gz && mv ${{ inputs.archive }} truffleruby-build
      shell: bash

    - name: Add TruffleRuby bin/ to PATH
      run: echo "$PWD/truffleruby-build/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set RUBY_BIN for jt
      run: echo "RUBY_BIN=$PWD/truffleruby-build/bin/truffleruby" >> $GITHUB_ENV
      shell: bash
