exclude :test_atom_category, "needs investigation"
exclude :test_atom_content, "needs investigation"
exclude :test_atom_generator, "needs investigation"
exclude :test_atom_link, "needs investigation"
exclude :test_atom_rights, "needs investigation"
exclude :test_atom_subtitle, "needs investigation"
exclude :test_atom_summary, "needs investigation"
exclude :test_atom_title, "needs investigation"
