exclude :test_attrset_id, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_nonascii, "needs investigation"
exclude :test_redefinition_warning, "needs investigation"
exclude :test_struct_new_with_empty_hash, "needs investigation"
exclude :test_parameters, "<[[:req, :_]]> expected but was"
exclude :test_keyword_args_warning, "<{:a=>1}> expected but was"
