exclude :test_aref, "needs investigation"
exclude :test_aset, "needs investigation"
exclude :test_attrset_id, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_nonascii, "needs investigation"
exclude :test_redefinition_warning, "needs investigation"
exclude :test_struct_new_with_keyword_init, "needs investigation"
