exclude :test_attrset_id, "needs investigation"
exclude :test_inspect, "needs investigation"
exclude :test_nonascii, "needs investigation"
exclude :test_redefinition_warning, "needs investigation"
exclude :test_struct_new_with_empty_hash, "needs investigation"
exclude :test_struct_keyword_init_p, "NoMethodError: undefined method `keyword_init?' for #<Class:0xc3f888>(keyword_init: true)"
