exclude :"test_marshal_compatibility@Africa/Ndjamena", "needs investigation"
exclude :"test_marshal_compatibility@America/Los_Angeles", "needs investigation"
exclude :"test_marshal_compatibility@Asia/Tokyo", "needs investigation"
exclude :"test_at@Africa/Ndjamena", "needs investigation"
exclude :"test_at@America/Los_Angeles", "needs investigation"
exclude :"test_at@Asia/Tokyo", "needs investigation"
exclude :"test_dst?@Africa/Ndjamena", "needs investigation"
exclude :"test_dst?@America/Los_Angeles", "needs investigation"
exclude :"test_dst?@Asia/Tokyo", "needs investigation"
exclude :test_fractional_second, "needs investigation"
exclude :"test_getlocal@Africa/Ndjamena", "needs investigation"
exclude :"test_getlocal@America/Los_Angeles", "needs investigation"
exclude :"test_getlocal@Asia/Tokyo", "needs investigation"
exclude :"test_marshal@Africa/Ndjamena", "needs investigation"
exclude :"test_marshal@America/Los_Angeles", "needs investigation"
exclude :"test_marshal@Asia/Tokyo", "needs investigation"
exclude :"test_new@Africa/Ndjamena", "needs investigation"
exclude :"test_new@America/Los_Angeles", "needs investigation"
exclude :"test_new@Asia/Tokyo", "needs investigation"
exclude :"test_now@Africa/Ndjamena", "needs investigation"
exclude :"test_now@America/Los_Angeles", "needs investigation"
exclude :"test_now@Asia/Tokyo", "needs investigation"
exclude :"test_plus@Africa/Ndjamena", "needs investigation"
exclude :"test_plus@America/Los_Angeles", "needs investigation"
exclude :"test_plus@Asia/Tokyo", "needs investigation"
exclude :"test_strftime@Africa/Ndjamena", "needs investigation"
exclude :"test_strftime@America/Los_Angeles", "needs investigation"
exclude :"test_strftime@Asia/Tokyo", "needs investigation"
exclude :"test_to_a@Africa/Ndjamena", "needs investigation"
exclude :"test_to_a@America/Los_Angeles", "needs investigation"
exclude :"test_to_a@Asia/Tokyo", "needs investigation"
exclude :"test_hour24@America/Los_Angeles", "NoMethodError: undefined method `name' for \"UTC\":String"
exclude :"test_hour24@Asia/Tokyo", "NoMethodError: undefined method `name' for \"UTC\":String"
exclude :"test_hour24@Africa/Ndjamena", "NoMethodError: undefined method `name' for \"UTC\":String"
