exclude :"test_find_proxy", "needs investigation"
exclude :"test_find_proxy_case_sensitive_env", "needs investigation"
exclude :test_find_proxy_bad_value, "needs investigation"
exclude :test_find_proxy_no_env, "needs investigation"
exclude :test_find_proxy_no_proxy, "needs investigation"
