exclude :test_1_2_3, "<[[\"expected a newline or semicolon after the statement\", 2..2],"
exclude :test_aliasing_global_variable_with_global_number_variable, "<[[\"invalid argument being passed to `alias`; expected a bare word, symbol, constant, or global variable\","
exclude :test_alnum_delimiters, "<[\"invalid `%` token\"]> expected but was <[\"unknown type of %string\"]>."
exclude :test_argument_forwarding_only_effects_its_own_internals, "<[[\"unexpected `...` when the parent method is not forwarding\", 43..46]]> expected but was <[[\"unexpected ... when the parent method is not forwarding\", 43..46]]>."
exclude :test_argument_forwarding_when_parent_is_not_forwarding, "<[[\"unexpected `...` when the parent method is not forwarding\", 18..21]]> expected but was <[[\"unexpected ... when the parent method is not forwarding\", 18..21]]>."
exclude :test_arguments_after_block, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x1238>"
exclude :test_arguments_binding_power_for_and, "<[\"expected a `)` to close the arguments\","
exclude :test_bad_arguments, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x14e8>"
exclude :test_binary_range_with_left_unary_range, "<[[\"expected a newline or semicolon after the statement\", 3..3],"
exclude :test_block_beginning_with_brace_and_ending_with_end, "<[\"expected a newline or semicolon after the statement\","
exclude :test_break_1, "<[[\"expected an argument\", 8..8]]> expected but was <[[\"unexpected ';'; expected an argument\", 8..9], [\"Invalid break\", 0..8]]>."
exclude :test_break_1_2_3, "<[[\"expected a newline or semicolon after the statement\", 7..7],"
exclude :test_cannot_assign_to_a_reserved_numbered_parameter, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x1d68>"
exclude :test_case_without_clauses, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x1da8>"
exclude :test_case_without_when_clauses_errors_on_else_clause, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x1de8>"
exclude :test_check_value_expression, "<[[\"unexpected void value expression\", 7..13],"
exclude :test_circular_param, "<[[\"parameter default value references itself\", 14..17],"
exclude :test_class_definition_in_method_body, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x2368>"
exclude :test_class_definition_in_method_defs, "<[[\"unexpected class definition in a method definition\", 14..19],"
exclude :test_class_name, "<[[\"expected a constant name after `class`\", 6..9]]> expected but was <[[\"unexpected constant path after `class`; class/module name must be CONSTANT\","
exclude :test_constant_path_with_invalid_token_after, "<[\"expected a constant after the `::` operator\","
exclude :test_cr_without_lf_in_percent_expression, "<[[\"invalid `%` token\", 0..2]]> expected but was <[[\"unterminated string meets end of file\", 2..2]]>."
exclude :test_def_with_empty_expression_receiver, "<[[\"expected a receiver for the method definition\", 5..5]]> expected but was <[[\"expected a receiver for the method definition\", 4..5]]>."
exclude :test_def_with_expression_receiver_and_no_identifier, "<[[\"expected a `.` or `::` after the receiver in a method definition\", 7..7],"
exclude :test_def_with_multiple_statements_receiver, "<[[\"expected a matching `)`\", 7..7],"
exclude :test_do_not_allow_characters_other_than_0_9_a_f_and_A_F_in_u_Unicode_character_notation, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x43a8>"
exclude :test_do_not_allow_forward_arguments_in_blocks, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x43e8>"
exclude :test_do_not_allow_forward_arguments_in_lambda_literals, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4428>"
exclude :test_do_not_allow_more_than_6_hexadecimal_digits_in_u_Unicode_character_notation, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4468>"
exclude :test_do_not_allow_multiple_codepoints_in_a_single_character_literal, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x44a8>"
exclude :test_do_not_allow_trailing_commas_in_lambda_parameters, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x44e8>"
exclude :test_do_not_allow_trailing_commas_in_method_parameters, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4528>"
exclude :test_dont_allow_return_inside_class_body, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4568>"
exclude :test_dont_allow_return_inside_module_body, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x45a8>"
exclude :test_dont_allow_setting_to_back_and_nth_reference, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x45e8>"
exclude :test_double_arguments_forwarding, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4628>"
exclude :test_double_scope_numbered_parameters, "<[[\"numbered parameter is already used in outer scope\", 15..17]]> expected but was <[[\"numbered parameter is already used in outer block\", 15..17]]>."
exclude :test_double_splat_followed_by_splat_argument, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4828>"
exclude :test_duplicated_parameter_names, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x4868>"
exclude :test_for_loops_index_missing, "NoMethodError: undefined method `MissingNode' for #<Prism::ErrorsTest:0x4a28>"
exclude :test_for_loops_only_end, "NoMethodError: undefined method `MissingNode' for #<Prism::ErrorsTest:0x4a68>"
exclude :test_forwarding_arg_after_keyword_rest, "<[[\"unexpected `...` in parameters\", 9..12]]> expected but was <[[\"unexpected parameter order\", 9..12]]>."
exclude :test_incomplete_instance_var_string, "<[[\"incomplete instance variable\", 4..5],"
exclude :test_invalid_global_variable_write, "<[[\"immutable variable as a write target\", 0..2],"
exclude :test_invalid_hex_escape, "<[[\"invalid hexadecimal escape sequence\", 1..3]]> expected but was <[[\"invalid hex escape sequence\", 1..3]]>."
exclude :test_invalid_multi_target, "<[\"immutable variable as a write target\", \"unexpected write target\"]> expected but was <[\"Can't set variable $1\", \"unexpected write target\"]>."
exclude :test_invalid_number_underscores, "<[\"invalid underscore placement in number\"]> expected but was <[\"trailing '_' in number\"]>."
exclude :test_keywords_parameters_before_required_parameters, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x56d8>"
exclude :test_match_plus, "<[[\"expected a newline or semicolon after the statement\", 6..6],"
exclude :test_method_parameters_after_arguments_forwarding, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x59a8>"
exclude :test_method_parameters_after_block, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x59e8>"
exclude :test_method_with_arguments_after_anonymous_block, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x5a28>"
exclude :test_missing_terminator_in_parentheses, "<[\"expected a newline or semicolon after the statement\"]> expected but was <[\"unexpected integer, expecting end-of-input\"]>."
exclude :test_module_definition_in_method_body, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x5ac8>"
exclude :test_module_definition_in_method_body_within_block, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x5b08>"
exclude :test_module_definition_in_method_defs, "<[[\"unexpected module definition in a method definition\", 14..20],"
exclude :test_module_name_recoverable, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x5d08>"
exclude :test_multiple_error_in_parameters_order, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x5d48>"
exclude :test_next_1, "<[[\"expected an argument\", 7..7]]> expected but was <[[\"unexpected ';'; expected an argument\", 7..8], [\"Invalid next\", 0..7]]>."
exclude :test_next_1_2_3, "<[[\"expected a newline or semicolon after the statement\", 6..6],"
exclude :test_non_assoc_equality, "<[[\"expected a newline or semicolon after the statement\", 6..6],"
exclude :test_non_assoc_range, "<[[\"expected a newline or semicolon after the statement\", 4..4],"
exclude :test_pre_execution_context, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x66a8>"
exclude :test_pre_execution_missing_brace, "NoMethodError: undefined method `StatementsNode' for #<Prism::ErrorsTest:0x6708>"
exclude :test_rational_number_with_exponential_portion, "<[[\"expected a newline or semicolon after the statement\", 3..3],"
exclude :test_repeated_parameter_name_in_destructured_params, "<[[\"repeated parameter name\", 14..15]]> expected but was <[[\"duplicated argument name\", 14..15]]>."
exclude :test_rest_keywords_parameters_before_required_parameters, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x6d48>"
exclude :test_return_1, "<[[\"expected an argument\", 9..9]]> expected but was <[[\"unexpected ';'; expected an argument\", 9..10]]>."
exclude :test_return_1_2_3, "<[\"expected a newline or semicolon after the statement\","
exclude :test_returning_to_optional_parameters_multiple_times, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x6f48>"
exclude :test_setter_method_cannot_be_defined_in_an_endless_method_definition, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x7068>"
exclude :test_shadow_args_in_block, "<[[\"repeated parameter name\", 7..8]]> expected but was <[[\"duplicated argument name\", 7..8]]>."
exclude :test_shadow_args_in_lambda, "<[[\"expected a `do` keyword or a `{` to open the lambda block\", 3..3],"
exclude :test_splat_argument_after_keyword_argument, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x7418>"
exclude :test_statement_operators, "<[[\"expected a newline or semicolon after the statement\", 9..9],"
exclude :test_switching_to_named_arguments_twice, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x7948>"
exclude :test_switching_to_optional_arguments_twice, "NoMethodError: undefined method `Location' for #<Prism::ErrorsTest:0x7988>"
exclude :test_symbol_in_hash, "<[[\"expected a closing delimiter for the string literal\", 7..7]]> expected but was <[[\"unexpected label\", 3..7]]>."
exclude :test_symbol_in_keyword_parameter, "<[[\"expected a closing delimiter for the string literal\", 14..14]]> expected but was <[[\"unexpected label\", 10..14]]>."
exclude :test_top_level_constant_starting_with_downcased_identifier, "<[\"expected a constant after the `::` operator\","
exclude :test_top_level_constant_with_downcased_identifier, "<[\"expected a constant after the `::` operator\","
exclude :test_trailing_comma_in_calls, "<[[\"expected an argument\", 5..6]]> expected but was <[[\"unexpected end-of-input; expected an argument\", 5..6]]>."
exclude :test_unterminated_W_list, "<[[\"expected a closing delimiter for the `%W` list\", 0..3]]> expected but was <[[\"unterminated list; expected a closing delimiter for the `%W`\", 0..3]]>."
exclude :test_unterminated_argument_expression, "<[[\"invalid `%` token\", 2..3],"
exclude :test_unterminated_embdoc, "<[[\"could not find a terminator for the embedded document\", 2..9]]> expected but was <[[\"embedded document meets end of file\", 2..9]]>."
exclude :test_unterminated_empty_string, "<[[\"expected a closing delimiter for the string literal\", 1..1]]> expected but was <[[\"unterminated string meets end of file\", 1..1]]>."
exclude :test_unterminated_global_variable, "<[[\"invalid global variable\", 0..1]]> expected but was <[[\"'$' without identifiers is not allowed as a global variable name\", 0..1]]>."
exclude :test_unterminated_i_list, "<[[\"expected a closing delimiter for the `%i` list\", 0..3]]> expected but was <[[\"unterminated list; expected a closing delimiter for the `%i`\", 0..3]]>."
exclude :test_unterminated_interpolated_string, "<[[\"expected a closing delimiter for the string literal\", 6..6]]> expected but was <[[\"unterminated string meets end of file\", 6..6]]>."
exclude :test_unterminated_interpolated_symbol, "<[\"expected a closing delimiter for the interpolated symbol\"]> expected but was <[\"unterminated symbol; expected a closing delimiter for the interpolated symbol\"]>."
exclude :test_unterminated_parenthesized_expression, "<[[\"expected a newline or semicolon after the statement\", 6..6],"
exclude :test_unterminated_regular_expression, "<[[\"expected a closing delimiter for the regular expression\", 0..1]]> expected but was <[[\"unterminated regexp meets end of file; expected a closing delimiter\", 0..1]]>."
exclude :test_unterminated_regular_expression_with_heredoc, "<[[\"expected a closing delimiter for the regular expression\", 9..10]]> expected but was <[[\"unterminated regexp meets end of file; expected a closing delimiter\","
exclude :test_unterminated_s_symbol, "<[[\"expected a closing delimiter for the dynamic symbol\", 0..3]]> expected but was <[[\"unterminated quoted string; expected a closing delimiter for the dynamic symbol\","
exclude :test_unterminated_string, "<[[\"expected a closing delimiter for the string literal\", 0..1]]> expected but was <[[\"unterminated string meets end of file\", 0..1]]>."
exclude :test_unterminated_unicode_brackets_should_be_a_syntax_error, "<[[\"invalid Unicode escape sequence; needs closing `}`\", 1..5]]> expected but was <[[\"invalid Unicode list: \\\\u{3\", 1..5]]>."
exclude :test_unterminated_w_list, "<[[\"expected a closing delimiter for the `%w` list\", 0..3]]> expected but was <[[\"unterminated list; expected a closing delimiter for the `%w`\", 0..3]]>."
exclude :test_while_endless_method, "<[[\"expected a predicate expression for the `while` statement\", 22..22],"
