exclude :test_BeginNode, "<10> expected but was <0>."
exclude :test_BreakNode, "<[]> expected but was <[#<Prism::ParseError @type=:invalid_block_exit @message=\"Invalid break\" @location=#<Prism::Location @start_offset=0 @length=5 start_line=1> @level=:syntax>]>."
exclude :test_IndexTargetNode, "<[]> expected but was <[#<Prism::ParseError @type=:unexpected_index_block @message=\"unexpected block arg given in index assignment; blocks are not allowed in index assignment expressions\" @location=#<Prism::Location @start_offset=9 @length=4 start_line=1> @level=:syntax>]>."
exclude :test_NextNode, "<[]> expected but was <[#<Prism::ParseError @type=:invalid_block_exit @message=\"Invalid next\" @location=#<Prism::Location @start_offset=0 @length=4 start_line=1> @level=:syntax>]>."
exclude :test_PinnedVariableNode, "<[]> expected but was <[#<Prism::ParseError @type=:no_local_variable @message=\"bar: no such local variable\" @location=#<Prism::Location @start_offset=8 @length=3 start_line=1> @level=:syntax>]>."
exclude :test_RedoNode, "<[]> expected but was <[#<Prism::ParseError @type=:invalid_block_exit @message=\"Invalid redo\" @location=#<Prism::Location @start_offset=0 @length=4 start_line=1> @level=:syntax>]>."
exclude :test_RetryNode, "<[]> expected but was <[#<Prism::ParseError @type=:invalid_retry_without_rescue @message=\"Invalid retry without rescue\" @location=#<Prism::Location @start_offset=0 @length=5 start_line=1> @level=:syntax>]>."
exclude :test_YieldNode, "<[]> expected but was <[#<Prism::ParseError @type=:invalid_yield @message=\"Invalid yield\" @location=#<Prism::Location @start_offset=0 @length=5 start_line=1> @level=:syntax>]>."
exclude :test_all_tested, "<[:AliasGlobalVariableNode,"
