exclude :"test_magic_comment_#  \\t\\v encoding  \\t\\v :  \\t\\v ascii  \\t\\v", "dyld: missing symbol called"
exclude :"test_magic_comment_#  \t\v encoding  \t\v :  \t\v ascii  \t\v", "dyld: missing symbol called"
exclude :"test_magic_comment_# -*-  \t\v encoding  \t\v :  \t\v ascii  \t\v -*-", "dyld: missing symbol called"
exclude :"test_magic_comment_# -*- CoDiNg: ascii -*-", "dyld: missing symbol called"
exclude :"test_magic_comment_# -*- coding: ascii -*-", "dyld: missing symbol called"
exclude :"test_magic_comment_# -*- eNcOdInG: ascii -*-", "dyld: missing symbol called"
exclude :"test_magic_comment_# -*- encoding: ascii -*-", "dyld: missing symbol called"
exclude :"test_magic_comment_# -*- foo: bar; encoding: ascii -*-", "dyld: missing symbol called"
exclude :"test_magic_comment_# CoDiNg: ascii", "dyld: missing symbol called"
exclude :"test_magic_comment_# coding \t \r  \v   :     \t \v    \r   ascii-8bit", "dyld: missing symbol called"
exclude :"test_magic_comment_# coding: ascii", "dyld: missing symbol called"
exclude :"test_magic_comment_# eNcOdInG: ascii", "dyld: missing symbol called"
exclude :"test_magic_comment_# encoding: ascii", "dyld: missing symbol called"
exclude :"test_magic_comment_# vim: filetype=ruby, fileencoding=big5, tabsize=3, shiftwidth=3", "dyld: missing symbol called"
