exclude :"test_emoji_method_calls.txt", "<[:program,"
exclude :"test_for.txt", "<nil> expected but was <[:program,"
exclude :"test_keyword_method_names.txt", "<nil> expected but was <[:program,"
exclude :"test_newline_terminated.txt", "dyld: missing symbol called"
exclude :"test_regex_escape_encoding.txt", "dyld: missing symbol called"
exclude :"test_seattlerb/block_kw.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/block_kw__required.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/bug_args_masgn_outer_parens__19.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/defn_opt_last_arg.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/f_kw.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/f_kw__required.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/magic_encoding_comment.txt", "dyld: missing symbol called"
exclude :"test_seattlerb/rhs_asgn.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/stabby_block_kw.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/stabby_block_kw__required.txt", "<nil> expected but was <[:program,"
exclude :"test_seattlerb/utf8_bom.txt", "dyld: missing symbol called"
exclude :"test_symbols.txt", "<[:program,"
exclude :"test_whitequark/bug_447.txt", "<nil> expected but was <[:program,"
exclude :"test_whitequark/bug_ascii_8bit_in_literal.txt", "dyld: missing symbol called"
exclude :"test_whitequark/endless_method_with_rescue_mod.txt", "<nil> expected but was <[:program,"
exclude :"test_whitequark/numparam_outside_block.txt", "<nil> expected but was <[:program,"
exclude :"test_whitequark/parser_bug_490.txt", "<nil> expected but was <[:program,"
exclude :"test_whitequark/parser_bug_507.txt", "<nil> expected but was <[:program,"
exclude :"test_whitequark/ruby_bug_10653.txt", "<nil> expected but was <[:program,"
