exclude :test_io, "needs investigation"
exclude :test_sizeof, "needs investigation"
exclude :test_strcpy, "needs investigation"
exclude :test_struct, "needs investigation"
exclude :test_unsigned_result, "needs investigation"
exclude :test_value, "needs investigation"
