exclude :test_aref_aset, "NoMethodError: undefined method `string_pointer_to_native' for Truffle::CExt:Module"
exclude :test_can_read_write_memory, "NoMethodError: undefined method `write' for Fiddle::Pointer:Class"
exclude :test_cmp, "NotImplementedError: NotImplementedError"
exclude :test_cptr_to_int, "NameError: uninitialized constant Fiddle::NULL"
exclude :test_equals, "NotImplementedError: NotImplementedError"
exclude :test_free, "NotImplementedError: NotImplementedError"
exclude :test_free=, "NotImplementedError: NotImplementedError"
exclude :test_free_with_func, "NotImplementedError: NotImplementedError"
exclude :test_free_with_no_func, "NotImplementedError: NotImplementedError"
exclude :test_freed?, "NotImplementedError: NotImplementedError"
exclude :test_inspect, "NotImplementedError: NotImplementedError"
exclude :test_malloc_block, "NotImplementedError: NotImplementedError"
exclude :test_malloc_block_no_free, "[ArgumentError] exception expected, not #<NotImplementedError: NotImplementedError>."
exclude :test_malloc_free_func, "NotImplementedError: NotImplementedError"
exclude :test_malloc_free_func_int, "<0> expected but was <140149941148512>."
exclude :test_malloc_subclass, "NotImplementedError: NotImplementedError"
exclude :test_minus, "NoMethodError: undefined method `string_pointer_to_native' for Truffle::CExt:Module"
exclude :test_not_equals, "NotImplementedError: NotImplementedError"
exclude :test_null?, "NotImplementedError: NotImplementedError"
exclude :test_null_pointer, "[Fiddle::DLError] exception expected, not #<Truffle::FFI::NullPointerError: invalid memory access at address=0x0>."
exclude :test_plus, "NoMethodError: undefined method `string_pointer_to_native' for Truffle::CExt:Module"
exclude :test_ref_ptr, "NotImplementedError: NotImplementedError"
exclude :test_size, "NotImplementedError: NotImplementedError"
exclude :test_size=, "NotImplementedError: NotImplementedError"
exclude :test_to_ptr_io, "NotImplementedError: NotImplementedError"
exclude :test_to_ptr_string, "NoMethodError: undefined method `string_pointer_to_native' for Truffle::CExt:Module"
exclude :test_to_ptr_with_num, "NotImplementedError: NotImplementedError"
exclude :test_to_ptr_with_ptr, "NotImplementedError: NotImplementedError"
exclude :test_to_s, "NoMethodError: undefined method `string_pointer_to_native' for Truffle::CExt:Module"
exclude :test_to_str, "NoMethodError: undefined method `string_pointer_to_native' for Truffle::CExt:Module"
exclude :test_to_value, "NotImplementedError: NotImplementedError"
