exclude :test_disable_close, "NotImplementedError: NotImplementedError"
exclude :test_enable_close, "NotImplementedError: NotImplementedError"
exclude :test_file_name, "NoMethodError: undefined method `file_name' for #<Fiddle::Handle:0x3e8>"
exclude :test_handle_close, "NotImplementedError: NotImplementedError"
exclude :test_handle_close_twice, "NotImplementedError: NotImplementedError"
exclude :test_static_sym, "NotImplementedError: NotImplementedError"
exclude :test_static_sym_unknown, "[Fiddle::DLError] exception expected, not #<NotImplementedError: NotImplementedError>."
exclude :test_sym, "NoMethodError: undefined method `sym_defined?' for #<Fiddle::Handle:0x4a8>"
exclude :test_sym_closed_handle, "NotImplementedError: NotImplementedError"
exclude :test_sym_unknown, "[Fiddle::DLError] exception expected, not #<NameError: Unknown identifier: fooo>."
exclude :test_to_i, "NotImplementedError: NotImplementedError"
exclude :test_to_ptr, "NoMethodError: undefined method `to_ptr' for #<Fiddle::Handle:0x528>"
