exclude :test_gettimeofday, "NotImplementedError: NotImplementedError"
exclude :test_io, "NotImplementedError: #<IO:fd 8> to pointer"
exclude :test_malloc, "NotImplementedError: NotImplementedError"
exclude :test_nested_struct_alignment_is_not_its_size, "NotImplementedError: NotImplementedError"
exclude :test_sizeof, "NotImplementedError: NotImplementedError"
exclude :test_sizeof_bool, "NameError: uninitialized constant Fiddle::Importer::TYPE_CONST_STRING"
exclude :test_sizeof_int64_t, "NameError: uninitialized constant Fiddle::Importer::TYPE_CONST_STRING"
exclude :"test_sizeof_long long", "NameError: uninitialized constant Fiddle::Importer::TYPE_CONST_STRING"
exclude :test_sizeof_uint64_t, "NameError: uninitialized constant Fiddle::Importer::TYPE_CONST_STRING"
exclude :"test_sizeof_ulong long", "NameError: uninitialized constant Fiddle::Importer::TYPE_CONST_STRING"
exclude :test_strcpy, "NotImplementedError: NotImplementedError"
exclude :test_struct, "NotImplementedError: NotImplementedError"
exclude :test_struct_array_assignment, "NotImplementedError: NotImplementedError"
exclude :test_struct_memory_access, "NotImplementedError: NotImplementedError"
exclude :test_struct_nested_struct_members, "NotImplementedError: NotImplementedError"
exclude :test_struct_nested_struct_replace_array_element, "NotImplementedError: NotImplementedError"
exclude :test_struct_nested_struct_replace_array_element_hash, "NotImplementedError: NotImplementedError"
exclude :test_struct_nested_struct_replace_array_element_nil, "NotImplementedError: NotImplementedError"
exclude :test_struct_nested_struct_replace_entire_array, "NotImplementedError: NotImplementedError"
exclude :test_struct_nested_struct_replace_entire_array_with_different_struct, "NotImplementedError: NotImplementedError"
exclude :test_struct_ptr_array_subscript_multiarg, "NotImplementedError: NotImplementedError"
exclude :test_union_nested_struct_members, "NotImplementedError: NotImplementedError"
exclude :test_unsigned_result, "NotImplementedError: 2147483649 from type -5"
exclude :test_value, "NotImplementedError: NotImplementedError"
