exclude :test_aref_pointer, "NotImplementedError: NotImplementedError"
exclude :test_aref_pointer_array, "NotImplementedError: NotImplementedError"
exclude :test_free, "NotImplementedError: NotImplementedError"
exclude :test_free_with_func, "NotImplementedError: NotImplementedError"
exclude :test_free_with_no_func, "NotImplementedError: NotImplementedError"
exclude :test_freed?, "NotImplementedError: NotImplementedError"
exclude :test_malloc_block, "NotImplementedError: NotImplementedError"
exclude :test_malloc_block_no_free, "[ArgumentError] exception expected, not #<NotImplementedError: NotImplementedError>."
exclude :test_new_double_free, "NotImplementedError: NotImplementedError"
exclude :test_null?, "NotImplementedError: NotImplementedError"
exclude :test_set_ctypes, "NotImplementedError: NotImplementedError"
exclude :test_size, "NotImplementedError: NotImplementedError"
exclude :test_size=, "NotImplementedError: NotImplementedError"
