exclude :test_class_size, "needs investigation"
exclude :test_class_size_with_count, "needs investigation"
exclude :test_aref_pointer, "needs investigation"
exclude :test_aref_pointer_array, "needs investigation"
exclude :test_set_ctypes, "needs investigation"
