exclude :test_argument_errors, "needs investigation"
exclude :test_conversion_char, "needs investigation"
exclude :test_conversion_long, "needs investigation"
exclude :test_conversion_long_long, "needs investigation"
exclude :test_conversion_short, "needs investigation"
exclude :test_conversion_unsigned_char, "needs investigation"
exclude :test_conversion_unsigned_int, "needs investigation"
exclude :test_conversion_unsigned_long, "needs investigation"
exclude :test_conversion_unsigned_long_long, "needs investigation"
exclude :test_conversion_unsigned_short, "needs investigation"
exclude :test_type_symbol, "needs investigation"
exclude :test_const_string, "needs investigation"
exclude :test_free, "NoMethodError: undefined method `freed?' for #<Fiddle::Closure:0x10ac3c8>"
exclude :test_returner, "NoMethodError: undefined method `freed?' for #<#<Class:0x10ac408>:0x10ac438>"
exclude :test_call, "NoMethodError: undefined method `freed?' for #<#<Class:0x10ac478>:0x10ac498>"
exclude :test_conversion_int, "NoMethodError: undefined method `freed?' for #<#<Class:0x10ac4d8>:0x10ac508>"
exclude :test_memsize_ruby_dev_42480, "NoMethodError: undefined method `freed?' for #<Fiddle::Closure:0x10ac558>"
exclude :test_block_caller, "NoMethodError: undefined method `freed?' for #<Fiddle::Closure::BlockCaller:0x10ac5b8>"
