exclude :test_static_sym_unknown, "needs investigation"
exclude :test_sym_unknown, "needs investigation"
exclude :test_disable_close, "needs investigation"
exclude :test_enable_close, "needs investigation"
exclude :test_handle_close, "needs investigation"
exclude :test_handle_close_twice, "needs investigation"
exclude :test_initialize_noargs, "needs investigation"
exclude :test_static_sym, "needs investigation"
exclude :test_sym_closed_handle, "needs investigation"
exclude :test_to_i, "needs investigation"
exclude :test_file_name, "NoMethodError: undefined method `file_name' for #<Fiddle::Handle:0xc63718>"
exclude :test_to_ptr, "NoMethodError: undefined method `to_ptr' for #<Fiddle::Handle:0xc63768>"
