exclude :test_open_encoding_nonexistent, "ArgumentError: unknown encoding name - nonexistent"
exclude :test_open_with_invalid_replace, "Encoding::InvalidByteSequenceError: \"\\x82\" on UTF-8"
exclude :test_open_with_invalid_replace_and_replace_string, "Encoding::InvalidByteSequenceError: \"\\x82\" on UTF-8"
exclude :test_open_with_newline, "CSV::MalformedCSVError: Unquoted fields do not allow new line <\"\\n\"> in line 2."
exclude :test_open_with_undef_replace, "Encoding::UndefinedConversionError: \"\\xC2\\xB7\" to Windows-31J in conversion from UTF-8 to Windows-31J"
exclude :test_open_with_undef_replace_and_replace_string, "Encoding::UndefinedConversionError: \"\\xC2\\xB7\" to Windows-31J in conversion from UTF-8 to Windows-31J"
