#!/bin/bash

set -ex

SCRIPT_PATH=$(dirname "$0")
SCRIPT_PATH=$(cd "$SCRIPT_PATH" && pwd)
TRUFFLERUBY_DIR=$SCRIPT_PATH/..

if [ ! -z "$SPIN" ]; then
  echo "source '$TRUFFLERUBY_DIR/.spin/env-custom'" > ~/.zshrc.d/truffleruby
fi

export SPIN_INITIALIZING=true
source "$TRUFFLERUBY_DIR"/.spin/env-custom

mkdir -p ~/.rubies

pushd "$TRUFFLERUBY_DIR"
jt install jvmci
jt install eclipse
jt mx sforceimports
jt build
jt idea
jt ruby --version
popd
