exclude :test_ar2st, "mutating Hash during key.hash"
exclude :test_to_proc, "<true> expected but was"
exclude :test_huge_iter_level, "RuntimeError expected but nothing was raised."
exclude :test_merge!, "FrozenError expected but nothing was raised."
exclude :test_create, "ArgumentError expected but nothing was raised."
exclude :test_callcc_reenter, "[ruby-dev:47803] [Bug #9105]."
exclude :test_select_reject_will_not_rehash, "<1> expected but was"
exclude :test_reject_on_identhash, "<{}> expected but was"
exclude :test_select_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was"
exclude :test_slice_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was"
exclude :test_shift2, "<:foo> expected but was"
exclude :test_NEWHASH_fstring_key, "Expected \"ABC\" (oid=44424) to be the same as \"ABC\" (oid=48)."
exclude :test_inverse_hash, "[ruby-core:34334]."
exclude :test_rehash2, "RuntimeError expected but nothing was raised."
exclude :test_shift_none, "<\"FOO\"> expected but was"
exclude :test_update5, "FrozenError expected but nothing was raised."
exclude :test_transform_values_on_identhash, "<{1=>2, 3=>4, 5=>6, \"str\"=>1, \"str\"=>2}> expected but was"
exclude :test_s_AREF_from_pairs, "ArgumentError expected but nothing was raised."
exclude :test_any_hash_fixable, "too slow"
exclude :test_recursive_hash_value_struct, "[ruby-core:58567] [Bug #9151]."
exclude :test_reject, "Expected {1=>\"one\", 2=>false, true=>\"true\", \"cat\"=>99} to be an instance of Hash, not TestHash::TestSubHash::SubHash."
exclude :test_transform_keys_bang, "<{false=>1, :b=>2, :c=>3}> expected but was"
exclude :test_callcc_escape, "[ruby-dev:47803] [Bug #9105]."
exclude :test_ASET_fstring_key, "Expected \"abc\" (oid=84584) to be the same as \"abc\" (oid=84600)."
exclude :test_fetch_error, "Expected /\\.\\.\\.\\z/ to match \"key not found: \\\"gumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumby\\\"\"."
exclude :test_ASET_fstring_non_literal_key, "Expected \"abc_def\" (oid=85320) to be the same as \"abc_def\" (oid=85336)."
exclude :test_callcc, "RuntimeError: Continuations are unsupported on TruffleRuby"
exclude :test_AREF_fstring_key, "NoMethodError: undefined method `count_objects' for ObjectSpace:Module"
exclude :test_callcc_iter_level, "RuntimeError: Continuations are unsupported on TruffleRuby"
