exclude :test_ar2st, "mutating Hash during key.hash"
exclude :test_ASET_fstring_key, "needs investigation"
exclude :test_ASET_fstring_non_literal_key, "needs investigation"
exclude :test_NEWHASH_fstring_key, "needs investigation"
exclude :test_callcc_escape, "needs investigation"
exclude :test_callcc_reenter, "needs investigation"
exclude :test_create, "needs investigation"
exclude :test_dup_equality, "needs investigation"
exclude :test_dup_will_rehash, "needs investigation"
exclude :test_fetch_error, "needs investigation"
exclude :test_huge_iter_level, "needs investigation"
exclude :test_inverse_hash, "needs investigation"
exclude :test_recursive_hash_value_struct, "needs investigation"
exclude :test_rehash2, "needs investigation"
exclude :test_reject, "needs investigation"
exclude :test_ruby2_keywords_hash?, "needs investigation"
exclude :test_s_AREF, "needs investigation"
exclude :test_callcc, "needs investigation"
exclude :test_callcc_iter_level, "needs investigation"
exclude :test_bug_12706, "needs investigation"
exclude :test_to_proc, "needs investigation"
exclude :test_transform_keys_bang, "needs investigation"
exclude :test_AREF_fstring_key, "needs investigation"
exclude :test_except, "needs investigation"
exclude :test_transform_keys, "needs investigation"
exclude :test_select_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was"
exclude :test_slice_on_identhash, "<{\"str\"=>1, \"str\"=>2}> expected but was"
exclude :test_reject_on_identhash, "<{}> expected but was"
exclude :test_select_reject_will_not_rehash, "<1> expected but was"
exclude :test_merge!, "FrozenError expected but nothing was raised."
exclude :test_update5, "FrozenError expected but nothing was raised."
exclude :test_transform_values_on_identhash, "<{1=>2, 3=>4, 5=>6, \"str\"=>1, \"str\"=>2}> expected but was"
exclude :test_s_AREF_from_pairs, "ArgumentError expected but nothing was raised."
